### ISSUE TITLE
Android4.4.2点击全屏闪退

### ISSUE THREAD

**Issue by CaiXiaoDong1991** [lipangit/JiaoZiVideoPlayer#1121]
FATAL EXCEPTION: main
                                                                             java.lang.RuntimeException: Error during detachFromGLContext (see logcat for details)
                                                                                 at android.graphics.SurfaceTexture.attachToGLContext(SurfaceTexture.java:237)
                                                                                 at android.view.GLES20TextureLayer.setSurfaceTexture(GLES20TextureLayer.java:81)
                                                                                 at android.view.HardwareRenderer$Gl20Renderer.setSurfaceTexture(HardwareRenderer.java:1576)
                                                                                 at android.view.TextureView.getHardwareLayer(TextureView.java:393)
                                                                                 at android.view.View.getDisplayList(View.java:12809)
                                                                                 at android.view.View.getDisplayList(View.java:12890)
                                                                                 at android.view.View.draw(View.java:13640)
                                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3050)
                                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2912)
                                                                                 at android.view.View.getDisplayList(View.java:12841)
                                                                                 at android.view.View.getDisplayList(View.java:12890)
                                                                                 at android.view.View.draw(View.java:13640)
                                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3050)
                                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2912)
                                                                                 at android.view.View.draw(View.java:13947)
                                                                                 at android.view.View.getDisplayList(View.java:12846)
                                                                                 at android.view.View.getDisplayList(View.java:12890)
                                                                                 at android.view.View.draw(View.java:13640)
                                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3050)
                                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2912)
                                                                                 at android.view.View.getDisplayList(View.java:12841)
                                                                                 at android.view.View.getDisplayList(View.java:12890)
                                                                                 at android.view.View.draw(View.java:13640)
                                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3050)
                                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2912)
                                                                                 at android.view.View.draw(View.java:13947)
                                                                                 at android.widget.FrameLayout.draw(FrameLayout.java:467)
                                                                                 at android.view.View.getDisplayList(View.java:12846)
                                                                                 at android.view.View.getDisplayList(View.java:12890)
                                                                                 at android.view.View.draw(View.java:13640)
                                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3050)
                                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2912)
                                                                                 at android.view.View.draw(View.java:13947)
                                                                                 at android.support.v7.widget.ActionBarOverlayLayout.draw(ActionBarOverlayLayout.java:444)
                                                                                 at android.view.View.getDisplayList(View.java:12846)
                                                                                 at android.view.View.getDisplayList(View.java:12890)
                                                                                 at android.view.View.draw(View.java:13640)
                                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3050)
                                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2912)
                                                                                 at android.view.View.getDisplayList(View.java:12841)
                                                                                 at android.view.View.getDisplayList(View.java:12890)
                                                                                 at android.view.View.draw(View.java:13640)
                                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3050)
                                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2912)
                                                                                 at android.view.View.getDisplayList(View.java:12841)
                                                                                 at android.view.View.getDisplayList(View.java:12890)
                                                                                 at android.view.View.draw(View.java:13640)
                                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3050)
                                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2912)
                                                                                 at android.view.View.draw(View.java:13947)
                                                                                 at android.widget.FrameLayout.draw(FrameLayout.java:467)
                                                                                 at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2247)
                                                                                 at android.view.View.getDisplayList(View.java:12846)
                                                                                 at android.view.View.getDisplayList(View.java:12890)
                                                                                 at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1249)
                                                                                 at android.view.ViewRootImpl.draw(ViewRootImpl.java:2572)
                                                                                 at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2439)
                                                                                 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2241)
                                                                                 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1216)
                                                                                 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5044)
                                                                                 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:776)
                                                                                 at android.view.Choreographer.doCallbacks(Choreographer.java:579)
                                                                                 at android.view.Choreographer.doFrame(Choreographer.java:548)
                                                                                 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:762)
                                                                                 at android.os.Handler.handleCallback(Handler.java:800)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                 at android.os.Looper.loop(Looper.java:194)
                                                                             	at android.app.Acti

**Comment by Seamo** [comment]
播放器所在的Activity继承AppCompatActivity了吗
没有的话继承一下再试

**Comment by CaiXiaoDong1991** [comment]
您好！我是直接运行github上的demo的，我看了一下是有继承AppCompatActivity的，我Google了一下说是Android4.4或以下版本的bug，需要对继承TextureView的类做特殊处理，但我不知道怎么改？ 这里有个一样的问题https://github.com/google/ExoPlayer/issues/737

**Comment by Seamo** [comment]
好像这个问题也有人提过 #750 
方便说下手机型号吗？

**Comment by CaiXiaoDong1991** [comment]
华为荣耀3C，比较老的机子了，对了系统版本是4.2.2,！不好意思刚才说错了~~

**Comment by Seamo** [comment]
既然是系统bug，那从应用层面上恐怕不太好收拾
我先把手边设备降个级回4.2.2试试能不能复现，研究一下

**Comment by CaiXiaoDong1991** [comment]
嗯嗯，好的，十分谢谢！我刚才发的那个链接里面的好像就是判断低于4.4就做一些特殊处理的~~

**Comment by JayneeLegend** [comment]
想请问一下 关于这个问题 有最终的解决方案了吗？我在使用的过程中也是在荣耀4.2.2上遇到了同样的问题。

**Comment by ldy441040480** [comment]
我解决了，后续提交一个pr

**Comment by JayneeLegend** [comment]
@ldy441040480  能否把解决的代码 贴一下呢 ？ 挺着急的

**Comment by ldy441040480** [comment]
已提交：https://github.com/lipangit/JieCaoVideoPlayer/pull/1140

**Comment by JayneeLegend** [comment]
非常感谢 我这就去看看
