### ISSUE TITLE
全屏播放完成后，调用 mVideo.startButton.performClick()报错

### ISSUE THREAD

**Issue by lizi0588** [lipangit/JiaoZiVideoPlayer#1126]
报错如下：
AndroidRuntime: FATAL EXCEPTION: main
                                                         java.lang.NullPointerException
                                                             at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.showSupportActionBar(JCVideoPlayer.java:909)
                                                             at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.clearFullscreenLayout(JCVideoPlayer.java:623)
                                                             at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onCompletion(JCVideoPlayer.java:558)
                                                             at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.onCompletion(JCVideoPlayerStandard.java:909)
                                                             at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerManager.completeAll(JCVideoPlayerManager.java:42)
                                                             at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.startVideo(JCVideoPlayer.java:348)
                                                             at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onClick(JCVideoPlayer.java:209)
                                                             at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.onClick(JCVideoPlayerStandard.java:230)
                                                             at android.view.View.performClick(View.java:4084)
                                                             at com.recon.ui.fragment.VideoRepairPushFragment.onClick(VideoRepairPushFragment.java:104)
                                                             at com.recon.ui.fragment.VideoRepairPushFragment_ViewBinding$3.doClick(VideoRepairPushFragment_ViewBinding.java:64)
                                                             at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
                                                             at android.view.View.performClick(View.java:4084)
                                                             at android.view.View.onKeyUp(View.java:7669)
                                                             at android.widget.TextView.onKeyUp(TextView.java:5328)
                                                             at android.view.KeyEvent.dispatch(KeyEvent.java:2633)
                                                             at android.view.View.dispatchKeyEvent(View.java:7086)
                                                             at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1358)
                                                             at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1358)
                                                             at android.support.v4.view.ViewPager.dispatchKeyEvent(ViewPager.java:2761)
                                                             at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1358)
                                                             at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1358)
                                                             at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1358)
                                                             at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1358)
                                                             at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchKeyEvent(PhoneWindow.java:1892)
                                                             at com.android.internal.policy.impl.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1369)
                                                             at android.app.Activity.dispatchKeyEvent(Activity.java:2366)
                                                             at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:1819)
                                                             at android.view.ViewRootImpl.deliverKeyEventPostIme(ViewRootImpl.java:3577)
                                                             at android.view.ViewRootImpl.handleImeFinishedEvent(ViewRootImpl.java:3547)
                                                             at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:2797)
                                                             at android.os.Handler.dispatchMessage(Handler.java:99)
                                                             at android.os.Looper.loop(Looper.java:137)
                                                             at android.app.ActivityThread.main(ActivityThread.java:4745)
                                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                                             at java.lang.reflect.Method.invoke(Method.java:511)
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                             at dalvik.system.NativeStart.main(Native Method)

在播放视频的时候也在进行语音通话，这个会有影响吗？

**Comment by lipangit** [comment]
包含视频的actiivity要继承Appcompactactivity
