### ISSUE TITLE
Attempt to invoke virtual method 'int java.util.LinkedHashMap.size()

### ISSUE THREAD

**Issue by xiongke15117937934** [lipangit/JiaoZiVideoPlayer#1150]
```
08-16 16:15:47.307 26839-26839/com.xk.gvido.app E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: com.xk.gvido.app, PID: 26839
                                                                  java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.LinkedHashMap.size()' on a null object reference
                                                                      at fm.jiecao.jcvideoplayer_lib.JCUtils.getCurrentUrlFromMap(JCUtils.java:128)
                                                                      at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.onClick(JCVideoPlayerStandard.java:233)
                                                                      at android.view.View.performClick(View.java:5204)
                                                                      at android.view.View$PerformClick.run(View.java:21153)
                                                                      at android.os.Handler.handleCallback(Handler.java:739)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by lipangit** [comment]
传进setUp的参数是什么
