### ISSUE TITLE
vivo y17t android 4.2.2 API17,视频播放时切换大小屏幕崩溃

### ISSUE THREAD

**Issue by wjy591416** [lipangit/JiaoZiVideoPlayer#1176]
FATAL EXCEPTION: main
                                                                       java.lang.RuntimeException: Error during detachFromGLContext (see logcat for details)
                                                                           at android.graphics.SurfaceTexture.attachToGLContext(SurfaceTexture.java:237)
                                                                           at android.view.GLES20TextureLayer.setSurfaceTexture(GLES20TextureLayer.java:81)
                                                                           at android.view.HardwareRenderer$Gl20Renderer.setSurfaceTexture(HardwareRenderer.java:1576)
                                                                           at android.view.TextureView.getHardwareLayer(TextureView.java:393)
                                                                           at android.view.View.getDisplayList(View.java:12731)
                                                                           at android.view.View.getDisplayList(View.java:12806)
                                                                           at android.view.View.draw(View.java:13540)
                                                                           at android.view.ViewGroup.drawChild(ViewGroup.java:3022)
                                                                           at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2886)
                                                                           at android.view.View.getDisplayList(View.java:12760)
                                                                           at android.view.View.getDisplayList(View.java:12806)
                                                                           at android.view.View.draw(View.java:13540)
                                                                           at android.view.ViewGroup.drawChild(ViewGroup.java:3022)
                                                                           at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2886)
                                                                           at android.view.View.draw(View.java:13835)
                                                                           at android.view.View.getDisplayList(View.java:12762)
                                                                           at android.view.View.getDisplayList(View.java:12806)
                                                                           at android.view.View.draw(View.java:13540)
                                                                           at android.view.ViewGroup.drawChild(ViewGroup.java:3022)
                                                                           at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2886)
                                                                           at android.view.View.getDisplayList(View.java:12760)
                                                                           at android.view.View.getDisplayList(View.java:12806)
                                                                           at android.view.View.draw(View.java:13540)
                                                                           at android.view.ViewGroup.drawChild(ViewGroup.java:3022)
                                                                           at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2886)
                                                                           at android.view.View.getDisplayList(View.java:12760)
                                                                           at android.view.View.getDisplayList(View.java:12806)
                                                                           at android.view.View.draw(View.java:13540)
                                                                           at android.view.ViewGroup.drawChild(ViewGroup.java:3022)
                                                                           at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2886)
                                                                           at android.view.View.getDisplayList(View.java:12760)
                                                                           at android.view.View.getDisplayList(View.java:12806)
                                                                           at android.view.View.draw(View.java:13540)
                                                                           at android.view.ViewGroup.drawChild(ViewGroup.java:3022)
                                                                           at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2886)
                                                                           at android.view.View.getDisplayList(View.java:12760)
                                                                           at android.view.View.getDisplayList(View.java:12806)
                                                                           at android.view.View.draw(View.java:13540)
                                                                           at android.view.ViewGroup.drawChild(ViewGroup.java:3022)
                                                                           at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2886)
                                                                           at android.view.View.getDisplayList(View.java:12760)
                                                                           at android.view.View.getDisplayList(View.java:12806)
                                                                           at android.view.View.draw(View.java:13540)
                                                                           at android.view.ViewGroup.drawChild(ViewGroup.java:3022)
                                                                           at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2886)
                                                                           at android.view.View.draw(View.java:13835)
                                                                           at android.widget.FrameLayout.draw(FrameLayout.java:467)
                                                                           at android.view.View.getDisplayList(View.java:12762)
                                                                           at android.view.View.getDisplayList(View.java:12806)
                                                                           at android.view.View.draw(View.java:13540)
                                                                           at android.view.ViewGroup.drawChild(ViewGroup.java:3022)
                                                                           at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2886)
                                                                           at android.view.View.getDisplayList(View.java:12760)
                                                                           at android.view.View.getDisplayList(View.java:12806)
                                                                           at android.view.View.draw(View.java:13540)
                                                                           at android.view.ViewGroup.drawChild(ViewGroup.java:3022)
                                                                           at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2886)
                                                                           at android.view.View.getDisplayList(View.java:12760)
                                                                           at android.view.View.getDisplayList(View.java:12806)
                                                                           at android.view.View.draw(View.java:13540)
                                                                           at android.view.ViewGroup.drawChild(ViewGroup.java:3022)
                                                                           at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2886)
                                                                           at android.view.View.getDisplayList(View.java:12760)
                                                                           at android.view.View.getDisplayList(View.java:12806)
                                                                           at android.view.View.draw(View.java:13540)
                                                                           at android.view.ViewGroup.drawChild(ViewGroup.java:3022)
                                                                           at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2886)
                                                                           at android.view.View.draw(View.java:13835)
                                                                           at android.widget.FrameLayout.draw(FrameLayout.java:467)
                                                                           at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2236)

**Comment by bifan-wei** [comment]
请问我也是这个问题，解决了么

**Comment by wjy591416** [comment]
@bifan-wei 已经解决，https://github.com/lipangit/JiaoZiVideoPlayer/pull/1140
