### ISSUE TITLE
友盟的crashlog，看看这个怎么处理

### ISSUE THREAD

**Issue by demonzym** [lipangit/JiaoZiVideoPlayer#1184]
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
	at android.view.ViewGroup.addViewInner(ViewGroup.java:4066)
	at android.view.ViewGroup.addView(ViewGroup.java:3916)
	at android.view.ViewGroup.addView(ViewGroup.java:3888)
	at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.addTextureView(JCVideoPlayer.java:557)
	at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.playOnThisJcvd(JCVideoPlayer.java:825)
	at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.backPress(JCVideoPlayer.java:838)
	at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onAutoCompletion(JCVideoPlayer.java:491)
	at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.onAutoCompletion(JCVideoPlayerStandard.java:832)
	at fm.jiecao.jcvideoplayer_lib.JCMediaManager$2.run(JCMediaManager.java:164)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5706)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1033)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)

**Comment by lipangit** [comment]
textureView已经有一个父类之后又addView到父类，报的错误。

能复现吗，还有其他线索吗

**Comment by demonzym** [comment]
没有哦  是发布在外面的app返回的一个log   我也复现不出来  界面的话  是上面一个videoplayer 下面一个recyclerview  没有什么特别的部分

**Comment by lipangit** [comment]
解决了吗
