### ISSUE TITLE
空指针异常当视频切换全屏和点击手机物理键返回时(actionBar为空）

### ISSUE THREAD

**Issue by wh121** [lipangit/JiaoZiVideoPlayer#1189]
om.wh.wang.scroopclassproject E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.wh.wang.scroopclassproject, PID: 3454
                                                                              java.lang.NullPointerException
                                                                                  at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.hideSupportActionBar(JCVideoPlayer.java:224)
                                                                                  at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.startWindowFullscreen(JCVideoPlayer.java:853)
                                                                                  at com.wh.wang.scroopclassproject.views.MyJCVideoPlayerStandard.startWindowFullscreen(MyJCVideoPlayerStandard.java:107)
                                                                                  at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onClick(JCVideoPlayer.java:338)
                                                                                  at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.onClick(JCVideoPlayerStandard.java:266)
                                                                                  at com.wh.wang.scroopclassproject.views.MyJCVideoPlayerStandard.onClick(MyJCVideoPlayerStandard.java:31)
                                                                                  at android.view.View.performClick(View.java:4438)
                                                                                  at android.view.View$PerformClick.run(View.java:18422)
                                                                                  at android.os.Handler.handleCallback(Handler.java:733)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                  at android.os.Looper.loop(Looper.java:136)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5019)
                                                                                  at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                  at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                                                  at dalvik.system.NativeStart.main(Native Method)

**Comment by lipangit** [comment]
包含视频的activity要继承Appcompactactivity，log里的空指针是不是
![image](https://user-images.githubusercontent.com/2038071/29914127-fa449130-8e69-11e7-841c-0764d0b8cf8d.png) activity是空

**Comment by wh121** [comment]
我是直接继承activity   没有继承Appcompactactivity 所以我想自己写一个自己想要的actionbar可以吗？
<activity
            android:name=".activity.VideoInfosActivity"
            android:configChanges="orientation|screenSize|keyboardHidden"
            android:screenOrientation="portrait" />

**Comment by wh121** [comment]
不继承Appcompactactivity 不行么？

**Comment by lipangit** [comment]
不继承Appcompactactivity就得改库了
