### ISSUE TITLE
java.lang.RuntimeException: Error during detachFromGLContext

### ISSUE THREAD

**Issue by bifan-wei** [lipangit/JiaoZiVideoPlayer#1302]
全屏直接崩了，华为4.2系统，这个问题好像比较多人遇到，能不能捕捉一下，别让它崩

  java.lang.RuntimeException: Error during detachFromGLContext (see logcat for details)
                                                                          at android.graphics.SurfaceTexture.attachToGLContext(SurfaceTexture.java:237)
                                                                          at android.view.GLES20TextureLayer.setSurfaceTexture(GLES20TextureLayer.java:81)
                                                                          at android.view.HardwareRenderer$Gl20Renderer.setSurfaceTexture(HardwareRenderer.java:1576)
                                                                          at android.view.TextureView.getHardwareLayer(TextureView.java:393)
                                                                          at android.view.View.getDisplayList(View.java:12809)
                                                                          at android.view.View.getDisplayList(View.java:12890)
                                                                          at android.view.View.draw(View.java:13640)
                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3050)
                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2912)
                                                                          at android.view.View.getDisplayList(View.java:12841)
                                                                          at android.view.View.getDisplayList(View.java:12890)
                                                                          at android.view.View.draw(View.java:13640)
                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3050)
                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2912)
                                                                          at android.view.View.draw(View.java:13947)
                                                                          at android.view.View.getDisplayList(View.java:12846)
                                                                          at android.view.View.getDisplayList(View.java:12890)
                                                                          at android.view.View.draw(View.java:13640)
                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3050)
                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2912)
                                                                          at android.view.View.getDisplayList(View.java:12841)
                                                                          at android.view.View.getDisplayList(View.java:12890)
                                                                          at android.view.View.draw(View.java:13640)
                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3050)
                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2912)
                                                                          at android.view.View.getDisplayList(View.java:12841)
                                                                          at android.view.View.getDisplayList(View.java:12890)
                                                                          at android.view.View.draw(View.java:13640)
                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3050)
                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2912)
                                                                          at android.view.View.getDisplayList(View.java:12841)
                                                                          at android.view.View.getDisplayList(View.java:12890)
                                                                          at android.view.View.draw(View.java:13640)
                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3050)
                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2912)
                                                                          at android.view.View.getDisplayList(View.java:12841)
                                                                          at android.view.View.getDisplayList(View.java:12890)
                                                                          at android.view.View.draw(View.java:13640)
                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3050)
                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2912)
                                                                          at android.view.View.getDisplayList(View.java:12841)
                                                                          at android.view.View.getDisplayList(View.java:12890)
                                                                          at android.view.View.draw(View.java:13640)
                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3050)
                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2912)
                                                                          at android.view.View.draw(View.java:13947)
                                                                          at android.widget.FrameLayout.draw(FrameLayout.java:467)
                                                                          at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2247)
                                                                          at android.view.View.getDisplayList(View.java:12846)
                                                                          at android.view.View.getDisplayList(View.java:12890)
                                                                          at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1249)
                                                                          at android.view.ViewRootImpl.draw(ViewRootImpl.java:2567)
                                                                          at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2434)
                                                                          at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2236)
                                                                          at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1211)
                                                                          at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5039)
                                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:776)
                                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:579)
                                                                          at android.view.Choreographer.doFrame(Choreographer.java:548)
                                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:762)
                                                                          at android.os.Handler.handleCallback(Handler.java:800)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                          at android.os.Looper.loop(Looper.java:194)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5433)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:525)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:922)

**Comment by lipangit** [comment]
这个即便不崩溃应该也是全屏失败

试试这个https://github.com/lipangit/JiaoZiVideoPlayer/pull/1140
