### ISSUE TITLE
java.lang.RuntimeException: Error during detachFromGLContext

### ISSUE THREAD

**Issue by saefbadwan** [lipangit/JiaoZiVideoPlayer#1331]
This problem happen when the full screen is in the landscape mode and the video about to finish and exit the fullscreen mode it crashes ,, it dose not happen if the user exit manually before the video finishes
Extra -> Device : Huawei

>  E/GLConsumer: [unnamed-28153-0] bindUnslottedBuffer: error binding external texture image 0x10000002 (slot -1): 0x502
10-31 09:50:46.676 28153-28153/com.network.imyth.network D/AndroidRuntime: Shutting down VM
10-31 09:50:46.676 28153-28153/com.network.imyth.network W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41594bc0)
10-31 09:50:46.696 28153-28153/com.network.imyth.network E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: com.network.imyth.network, PID: 28153
                                                                           java.lang.RuntimeException: Error during attachToGLContext (see logcat for details)
                                                                               at android.graphics.SurfaceTexture.attachToGLContext(SurfaceTexture.java:215)
                                                                               at android.view.GLES20TextureLayer.setSurfaceTexture(GLES20TextureLayer.java:86)
                                                                               at android.view.HardwareRenderer$Gl20Renderer.setSurfaceTexture(HardwareRenderer.java:2226)
                                                                               at android.view.TextureView.getHardwareLayer(TextureView.java:401)
                                                                               at android.view.View.getDisplayList(View.java:13344)
                                                                               at android.view.View.getDisplayList(View.java:13420)
                                                                               at android.view.View.draw(View.java:14205)
                                                                               at android.view.ViewGroup.drawChild(ViewGroup.java:3127)
                                                                               at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2964)
                                                                               at android.view.View.getDisplayList(View.java:13373)
                                                                               at android.view.View.getDisplayList(View.java:13420)
                                                                               at android.view.View.draw(View.java:14205)
                                                                               at android.view.ViewGroup.drawChild(ViewGroup.java:3127)
                                                                               at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2964)
                                                                               at android.view.View.draw(View.java:14491)
                                                                               at android.view.View.getDisplayList(View.java:13378)
                                                                               at android.view.View.getDisplayList(View.java:13420)
                                                                               at android.view.View.draw(View.java:14205)
                                                                               at android.view.ViewGroup.drawChild(ViewGroup.java:3127)
                                                                               at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2964)
                                                                               at android.view.View.getDisplayList(View.java:13373)
                                                                               at android.view.View.getDisplayList(View.java:13420)
                                                                               at android.view.View.draw(View.java:14205)
                                                                               at android.view.ViewGroup.drawChild(ViewGroup.java:3127)
                                                                               at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2964)
                                                                               at android.view.View.getDisplayList(View.java:13373)
                                                                               at android.view.View.getDisplayList(View.java:13420)
                                                                               at android.view.View.draw(View.java:14205)
                                                                               at android.view.ViewGroup.drawChild(ViewGroup.java:3127)
                                                                               at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2964)
                                                                               at android.view.View.getDisplayList(View.java:13373)
                                                                               at android.view.View.getDisplayList(View.java:13420)
                                                                               at android.view.View.draw(View.java:14205)
                                                                               at android.view.ViewGroup.drawChild(ViewGroup.java:3127)
                                                                               at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2964)
                                                                               at android.view.View.getDisplayList(View.java:13373)
                                                                               at android.view.View.getDisplayList(View.java:13420)
                                                                               at android.view.View.draw(View.java:14205)
                                                                               at android.view.ViewGroup.drawChild(ViewGroup.java:3127)
                                                                               at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2964)
                                                                               at android.view.View.draw(View.java:14491)
                                                                               at android.view.View.getDisplayList(View.java:13378)
                                                                               at android.view.View.getDisplayList(View.java:13420)
                                                                               at android.view.View.draw(View.java:14205)
                                                                               at android.view.ViewGroup.drawChild(ViewGroup.java:3127)
                                                                               at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4581)
                                                                               at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2964)
                                                                               at android.view.View.draw(View.java:14491)
                                                                               at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3987)
                                                                               at android.view.View.getDisplayList(View.java:13378)
                                                                               at android.view.View.getDisplayList(View.java:13420)
                                                                               at android.view.View.draw(View.java:14205)
                                                                               at android.view.ViewGroup.drawChild(ViewGroup.java:3127)
                                                                               at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2964)
                                                                               at android.view.View.getDisplayList(View.java:13373)
                                                                               at android.view.View.getDisplayList(View.java:13420)
                                                                               at android.view.View.draw(View.java:14205)
                                                                               at android.view.ViewGroup.drawChild(ViewGroup.java:3127)
                                                                               at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2964)
                                                                               at android.view.View.getDisplayList(View.java:13373)
                                                                               at android.view.View.getDisplayList(View.java:13420)
                                                                               at android.view.View.draw(View.java:14205)
                                                                               at android.view.ViewGroup.drawChild(ViewGroup.java:3127)
                                                                               at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2971)
                                                                               at android.view.View.draw(View.java:14491)
                                                                               at android.view.View.getDisplayList(View.java:13378)
                                                                               at android.view.View.getDisplayList(View.java:13420)
                                                                               at android.view.View.draw(View.java:14205)
                                                                               at android.view.ViewGroup.drawChild(ViewGroup.java:3127)
                                                                               at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2964)
                                                                           	at and

**Comment by lipangit** [comment]
Is demo run on that device ok? Did you change the code in library?

**Comment by lipangit** [comment]
https://github.com/lipangit/JiaoZiVideoPlayer/pull/1140 try this code
