### ISSUE TITLE
how to measure the height of the video correctly?

### ISSUE THREAD

**Issue by JoaoArmandoo** [lipangit/JiaoZiVideoPlayer#1392]
First of all, thank you for the library, it's the best I've found.
I would like to know how to fix the size of the video, I do not want it to always have this black background when there is no need, I have several different sizes of video, and not always the height is equal to 250dp or more is the correct thing to do , I imagine I should not have been the only one with this problem, I'm a beginner in programming, so any help will be welcome if someone can share a code that does this, so I can enjoy it and improve my way if required. thank you!

**Comment by lipangit** [comment]
You can see ActivityApiRotationVideoSize in demo, It will tell you how to change the video size in textureView.

**Comment by JoaoArmandoo** [comment]
Hi, thanks for the quick response.
I changed it as you mentioned, but I did not have significant results. VideoPlayer now gets smaller than 250 dp, this is my XML:
```
  <cn.jzvd.JZVideoPlayerStandard
                            android:id="@+id/videoPlayerFacebook"
                            android:layout_width="match_parent"
                            android:layout_height="wrap_content"
                            android:visibility="gone" />
```

My Code:
 ```
String proxyUrl = proxy.getProxyUrl ( source );
                        holder.videoPlayer.setVisibility(View.VISIBLE);
                        holder.videoPlayer.setUp(
                                proxyUrl, JZVideoPlayer.SCREEN_WINDOW_NORMAL,
                              "video");
//                        holder.videoPlayer.setVideoImageDisplayType(JZVideoPlayer.VIDEO_IMAGE_DISPLAY_TYPE_FILL_SCROP);

                        holder.videoPlayer.setOnClickListener(new View.OnClickListener() {
                            @Override
                            public void onClick(View view) {
                                holder.videoPlayer.startButton.setVisibility(View.GONE);
                                openVideo(source);
                            }
                        });
                        holder.videoPlayer.fullscreenButton.setOnTouchListener(new View.OnTouchListener() {
                            @Override
                            public boolean onTouch(View view, MotionEvent motionEvent) {
                                if (motionEvent.getActionMasked() == MotionEvent.BUTTON_PRIMARY) {
                                    openVideo(source);
                                }


                                return true;
                            }
                        });
                        holder.videoPlayer.loop = true;
                        holder.videoPlayer.progressBar.setVisibility(View.GONE);
                        holder.videoPlayer.totalTimeTextView.setVisibility(View.GONE);
                        holder.videoPlayer.currentTimeTextView.setVisibility(View.GONE);
                        Picasso.with(mContext).load(full_picture).placeholder(R.drawable.ic_preload_thumb).into(holder.videoPlayer.thumbImageView);
```
note: I'm using displaying in a RecyclerView.
note 2: I already tried the 5 available options in setVideoImageDisplayType ();

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/33270743-048e9c9e-d3c0-11e7-9ccc-f8235810a282.png)

Do you know the video size, you can see ActivityApiUISmallChange in demo, It will tell you how to specify the aspect ratio.

**Comment by JoaoArmandoo** [comment]
Hello, I've been able to solve this problem by removing JZVideoPlayerStandard from my recyclerView, now I'm going to open it in an activity full screen (so it looks better in my case) But I've noticed another problem when loading videos, even with low quality 240p or 480, it takes about 3-4 seconds for the video to load and get started, which is certainly a problem, do you know how to solve it?

**Comment by lipangit** [comment]
Loading slowly depends on the mediaplay , now use android.media.MediaPlayer it is like that.

**Comment by JoaoArmandoo** [comment]
Can you tell me how to make this change?

**Comment by lipangit** [comment]
You can change to IJkplayer

![image](https://user-images.githubusercontent.com/2038071/33381965-6f8d21e6-d55a-11e7-9cb4-61ab695b0994.png)

**Comment by fukemy** [comment]
hello. I can not find the way to change to IJKPlayer. the rtsp link took long time to load.

<img width="834" alt="screen shot 2018-08-18 at 22 36 09" src="https://user-images.githubusercontent.com/8202437/44300816-35721d80-a337-11e8-925a-e8fe37905372.png">

**Comment by fukemy** [comment]
i copy JZMediaijkplayer class and change mediaInterface to ijk. But got crash:

```
08-18 22:42:13.109 19084-19229/com.futurisx.icamera E/AndroidRuntime: FATAL EXCEPTION: JiaoZiVideoPlayer
    Process: com.futurisx.icamera, PID: 19084
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/base.apk", zip file "/data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/split_lib_dependencies_apk.apk", zip file "/data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/split_lib_resources_apk.apk", zip file "/data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/split_lib_slice_0_apk.apk", zip file "/data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/split_lib_slice_1_apk.apk", zip file "/data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/split_lib_slice_2_apk.apk", zip file "/data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/split_lib_slice_3_apk.apk", zip file "/data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/split_lib_slice_4_apk.apk", zip file "/data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/split_lib_slice_5_apk.apk", zip file "/data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/split_lib_slice_6_apk.apk", zip file "/data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/split_lib_slice_7_apk.apk", zip file "/data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/split_lib_slice_8_apk.apk", zip file "/data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/lib/x86, /data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/base.apk!/lib/x86, /data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/split_lib_dependencies_apk.apk!/lib/x86, /data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/split_lib_resources_apk.apk!/lib/x86, /data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/split_lib_slice_0_apk.apk!/lib/x86, /data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/split_lib_slice_1_apk.apk!/lib/x86, /data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/split_lib_slice_2_apk.apk!/lib/x86, /data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/split_lib_slice_3_apk.apk!/lib/x86, /data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/split_lib_slice_4_apk.apk!/lib/x86, /data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/split_lib_slice_5_apk.apk!/lib/x86, /data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/split_lib_slice_6_apk.apk!/lib/x86, /data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/split_lib_slice_7_apk.apk!/lib/x86, /data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/split_lib_slice_8_apk.apk!/lib/x86, /data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/split_lib_slice_9_apk.apk!/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libijkffmpeg.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1657)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:178)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:189)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:230)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:226)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:217)
        at com.futurisx.icamera.Screen.JZMediaIjkplayer.prepare(JZMediaIjkplayer.java:30)
        at cn.jzvd.JZMediaManager$MediaHandler.handleMessage(JZMediaManager.java:147)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

here is my code:

````
08-18 22:42:13.109 19084-19229/com.futurisx.icamera E/AndroidRuntime: FATAL EXCEPTION: JiaoZiVideoPlayer
    Process: com.futurisx.icamera, PID: 19084
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/base.apk", zip file "/data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/split_lib_dependencies_apk.apk", zip file "/data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/split_lib_resources_apk.apk", zip file "/data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/split_lib_slice_0_apk.apk", zip file "/data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/split_lib_slice_1_apk.apk", zip file "/data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/split_lib_slice_2_apk.apk", zip file "/data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/split_lib_slice_3_apk.apk", zip file "/data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/split_lib_slice_4_apk.apk", zip file "/data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/split_lib_slice_5_apk.apk", zip file "/data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/split_lib_slice_6_apk.apk", zip file "/data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/split_lib_slice_7_apk.apk", zip file "/data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/split_lib_slice_8_apk.apk", zip file "/data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/lib/x86, /data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/base.apk!/lib/x86, /data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/split_lib_dependencies_apk.apk!/lib/x86, /data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/split_lib_resources_apk.apk!/lib/x86, /data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/split_lib_slice_0_apk.apk!/lib/x86, /data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/split_lib_slice_1_apk.apk!/lib/x86, /data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/split_lib_slice_2_apk.apk!/lib/x86, /data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/split_lib_slice_3_apk.apk!/lib/x86, /data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/split_lib_slice_4_apk.apk!/lib/x86, /data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/split_lib_slice_5_apk.apk!/lib/x86, /data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/split_lib_slice_6_apk.apk!/lib/x86, /data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/split_lib_slice_7_apk.apk!/lib/x86, /data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/split_lib_slice_8_apk.apk!/lib/x86, /data/app/com.futurisx.icamera-oRJ9PsPjqyf5hBgHNrpxlA==/split_lib_slice_9_apk.apk!/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libijkffmpeg.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1657)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:178)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:189)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:230)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:226)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:217)
        at com.futurisx.icamera.Screen.JZMediaIjkplayer.prepare(JZMediaIjkplayer.java:30)
        at cn.jzvd.JZMediaManager$MediaHandler.handleMessage(JZMediaManager.java:147)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```
