### ISSUE TITLE
播放设置了播放窗口全屏,开始播放后,点返回键,回到了竖屏播放,并且播放停止,点击播放按钮界面出错

### ISSUE THREAD

**Issue by wodx521** [lipangit/JiaoZiVideoPlayer#1393]
播放设置屏幕属性JZVideoPlayerStandard.SCREEN_WINDOW_FULLSCREEN,点击开始播放视频后,点击返回按钮,视频变为竖屏,并停止播放了,点击播放按钮的话,界面报错退出了,希望改进

**Comment by lipangit** [comment]
log是什么？setUp函数你是怎么写的？需要更多信息

**Comment by wodx521** [comment]
jcplayer.setUp("http://myweike.oss-cn-beijing.aliyuncs.com/Upload/weike/初三/物理/复习课/热学复习指南（曾波）.mp4"
               ,JZVideoPlayerStandard.SCREEN_WINDOW_FULLSCREEN, "热学复习指南");
这是设置,在AndroidManifest.xml中配置信息为
<activity
            android:name=".activity.WeiKeContentActivity"
            android:configChanges="orientation|keyboardHidden|screenSize"
            android:screenOrientation="landscape"/>
运行后报错结果
FATAL EXCEPTION: main
                                                                    Process: com.wew100.student, PID: 30173
                                                                    java.lang.IllegalStateException
                                                                        at android.media.MediaPlayer._pause(Native Method)
                                                                        at android.media.MediaPlayer.pause(MediaPlayer.java:1257)
                                                                        at cn.jzvd.JZVideoPlayer.onClick(JZVideoPlayer.java:392)
                                                                        at cn.jzvd.JZVideoPlayerStandard.onClick(JZVideoPlayerStandard.java:262)
                                                                        at android.view.View.performClick(View.java:5647)
                                                                        at android.view.View$PerformClick.run(View.java:22462)
                                                                        at android.os.Handler.handleCallback(Handler.java:754)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:163)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6276)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:788)

我想尝试使用ijkplayer,因此下载了demo,把videoplayer的moudle依赖到了自己项目中,我修改的就是moudle中一些类view转viewgroup的强转,一些控件的findviewbyid的强转,还是上面的代码,运行并没有出现描述的问题,我看咱使用的studio版本可能是3.0,在build.gradle中一些配置和我使用的studio2.2.3版本的有所不同,经过修改后可以正常运行了,不会出现我说的那种情况

**Comment by wodx521** [comment]
@lipangit 因为添加依赖的关系是直接引入的jar包,打包好的jar包中一些类控件没有强转,可能在高版本的studio中不提示错误,但在低版本中提示错误,或许因为这些问题引起的我之前描述的问题,
如在JZVideoPlayerStandard类中
'''batteryTimeLayout = findViewById(R.id.battery_time_layout);
        bottomProgressBar = findViewById(R.id.bottom_progress);
        titleTextView = findViewById(R.id.title);
        backButton = findViewById(R.id.back);
上面的控件没有强转,在我导入了demo,并修改了上面的错误后,问题也就解决了

**Comment by lipangit** [comment]
解决了好
