### ISSUE TITLE
没有初始化  JZVideoPlayerStandard 调用 releaseAllVideos() 空指针

### ISSUE THREAD

**Issue by chapliny** [lipangit/JiaoZiVideoPlayer#1410]
用的版本是 6.2.0_preview
`FATAL EXCEPTION: JiaoZiVideoPlayer
                                                                    java.lang.NullPointerException
                                                                        at cn.jzvd.JZMediaManager$MediaHandler.handleMessage(JZMediaManager.java:151)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                        at android.os.Looper.loop(Looper.java:177)
                                                                        at android.os.HandlerThread.run(HandlerThread.java:61)`

**Comment by lipangit** [comment]
能复现吗 哪个变量是null demo有这问题吗

**Comment by zhangshaobo87** [comment]
我集成最新版 也是这个问题 而且那个私有的广播 报错没有反注册

**Comment by lipangit** [comment]
保持关注，旧版本有这问题吗

**Comment by zhangshaobo87** [comment]
@lipangit JZMediaManager中的 
![image](https://user-images.githubusercontent.com/17812840/33513306-ef010560-d77a-11e7-9683-62b16beabaa3.png)

**Comment by lipangit** [comment]
继续断点哪里发出的这个消息

**Comment by chapliny** [comment]
@lipangit  嗯 demo 中也一样

**Comment by lipangit** [comment]
用新版，这个问题已经解决了

出现问题是不是因为视频还没播放，退出界面，jzMediaInterface还是空，就会报错

**Comment by chapliny** [comment]
@lipangit  是的
