### ISSUE TITLE
Integer cannot be cast to Long

### ISSUE THREAD

**Issue by mastergyp** [lipangit/JiaoZiVideoPlayer#1418]
12-04 17:31:42.636 28898-28898/com.vapeam.vp E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: com.vapeam.vp, PID: 28898
                                                               java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
                                                                   at android.app.SharedPreferencesImpl.getLong(SharedPreferencesImpl.java:249)
                                                                   at cn.jzvd.JZUtils.getSavedProgress(JZUtils.java:131)
                                                                   at cn.jzvd.JZVideoPlayer.onStatePrepared(JZVideoPlayer.java:673)
                                                                   at cn.jzvd.JZVideoPlayer.onPrepared(JZVideoPlayer.java:613)
                                                                   at cn.jzvd.JZMediaSystem$6.run(JZMediaSystem.java:159)
                                                                   at android.os.Handler.handleCallback(Handler.java:751)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6646)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

**Comment by lipangit** [comment]
清一下保存的进度，新版换成long了，旧版本保存的进度是int

**Comment by lipangit** [comment]
忘了改了 这个版本。。现在修改

**Comment by lipangit** [comment]
fixed on fb63e013a957507ebfb6cd14a8a9f3ccf4e40b26
