### ISSUE TITLE
有个空指针

### ISSUE THREAD

**Issue by ZhenMrLee** [lipangit/JiaoZiVideoPlayer#1424]
java.lang.NullPointerException: Attempt to invoke virtual method 'void cn.jzvd.JZMediaInterface.release()' on a null object reference

at cn.jzvd.JZMediaManager$MediaHandler.handleMessage(JZMediaManager.java:151)

at android.os.Handler.dispatchMessage(Handler.java:111)

at android.os.Looper.loop(Looper.java:210)

at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by ZhenMrLee** [comment]
@lipangit  急急急，产品线上得问题

**Comment by lipangit** [comment]
已经解决，请更新版本

**Comment by ZhenMrLee** [comment]
新版本什么

**Comment by lipangit** [comment]
6.2.1

**Comment by ZhenMrLee** [comment]
还是不行，6.2.1还是有

**Comment by lipangit** [comment]
试试6.2.3，这个interface是单例的，并且不会为空
