### ISSUE TITLE
somtimes the video load slowly 

### ISSUE THREAD

**Issue by medmedchiheb** [lipangit/JiaoZiVideoPlayer#1455]
i have try this library it's awesome, i like it.
first i worked in my localhost and everything is good but when i change to my server the video load slowly 
and it's not internet connection or something i think it's from this library i wish you fix this problem 
good continuation

**Comment by lipangit** [comment]
Loading speed depends on the video engine, video engines are android.media.MediaPlayer or ijkplayer or exoplayer, you can change it in one line code.

**Comment by medmedchiheb** [comment]
can you give me an example

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/34048532-0a9d6132-e1ef-11e7-942d-8a2a3f88e7ef.png)

**Comment by medmedchiheb** [comment]
thank you

**Comment by medmedchiheb** [comment]
i get this Error when i change the Media Interface to JZMediaIjkplayer


```
FATAL EXCEPTION: JiaoZiVideoPlayer
                                                                                  Process: etcadire.com.tn.octadev.etcadire, PID: 18110
                                                                                  java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/etcadire.com.tn.octadev.etcadire-1/base.apk", zip file "/data/app/etcadire.com.tn.octadev.etcadire-1/split_lib_dependencies_apk.apk", zip file "/data/app/etcadire.com.tn.octadev.etcadire-1/split_lib_slice_0_apk.apk", zip file "/data/app/etcadire.com.tn.octadev.etcadire-1/split_lib_slice_1_apk.apk", zip file "/data/app/etcadire.com.tn.octadev.etcadire-1/split_lib_slice_2_apk.apk", zip file "/data/app/etcadire.com.tn.octadev.etcadire-1/split_lib_slice_3_apk.apk", zip file "/data/app/etcadire.com.tn.octadev.etcadire-1/split_lib_slice_4_apk.apk", zip file "/data/app/etcadire.com.tn.octadev.etcadire-1/split_lib_slice_5_apk.apk", zip file "/data/app/etcadire.com.tn.octadev.etcadire-1/split_lib_slice_6_apk.apk", zip file "/data/app/etcadire.com.tn.octadev.etcadire-1/split_lib_slice_7_apk.apk", zip file "/data/app/etcadire.com.tn.octadev.etcadire-1/split_lib_slice_8_apk.apk", zip file "/data/app/etcadire.com.tn.octadev.etcadire-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/etcadire.com.tn.octadev.etcadire-1/lib/arm64, /data/app/etcadire.com.tn.octadev.etcadire-1/base.apk!/lib/arm64-v8a, /data/app/etcadire.com.tn.octadev.etcadire-1/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/etcadire.com.tn.octadev.etcadire-1/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/etcadire.com.tn.octadev.etcadire-1/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/etcadire.com.tn.octadev.etcadire-1/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/etcadire.com.tn.octadev.etcadire-1/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/etcadire.com.tn.octadev.etcadire-1/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/etcadire.com.tn.octadev.etcadire-1/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/etcadire.com.tn.octadev.etcadire-1/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/etcadire.com.tn.octadev.etcadire-1/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/etcadire.com.tn.octadev.etcadire-1/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/etcadire.com.tn.octadev.etcadire-1/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libijkffmpeg.so"
                                                                                      at java.lang.Runtime.loadLibrary0(Runtime.java:972)
                                                                                      at java.lang.System.loadLibrary(System.java:1567)
                                                                                      at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:178)
                                                                                      at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:189)
                                                                                      at tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:230)
                                                                                      at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:226)
                                                                                      at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:217)
                                                                                      at etcadire.com.tn.octadev.etcadire.controls.JZMediaIjkplayer.prepare(JZMediaIjkplayer.java:33)
                                                                                      at cn.jzvd.JZMediaManager$MediaHandler.handleMessage(JZMediaManager.java:145)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                      at android.os.Looper.loop(Looper.java:154)
                                                                                      at android.os.HandlerThread.run(HandlerThread.java:61)
```

any suggestions

**Comment by lipangit** [comment]
This is the point -> "couldn't find "libijkffmpeg.so"

Did you import ijkplayer in your gradle file? if not solve, You may ask [ijkplayer](https://github.com/Bilibili/ijkplayer)
