### ISSUE TITLE
我换了IJKplayer后全屏会报空指针，求指教

### ISSUE THREAD

**Issue by m5314** [lipangit/JiaoZiVideoPlayer#1456]
java.lang.NullPointerException
                                                                at cn.jzvd.demo.CustomMediaPlayer.JZMediaIjkplayer.getCurrentPosition(JZMediaIjkplayer.java:82)
                                                                at cn.jzvd.JZMediaManager.getCurrentPosition(JZMediaManager.java:70)
                                                                at cn.jzvd.JZVideoPlayer.getCurrentPositionWhenPlaying(JZVideoPlayer.java:904)
                                                                at cn.jzvd.JZVideoPlayer$ProgressTimerTask$1.run(JZVideoPlayer.java:1147)

这种报错，换回mediaplayer后正常，怎么办。。

**Comment by lipangit** [comment]
哪个变量是空？，是最新版本吗

**Comment by m5314** [comment]
是我错了0-0，找到原因了，我调了多次setMediaInterface方法导致的，已解决
