### ISSUE TITLE
java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by marscl** [lipangit/JiaoZiVideoPlayer#1463]
java.lang.IllegalArgumentException: surfaceTexture must not be null
	at android.view.Surface.<init>(Surface.java:140)
	at cn.jzvd.JZMediaManager$MediaHandler.handleMessage(JZMediaManager.java)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:200)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by lipangit** [comment]
什么版本，怎么操作出现的这个错误，能复现吗

**Comment by marscl** [comment]
6.2.0 没法复现

**Comment by marscl** [comment]
可以添加个ExoPlayer的demo吗

**Comment by lipangit** [comment]
你可以参照JZIJKPlayer写一个exoplayer的，咱们这个库也需要大家的参数
