### ISSUE TITLE
电池广播取消问题

### ISSUE THREAD

**Issue by techGay** [lipangit/JiaoZiVideoPlayer#1515]
java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.BATTERY_CHANGED flg=0x60000010 (has extras) } in cn.jzvd.JZVideoPlayerStandard$1@1b134884
        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:926)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5574)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:962)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
Caused by: java.lang.IllegalArgumentException: Receiver not registered: cn.jzvd.JZVideoPlayerStandard$1@1b134884
        at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:791)
        at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1728)
        at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:511)
        at cn.jzvd.JZVideoPlayerStandard$1.onReceive(JZVideoPlayerStandard.java:91)
        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:914)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5574)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:962)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)

很奇怪，这是后台捕抓到的日志，但是这个并不是报在播放界面，而是列表界面（列表仅用于展示数据，并没有其他的东西，即是点击之后跳转播放的视频），貌似是退出播放的时候极小几率没有取消注册的广播。

捕抓到系统信息：

Meizu
model PRO 5
networkAccess   wifi
orientation    portrait
osBuild   Flyme 6.7.4.12 daily
osName   android
osVersion  5.1
screenDensity  3
screenResolution  1920x1080
totalMemory   268435456

**Comment by lipangit** [comment]
每次去的电量之后马上就会注销广播，难道要不判断if 直接注销吗

持续关注这个问题

**Comment by techGay** [comment]
到目前为止就只有这一个用户发现了这个问题，发生了6次，暂时没发现其他用户和机型会出现。后序如果有更多用户或者其他有用的信息再来反馈

**Comment by lipangit** [comment]
问题是集中出现还是，一直偶尔会有

**Comment by techGay** [comment]
没有集中出现，到目前出现的次数非常少，已经有几天没出现过了，应该是极其小的概率发生，或者非常特定的条件下
