### ISSUE TITLE
NullPointerException when rotating video to landscape on full screen

### ISSUE THREAD

**Issue by Monster-king** [lipangit/JiaoZiVideoPlayer#1529]
I'm getting nullpointerException when rotating screen to landscape on fullscreen mode. I'm using your library in recyclerview and in my recyclerview many types of items such photo music and video. 
If I remove from recyclerview override method onChildViewDetachedFromWindow error does not occurring. In onChildViewDetachedFromWindow method I've write next:

```
@Override
            public void onChildViewDetachedFromWindow(View view) {
                JZVideoPlayerStandard video = view.findViewById(R.id.videoview);
                if (video != null &&
                        JZUtils.dataSourceObjectsContainsUri(video.dataSourceObjects,
                                JZMediaManager.getCurrentDataSource())) {
                    JZVideoPlayer.releaseAllVideos();
                }
            }
```

And error log looks like:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference
                                                                   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:275)
                                                                   at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                   at android.view.View.layout(View.java:18874)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5954)
                                                                   at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                   at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                   at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                   at android.view.View.layout(View.java:18874)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5954)
                                                                   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                   at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                   at android.view.View.layout(View.java:18874)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5954)
                                                                   at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                   at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                   at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                   at android.view.View.layout(View.java:18874)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5954)
                                                                   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                   at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                   at com.android.internal.policy.DecorView.onLayout(DecorView.java:910)
                                                                   at android.view.View.layout(View.java:18874)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5954)
                                                                   at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2697)
                                                                   at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2413)
                                                                   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1550)
                                                                   at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7190)
                                                                   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:959)
                                                                   at android.view.Choreographer.doCallbacks(Choreographer.java:734)
                                                                   at android.view.Choreographer.doFrame(Choreographer.java:670)
                                                                   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:945)
                                                                   at android.os.Handler.handleCallback(Handler.java:751)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
```

**Comment by lipangit** [comment]
what version? Does it occur in demo

**Comment by Monster-king** [comment]
I download your library like module and use it. Last commit was orientation demo. I can't reproduce this bug in demo app. Because it appears hardly ever. How do you think, where it can be error?

**Comment by lipangit** [comment]
You can simplify your code and push to github, I will download and test your code.

**Comment by vzhilong** [comment]
结果怎么样了？
