### ISSUE TITLE
SurfaceTexture must not be null

### ISSUE THREAD

**Issue by kimnamcham** [lipangit/JiaoZiVideoPlayer#1552]
I use in recycleview, sometime is crash. This is log:

/AndroidRuntime: FATAL EXCEPTION: JiaoZiVideoPlayer
                                                                        PID: 12404
                                                                        java.lang.IllegalArgumentException: surfaceTexture must not be null
                                                                            at android.view.Surface.<init>(Surface.java:140)
                                                                            at cn.jzvd.JZMediaManager$MediaHandler.handleMessage(JZMediaManager.java:149)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:153)
                                                                            at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by lipangit** [comment]
try new version, fix a bug about this log , maybe fix your problem

**Comment by kimnamcham** [comment]
Thanks, i will try it

**Comment by lipangit** [comment]
How is it going
