### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by chenpdsu** [lipangit/JiaoZiVideoPlayer#1577]
java.lang.NullPointerException: Attempt to read from field 'int android.view.View.mViewFlags' on a null object reference
                                                                            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3584)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:15171)
                                                                            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3605)
                                                                            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3585)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:15171)
                                                                            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3605)
                                                                            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3585)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:15171)
                                                                            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3605)
                                                                            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3585)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:15171)
                                                                            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3605)
                                                                            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3585)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:15171)
                                                                            at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:296)
                                                                            at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:302)
                                                                            at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:337)
                                                                            at android.view.ViewRootImpl.draw(ViewRootImpl.java:2874)
                                                                            at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2690)
                                                                            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2319)
                                                                            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1331)
                                                                            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6607)
                                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                            at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                            at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                            at android.os.Handler.handleCallback(Handler.java:739)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5547)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:935)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:726)

**Comment by lipangit** [comment]
什么时候，是列表的最后一个item全屏的时候崩溃吗

**Comment by lipangit** [comment]
最后一个item全屏的时候崩溃，已经修复，忘了什么时候
