### ISSUE TITLE
华为H30-U10手机点击全屏闪退

### ISSUE THREAD

**Issue by zhuminjunivan** [lipangit/JiaoZiVideoPlayer#1583]
` E/CrashHandler: In thread: Thread[main,5,main]
                                                             UncaughtException detected: java.lang.RuntimeException: Error during detachFromGLContext (see logcat for details)
                                                                 at android.graphics.SurfaceTexture.attachToGLContext(SurfaceTexture.java:237)
                                                                 at android.view.GLES20TextureLayer.setSurfaceTexture(GLES20TextureLayer.java:81)
                                                                 at android.view.HardwareRenderer$Gl20Renderer.setSurfaceTexture(HardwareRenderer.java:1576)
                                                                 at android.view.TextureView.getHardwareLayer(TextureView.java:393)
                                                                 at android.view.View.getDisplayList(View.java:12809)
                                                                 at android.view.View.getDisplayList(View.java:12890)
                                                                 at android.view.View.draw(View.java:13640)
                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3050)
                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2912)
                                                                 at android.view.View.getDisplayList(View.java:12841)
                                                                 at android.view.View.getDisplayList(View.java:12890)
                                                                 at android.view.View.draw(View.java:13640)
                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3050)
                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2912)
                                                                 at android.view.View.draw(View.java:13947)
                                                                 at android.view.View.getDisplayList(View.java:12846)
                                                                 at android.view.View.getDisplayList(View.java:12890)
                                                                 at android.view.View.draw(View.java:13640)
                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3050)
                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2912)
                                                                 at android.view.View.getDisplayList(View.java:12841)
                                                                 at android.view.View.getDisplayList(View.java:12890)
                                                                 at android.view.View.draw(View.java:13640)
                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3050)
                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2912)
                                                                 at android.view.View.draw(View.java:13947)
                                                                 at android.widget.FrameLayout.draw(FrameLayout.java:467)
                                                                 at android.view.View.getDisplayList(View.java:12846)
                                                                 at android.view.View.getDisplayList(View.java:12890)
                                                                 at android.view.View.draw(View.java:13640)
                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3050)
                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2912)
                                                                 at android.view.View.getDisplayList(View.java:12841)
                                                                 at android.view.View.getDisplayList(View.java:12890)
                                                                 at android.view.View.draw(View.java:13640)
                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3050)
                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2912)
                                                                 at android.view.View.getDisplayList(View.java:12841)
                                                                 at android.view.View.getDisplayList(View.java:12890)
                                                                 at android.view.View.draw(View.java:13640)
                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3050)
                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2912)
                                                                 at android.view.View.getDisplayList(View.java:12841)
                                                                 at android.view.View.getDisplayList(View.java:12890)
                                                                 at android.view.View.draw(View.java:13640)
                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3050)
                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2912)
                                                                 at android.view.View.draw(View.java:13947)
                                                                 at android.widget.FrameLayout.draw(FrameLayout.java:467)
                                                                 at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2247)
                                                                 at android.view.View.getDisplayList(View.java:12846)
                                                                 at android.view.View.getDisplayList(View.java:12890)
                                                                 at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1249)
                                                                 at android.view.ViewRootImpl.draw(ViewRootImpl.java:2572)
                                                                 at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2439)
                                                                 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2241)
                                                                 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1216)
                                                                 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5044)
                                                                 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:776)
                                                                 at android.view.Choreographer.doCallbacks(Choreographer.java:579)
                                                                 at android.view.Choreographer.doFrame(Choreographer.java:548)
                                                                 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:762)
                                                                 at android.os.Handler.handleCallback(Handler.java:800)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                 at android.os.Looper.loop(Looper.java:194)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5433)
                                                                 at java.lang.reflect.Method.invokeNative(Native Method)`
系统版本4.2.2 项目版本 6.2.7

**Comment by lipangit** [comment]
改库了吗，demo有这个问题吗

**Comment by zhuminjunivan** [comment]
demo也有这个问题 只是简单的用示例代码写了一下 还没深入

**Comment by lipangit** [comment]
https://github.com/lipangit/JiaoZiVideoPlayer/pull/1140  这个应该可以解决，但是这个安卓版本太老了，已经放弃了
