### ISSUE TITLE
播放结束直接报错，请问啥原因

### ISSUE THREAD

**Issue by linfeizheng** [lipangit/JiaoZiVideoPlayer#1602]
java.lang.RuntimeException: Error during attachToGLContext (see logcat for details)
    at android.graphics.SurfaceTexture.attachToGLContext(SurfaceTexture.java:215)
    at android.view.GLES20TextureLayer.setSurfaceTexture(GLES20TextureLayer.java:86)
    at android.view.HardwareRenderer$Gl20Renderer.setSurfaceTexture(HardwareRenderer.java:2221)
    at android.view.TextureView.getHardwareLayer(TextureView.java:401)
    at android.view.View.getDisplayList(View.java:13328)
    at android.view.View.getDisplayList(View.java:13404)
    at android.view.View.draw(View.java:14182)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
    at android.view.View.getDisplayList(View.java:13357)
    at android.view.View.getDisplayList(View.java:13404)
    at android.view.View.draw(View.java:14182)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
    at android.view.View.draw(View.java:14468)
    at android.view.View.getDisplayList(View.java:13362)
    at android.view.View.getDisplayList(View.java:13404)
    at android.view.View.draw(View.java:14182)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
    at android.view.View.getDisplayList(View.java:13357)
    at android.view.View.getDisplayList(View.java:13404)
    at android.view.View.draw(View.java:14182)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
    at android.view.View.getDisplayList(View.java:13357)
    at android.view.View.getDisplayList(View.java:13404)
    at android.view.View.draw(View.java:14182)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
    at android.view.View.draw(View.java:14468)
    at android.view.View.getDisplayList(View.java:13362)
    at android.view.View.getDisplayList(View.java:13404)
    at android.view.View.draw(View.java:14182)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
    at android.view.View.draw(View.java:14468)
    at android.widget.FrameLayout.draw(FrameLayout.java:472)
    at android.view.View.getDisplayList(View.java:13362)
    at android.view.View.getDisplayList(View.java:13404)
    at android.view.View.draw(View.java:14182)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
    at android.view.View.getDisplayList(View.java:13357)
    at android.view.View.getDisplayList(View.java:13404)
    at android.view.View.draw(View.java:14182)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
    at android.view.View.getDisplayList(View.java:13357)
    at android.view.View.getDisplayList(View.java:13404)
    at android.view.View.draw(View.java:14182)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
    at android.view.View.getDisplayList(View.java:13357)
    at android.view.View.getDisplayList(View.java:13404)
    at android.view.View.draw(View.java:14182)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
    at android.view.View.draw(View.java:14468)
    at android.widget.FrameLayout.draw(FrameLayout.java:472)
    at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2326)
    at android.view.View.getDisplayList(View.java:13362)
    at android.view.View.getDisplayList(View.java:13404)
    at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1570)
    at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1449)
    at android.view.ViewRootImpl.draw(ViewRootImpl.java:2377)
    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2249)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1879)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)

**Comment by lipangit** [comment]
饺子什么版本，安卓什么版本，什么手机，改库了吗

**Comment by linfeizheng** [comment]
刚download下来的，nexus5，4.4.4，改了一点，能把demo发你看下吗，issue说不清楚

**Comment by lipangit** [comment]
可以

**Comment by linfeizheng** [comment]
邮箱多少请问

**Comment by lipangit** [comment]
进群就号了，群里很多热心肠的人
