### ISSUE TITLE
能否提供库文件呢？

### ISSUE THREAD

**Issue by kulong51** [lipangit/JiaoZiVideoPlayer#1613]
java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.an.gji-1/lib/arm/libijksdl.so"
                                                                      at java.lang.Runtime.loadLibrary(Runtime.java:371)
                                                                      at java.lang.System.loadLibrary(System.java:988)
                                                                      at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:178)
                                                                      at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:190)
                                                                      at tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:230)
                                                                      at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:226)
                                                                      at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:0)
                                                                      at com.anding.issue.common.CustomMediaPlayer.JZMediaIjkplayer.prepare(JZMediaIjkplayer.java:30)
                                                                      at cn.jzvd.JZMediaManager$MediaHandler.handleMessage(JZMediaManager.java:146)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:134)
                                                                      at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by lipangit** [comment]
gradle引用会自动下载的

**Comment by kulong51** [comment]
使用以下方式集成还是提示 java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.an.gji-1/lib/arm/libijksdl.so"

 implementation 'cn.jzvd:jiaozivideoplayer:6.2.7'
    implementation 'tv.danmaku.ijk.media:ijkplayer-java:0.8.4'
    implementation 'tv.danmaku.ijk.media:ijkplayer-armv7a:0.8.4'
    implementation 'tv.danmaku.ijk.media:ijkplayer-armv5:0.8.4'
    implementation 'tv.danmaku.ijk.media:ijkplayer-x86:0.8.4'
    implementation 'tv.danmaku.ijk.media:ijkplayer-exo:0.8.4'

    implementation 'com.danikula:videocache:2.7.0'

**Comment by kulong51** [comment]
找到原因了混淆导致的问题，发现一些新问题：1 播放m3u8 格式视频直播流过程中，滑动时间进度条后将无法播放。 2播放m3u8 格式广播直播流时已经正常播放，加载进度条一直加载种。

**Comment by lipangit** [comment]
超出老臣解决范围，可以到ijkplayer项目中提问

**Comment by kulong51** [comment]
好的， 非常感谢哈 ！
