### ISSUE TITLE
RecycleView最后一个全屏之后转为横屏直接崩溃

### ISSUE THREAD

**Issue by scar1et** [lipangit/JiaoZiVideoPlayer#1629]
播放引擎：系统播放器
机型与系统：三星 GT-I9500（4.4.2）| 魅族 M1 Note（5.1）
错误日志：
02-09 14:50:57.887 8489-8959/cn.jzvd.demo E/BufferQueue: [unnamed-8489-0] queueBuffer: BufferQueue has been abandoned!
02-09 14:50:57.902 8489-8501/cn.jzvd.demo E/BufferQueue: [unnamed-8489-0] query: BufferQueue has been abandoned!
02-09 14:50:57.907 8489-8500/cn.jzvd.demo E/BufferQueue: [unnamed-8489-0] dequeueBuffer: BufferQueue has been abandoned!
02-09 14:50:57.907 8489-8489/cn.jzvd.demo E/AndroidRuntime: FATAL EXCEPTION: main
                                                            Process: cn.jzvd.demo, PID: 8489
                                                            java.lang.NullPointerException
                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:405)
                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                at android.view.View.layout(View.java:15656)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:4857)
                                                                at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:443)
                                                                at android.view.View.layout(View.java:15656)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:4857)
                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                at android.view.View.layout(View.java:15656)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:4857)
                                                                at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
                                                                at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
                                                                at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
                                                                at android.view.View.layout(View.java:15656)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:4857)
                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                at android.view.View.layout(View.java:15656)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:4857)
                                                                at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2288)
                                                                at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2008)
                                                                at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1238)
                                                                at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6473)
                                                                at android.view.Choreographer$CallbackRecord.run(Choreographer.java:803)
                                                                at android.view.Choreographer.doCallbacks(Choreographer.java:603)
                                                                at android.view.Choreographer.doFrame(Choreographer.java:573)
                                                                at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:789)
                                                                at android.os.Handler.handleCallback(Handler.java:733)
                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                at android.os.Looper.loop(Looper.java:157)
                                                                at android.app.ActivityThread.main(ActivityThread.java:5387)
                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                at java.lang.reflect.Method.invoke(Method.java:515)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
                                                                at dalvik.system.NativeStart.main(Native Method)

**Comment by lipangit** [comment]
是的，正在解决，有什么线索吗

**Comment by scar1et** [comment]
@lipangit 我是在测试新demo的时候发现的，没有深入研究，看log估计是转屏是丢了啥属性导致的空指针。

**Comment by lipangit** [comment]
NullPointerException 没看到这个log，华为nova 2s，确实闪退了，有问题，但是没有相关的log

**Comment by lipangit** [comment]
这是个问题，可能有点复杂

**Comment by scar1et** [comment]
@lipangit 直接adb logcat  然后操作崩溃，然后搜索fatal

**Comment by scar1et** [comment]
在转屏时调用“android.view.View.getVisibility()”，然后出现了空指针，但是具体位置没找到

**Comment by lipangit** [comment]
en 一起研究

**Comment by lipangit** [comment]
是不是有地方调用了mediaplayer.release()，

**Comment by scar1et** [comment]
我打断点没进mediaplayer.release()

**Comment by scar1et** [comment]
崩溃之前进了
JZMediaSystem.release()

**Comment by scar1et** [comment]
这是不是说明导致崩溃的点不是在一个线程与调用JZMediaSystem.release()是不在一个线程里面的

**Comment by lipangit** [comment]
好的，一会起来调试调试

**Comment by Monster-king** [comment]
I have the same issue.

**Comment by lipangit** [comment]
这个问题已经解决，在最近的commit上，周日发版

**Comment by minitriangle** [comment]
@lipangit 幸苦了

**Comment by minitriangle** [comment]
@lipangit compile 获取不到最新的修改

**Comment by MuchenXmy** [comment]
> 这个问题已经解决，在最近的commit上，周日发版

这个怎么解决的啊，可以贴下代码吗

**Comment by lipangit** [comment]
用新版



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月31日(周六) 中午11:52
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [lipangit/JiaoZiVideoPlayer] RecycleView最后一个全屏之后转为横屏直接崩溃 (#1629)




  
这个问题已经解决，在最近的commit上，周日发版
  
这个怎么解决的啊，可以贴下代码吗
