### ISSUE TITLE
I'm getting this excetion

### ISSUE THREAD

**Issue by ismailtosun** [lipangit/JiaoZiVideoPlayer#1657]
hi,I'm using tab layout and in this tab layout there are 3 fragment.
in this fragment i have a recycler view. and i am getting this exeption

[FATAL EXCEPTION: main
                  Process: com.example.developerfyk.winnerinno, PID: 3637
                  java.lang.NullPointerException: Attempt to read from field 'int cn.jzvd.JZVideoPlayer.currentScreen' on a null object reference
                      at com.example.developerfyk.winnerinno.Activity.Fragment.Join.JoinFragment$2.onChildViewDetachedFromWindow(JoinFragment.java:117)
                      at android.support.v7.widget.RecyclerView.dispatchChildDetached(RecyclerView.java:6978)
                      at android.support.v7.widget.RecyclerView$5.removeViewAt(RecyclerView.java:770)
                      at android.support.v7.widget.ChildHelper.removeViewAt(ChildHelper.java:168)
                      at android.support.v7.widget.RecyclerView$LayoutManager.removeViewAt(RecyclerView.java:8067)
                      at android.support.v7.widget.RecyclerView$LayoutManager.removeAndRecycleViewAt(RecyclerView.java:8339)
                      at android.support.v7.widget.LinearLayoutManager.recycleChildren(LinearLayoutManager.java:1370)
                      at android.support.v7.widget.LinearLayoutManager.recycleViewsFromStart(LinearLayoutManager.java:1416)
                      at android.support.v7.widget.LinearLayoutManager.recycleByLayoutState(LinearLayoutManager.java:1485)
                      at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1509)
                      at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1332)
                      at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1076)
                      at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1790)
                      at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2996)
                      at android.view.View.dispatchTouchEvent(View.java:10936)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2836)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2512)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2842)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2527)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2842)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2527)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2842)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2527)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2842)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2527)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2842)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2527)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2842)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2527)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2842)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2527)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2842)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2527)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2842)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2527)
                      at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:623)
                      at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1909)
                      at android.app.Activity.dispatchTouchEvent(Activity.java:3247)
                      at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
                      at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
                      at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:585)
                      at android.view.View.dispatchPointerEvent(View.java:11165)
                      at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5227)
                      at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5076)
                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4580)
                      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4633)
E/AndroidRuntime:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4599)
                      at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4736)
                      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4607)
                      at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4793)
                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4580)
                      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4633)
                      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4599)
                      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4607)
                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4580)
                      at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7210)
                      at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7142)
                      at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7103)
                      at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7321)
                      at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                      at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
                      at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
                      at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7284)
                      at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7348)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:930)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:705)
                      at android.view.Choreographer.doFrame(Choreographer.java:634)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:916)
                      at android.os.Handler.handleCallback(Handler.java:751)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6816)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)](url)

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/36934199-f59fe54c-1f20-11e8-94c6-455fff65e885.png)

break point in this method, where call this method in a wrong time
