### ISSUE TITLE
exceptions!!!!!!!

### ISSUE THREAD

**Issue by ismailtosun** [lipangit/JiaoZiVideoPlayer#1669]
FATAL EXCEPTION: main
                  java.lang.RuntimeException: Error during detachFromGLContext (see logcat for details)
                      at android.graphics.SurfaceTexture.attachToGLContext(SurfaceTexture.java:237)
                      at android.view.GLES20TextureLayer.setSurfaceTexture(GLES20TextureLayer.java:81)
                      at android.view.HardwareRenderer$Gl20Renderer.setSurfaceTexture(HardwareRenderer.java:1576)
                      at android.view.TextureView.getHardwareLayer(TextureView.java:393)
                      at android.view.View.getDisplayList(View.java:12795)
                      at android.view.View.getDisplayList(View.java:12876)
                      at android.view.View.draw(View.java:13621)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3037)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2901)
                      at android.view.View.getDisplayList(View.java:12827)
                      at android.view.View.getDisplayList(View.java:12876)
                      at android.view.View.draw(View.java:13621)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3037)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2901)
                      at android.view.View.draw(View.java:13928)
                      at android.view.View.getDisplayList(View.java:12832)
                      at android.view.View.getDisplayList(View.java:12876)
                      at android.view.View.draw(View.java:13621)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3037)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2901)
                      at android.view.View.getDisplayList(View.java:12827)
                      at android.view.View.getDisplayList(View.java:12876)
                      at android.view.View.draw(View.java:13621)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3037)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2901)
                      at android.view.View.draw(View.java:13928)
                      at android.widget.FrameLayout.draw(FrameLayout.java:467)
                      at android.view.View.getDisplayList(View.java:12832)
                      at android.view.View.getDisplayList(View.java:12876)
                      at android.view.View.draw(View.java:13621)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3037)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2901)
                      at android.view.View.getDisplayList(View.java:12827)
                      at android.view.View.getDisplayList(View.java:12876)
                      at android.view.View.draw(View.java:13621)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3037)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2901)
                      at android.view.View.getDisplayList(View.java:12827)
                      at android.view.View.getDisplayList(View.java:12876)
                      at android.view.View.draw(View.java:13621)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3037)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2901)
                      at android.view.View.getDisplayList(View.java:12827)
                      at android.view.View.getDisplayList(View.java:12876)
                      at android.view.View.draw(View.java:13621)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3037)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2901)
                      at android.view.View.draw(View.java:13928)
                      at android.widget.FrameLayout.draw(FrameLayout.java:467)
                      at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2228)
                      at android.view.View.getDisplayList(View.java:12832)
                      at android.view.View.getDisplayList(View.java:12876)
                      at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1249)
                      at android.view.ViewRootImpl.draw(ViewRootImpl.java:2520)
                      at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2387)
                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2189)
                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1181)
                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4942)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:776)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:579)
                      at android.view.Choreographer.doFrame(Choreographer.java:548)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:762)
                      at android.os.Handler.handleCallback(Handler.java:800)
                      at android.os.Handler.dispatchMessage(Handler.java:100)
                      at android.os.Looper.loop(Looper.java:194)
                      at android.app.ActivityThread.main(ActivityThread.java:5370)
                      at java.lang.reflect.Method.invokeNative(Native Method)

**Comment by lipangit** [comment]
does it happend in demo?
