### ISSUE TITLE
NullPointerException 

### ISSUE THREAD

**Issue by SiXuManYan** [lipangit/JiaoZiVideoPlayer#1681]
RecycleView 参照demo中的[ActivityListViewRecyclerView  ](https://github.com/lipangit/JiaoZiVideoPlayer/blob/c7e077de010b232ac878d186562911e19686ae49/app/src/main/java/cn/jzvd/demo/ActivityListViewRecyclerView.java),做一个滑出屏幕回收，用外部类继承的方式写，然后报了一个空指针，
我的RcycleView item，不全都是视频，隔着几个item会有一个视频

相关版本
```xml
compileSdkVersion 25
buildToolsVersion '25.0.3'
minSdkVersion 16
targetSdkVersion 23

compile 'cn.jzvd:jiaozivideoplayer:6.2.8'
```

日志文件如下：

```xml
2018-03-13 11:02:08
App Version: BetaVersion_69
OS Version: 8.0.0_26
Vendor: HMD Global Oy
Model: TA-1000
CPU ABI: armeabi-v7a

java.lang.NullPointerException: Attempt to read from field 'int cn.jzvd.JZVideoPlayer.currentScreen' on a null object reference
	at com.jz.yihua.activity.listener.feed.FeedOnChildAttachStateChangeListener.onChildViewDetachedFromWindow(FeedOnChildAttachStateChangeListener.java:34)
	at android.support.v7.widget.RecyclerView.dispatchChildDetached(RecyclerView.java:6780)
	at android.support.v7.widget.RecyclerView$5.removeViewAt(RecyclerView.java:718)
	at android.support.v7.widget.ChildHelper.removeViewAt(ChildHelper.java:168)
	at android.support.v7.widget.RecyclerView$LayoutManager.removeViewAt(RecyclerView.java:7766)
	at android.support.v7.widget.RecyclerView$LayoutManager.removeAndRecycleViewAt(RecyclerView.java:8038)
	at android.support.v7.widget.LinearLayoutManager.recycleChildren(LinearLayoutManager.java:1355)
	at android.support.v7.widget.LinearLayoutManager.recycleViewsFromEnd(LinearLayoutManager.java:1441)
	at android.support.v7.widget.LinearLayoutManager.recycleByLayoutState(LinearLayoutManager.java:1464)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
	at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1313)
	at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1058)
	at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4680)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:974)
	at android.view.Choreographer.doCallbacks(Choreographer.java:786)
	at android.view.Choreographer.doFrame(Choreographer.java:718)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:960)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6548)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

java 代码
```java
package com.jz.yihua.activity.listener.feed;

import android.support.annotation.IdRes;
import android.support.v7.widget.RecyclerView;
import android.view.View;

import cn.jzvd.JZMediaManager;
import cn.jzvd.JZUtils;
import cn.jzvd.JZVideoPlayer;
import cn.jzvd.JZVideoPlayerManager;

/**
 * Created by Admin on 2018/3/13.
 * 消费圈社区
 * 视频播放滚动回收
 */
public class FeedOnChildAttachStateChangeListener implements RecyclerView.OnChildAttachStateChangeListener {

    private final int jzvideoPlayerResId;

    public FeedOnChildAttachStateChangeListener(@IdRes int jzvideoPlayerResId) {
        this.jzvideoPlayerResId = jzvideoPlayerResId;
    }

    @Override
    public void onChildViewAttachedToWindow(View view) {

    }

    @Override
    public void onChildViewDetachedFromWindow(View view) {
        JZVideoPlayer jzvd = (JZVideoPlayer) view.findViewById(jzvideoPlayerResId);
        if (jzvd != null && JZUtils.dataSourceObjectsContainsUri(jzvd.dataSourceObjects, JZMediaManager.getCurrentDataSource())) {
// 下面这行 JZVideoPlayerManager.getCurrentJzvd().currentScreen报空指针
            if (JZVideoPlayerManager.getCurrentJzvd().currentScreen != JZVideoPlayer.SCREEN_WINDOW_FULLSCREEN) {// 这是第34行
                JZVideoPlayer.releaseAllVideos();
            }
        }


    }
}
```

```java
FeedOnChildAttachStateChangeListener feedOnChildAttachStateChangeListener =
                new FeedOnChildAttachStateChangeListener(R.id.feed_video_player);

recyclerView.addOnChildAttachStateChangeListener(feedOnChildAttachStateChangeListener);
```

**Comment by SiXuManYan** [comment]
see [9843136](https://github.com/lipangit/JiaoZiVideoPlayer/commit/9843136491d10661ffe22377e973ed09376d9d19)

**Comment by LightProspect** [comment]
我也是这部分代码出现的问题但是我断点走的时候在视频划出屏幕外的时候  在走if (jzvd != null && JZUtils.dataSourceObjectsContainsUri(jzvd.dataSourceObjects, JZMediaManager.getCurrentDataSource())) {这个一行代码的时候就奔溃了 这是为什么
