### ISSUE TITLE
UnsatisfiedLinkError In My App But Demo Is Work Correctly

### ISSUE THREAD

**Issue by moeintav** [lipangit/JiaoZiVideoPlayer#1756]
Hi. Thank you for your librery. when I use this line in build.gradle project 

    implementation 'tv.danmaku.ijk.media:ijkplayer-java:0.8.4'
    implementation 'tv.danmaku.ijk.media:ijkplayer-armv7a:0.8.4'

the project sync but app crashes and its crashe is 

 java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/ir.winker.admin-1/base.apk"],nativeLibraryDirectories=[/data/app/ir.winker.admin-1/lib/arm64, /data/app/ir.winker.admin-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/vendor/lib64]]] couldn't find "libijkffmpeg.so"
                                                                   at java.lang.Runtime.loadLibrary0(Runtime.java:972)
                                                                   at java.lang.System.loadLibrary(System.java:1530)
                                                                   at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:179)
                                                                   at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:190)
                                                                   at tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:231)
                                                                   at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:227)
                                                                   at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:218)
                                                                   at ir.winker.admin.chitva_GUI.Video.JZMediaIjkplayer.prepare(JZMediaIjkplayer.java:28)
                                                                   at ir.winker.admin.chitva_GUI.Video.JZMediaManager$MediaHandler.handleMessage(JZMediaManager.java:146)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                   at android.os.Looper.loop(Looper.java:203)
                                                                   at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by moeintav** [comment]
why your demo app is woeking correctly?

**Comment by lipangit** [comment]
I do not know

**Comment by faith-hb** [comment]
再加上其他abi类型的文件包
implementation 'tv.danmaku.ijk.media:ijkplayer-armv5:0.8.8'
    implementation 'tv.danmaku.ijk.media:ijkplayer-arm64:0.8.8'
    implementation 'tv.danmaku.ijk.media:ijkplayer-x86:0.8.8'
    implementation 'tv.danmaku.ijk.media:ijkplayer-x86_64:0.8.8'
