### ISSUE TITLE
IllegalArgumentException

### ISSUE THREAD

**Issue by m5314** [lipangit/JiaoZiVideoPlayer#1776]
java.lang.IllegalArgumentException: The surface has been released
	at android.media.MediaPlayer._setVideoSurface(Native Method)
	at android.media.MediaPlayer.setSurface(MediaPlayer.java:715)
	at cn.jzvd.c.a(SourceFile:103)
	at cn.jzvd.b$a.handleMessage(SourceFile:153)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.os.HandlerThread.run(HandlerThread.java:61)

求解

**Comment by lipangit** [comment]
能再具体说说吗，现在无法定位原因

**Comment by m5314** [comment]
我也是看用户日志发现的报错，我自己也没有重现出来

**Comment by m5314** [comment]
java.lang.IllegalArgumentException: surfaceTexture must not be null
	at android.view.Surface.<init>(Surface.java:186)
	at cn.jzvd.b$a.handleMessage(SourceFile:151)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.os.HandlerThread.run(HandlerThread.java:61)

还有这个问题

**Comment by lipangit** [comment]
是不是判空的地方不对

**Comment by m5314** [comment]
我没改，就是你的源码JZMediaManager

**Comment by lipangit** [comment]
保持关注，你离这个bug最近，你也可以深入研究一下
