### ISSUE TITLE
scrollview中惯性滑动,悬浮窗口关闭时闪退

### ISSUE THREAD

**Issue by wolongalick** [lipangit/JiaoZiVideoPlayer#1801]
如果手一直按住滑动,则没有问题,松手靠惯性滑动,就会闪退

java.lang.NullPointerException: Attempt to read from field 'int android.view.View.mViewFlags' on a null object reference
                                                     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4179)
                                                     at android.view.View.updateDisplayListIfDirty(View.java:18054)
                                                     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4200)
                                                     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4180)
                                                     at android.view.View.updateDisplayListIfDirty(View.java:18054)
                                                     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4200)
                                                     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4180)
                                                     at android.view.View.updateDisplayListIfDirty(View.java:18054)
                                                     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4200)
                                                     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4180)
                                                     at android.view.View.updateDisplayListIfDirty(View.java:18054)
                                                     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4200)
                                                     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4180)
                                                     at android.view.View.updateDisplayListIfDirty(View.java:18054)
                                                     at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:652)
                                                     at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:658)
                                                     at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:766)
                                                     at android.view.ViewRootImpl.draw(ViewRootImpl.java:3027)
                                                     at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2822)
                                                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2375)
                                                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1414)
                                                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6801)
                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1026)
                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:838)
                                                     at android.view.Choreographer.doFrame(Choreographer.java:769)
                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1012)
                                                     at android.os.Handler.handleCallback(Handler.java:789)
                                                     at android.os.Handler.dispatchMessage(Handler.java:98)
                                                     at android.os.Looper.loop(Looper.java:171)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6684)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)

**Comment by lipangit** [comment]
是哪造成的呢，scrollview里嵌套listview了吗
