### ISSUE TITLE
电量变化广播问题

### ISSUE THREAD

**Issue by renchunjian** [lipangit/JiaoZiVideoPlayer#1809]
java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.BATTERY_CHANGED flg=0x60000010 (has extras) } in cn.jzvd.JZVideoPlayerStandard$1@f21d393
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_52497(LoadedApk.java:1323)
	at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.$m$7(Unknown Source:4)
	at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.run(Unknown Source:39)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.IllegalArgumentException: Receiver not registered: cn.jzvd.JZVideoPlayerStandard$1@f21d393
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1193)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1449)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:645)
	at cn.jzvd.JZVideoPlayerStandard$1.onReceive(JZVideoPlayerStandard.java:80)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_52497(LoadedApk.java:1313)
	... 9 more
java.lang.IllegalArgumentException: Receiver not registered: cn.jzvd.JZVideoPlayerStandard$1@f21d393
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1193)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1449)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:645)
	at cn.jzvd.JZVideoPlayerStandard$1.onReceive(JZVideoPlayerStandard.java:80)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_52497(LoadedApk.java:1313)
	at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.$m$7(Unknown Source:4)
	at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.run(Unknown Source:39)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by renchunjian** [comment]
没有复现，可能是注册广播的页面已经destory，但广播没有unregisterReceiver，导致注册广播的context与unregisterReceiver的context不同

**Comment by lipangit** [comment]
保持关注
