### ISSUE TITLE
切换Ijk播放报错

### ISSUE THREAD

**Issue by JayChan95318** [lipangit/JiaoZiVideoPlayer#1814]
ava.lang.UnsatisfiedLinkError: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize__)
                                                             at tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize(Native Method)
                                                             at tv.danmaku.ijk.media.player.IjkMediaPlayer.finalize(IjkMediaPlayer.java:949)
                                                             at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:258)
                                                             at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:245)
                                                             at java.lang.Daemons$Daemon.run(Daemons.java:111)
                                                             at java.lang.Thread.run(Thread.java:764)

TinkerUncaughtHandler catch exception:java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.sharing.app-JirTqXi03KqgA2wzzjpmpQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.sharing.app-JirTqXi03KqgA2wzzjpmpQ==/lib/arm64, /data/app/com.sharing.app-JirTqXi03KqgA2wzzjpmpQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]] couldn't find "libijkffmpeg.so"
                                                                             at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
                                                                             at java.lang.System.loadLibrary(System.java:1657)
                                                                             at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:178)
                                                                             at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:189)
                                                                             at tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:230)
                                                                             at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:226)
                                                                             at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:217)
                                                                             at com.sharing.app.ui.view.JZMediaIjkplayer.prepare(JZMediaIjkplayer.java:30)
                                                                             at cn.jzvd.JZMediaManager$MediaHandler.handleMessage(JZMediaManager.java:146)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                             at android.os.Looper.loop(Looper.java:164)
                                                                             at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by lipangit** [comment]
couldn't find "libijkffmpeg.so"

应该是引入库的问题
