### ISSUE TITLE
在fragment中播放，remove掉fragment时，崩溃了，求大神帮忙看一下

### ISSUE THREAD

**Issue by cs1991** [lipangit/JiaoZiVideoPlayer#1831]
05-05 18:10:02.591 13214-13354/com.iot.xinghe.iot_master W/System.err:     at com.android.okhttp.okio.AsyncTimeout.enter(AsyncTimeout.java:62)
        at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:209)
        at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:50)
        at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:431)
05-05 18:10:02.592 13214-13354/com.iot.xinghe.iot_master W/System.err:     at com.android.okhttp.internal.Util.skipAll(Util.java:159)
        at com.android.okhttp.internal.Util.discard(Util.java:141)
        at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.close(HttpConnection.java:448)
        at com.android.okhttp.okio.RealBufferedSource.close(RealBufferedSource.java:396)
        at com.android.okhttp.okio.RealBufferedSource$1.close(RealBufferedSource.java:384)
        at java.io.BufferedInputStream.close(BufferedInputStream.java:472)
        at android.media.MediaHTTPConnection.teardownConnection(MediaHTTPConnection.java:147)
        at android.media.MediaHTTPConnection.disconnect(MediaHTTPConnection.java:136)
        at android.media.IMediaHTTPConnection$Stub.onTransact(IMediaHTTPConnection.java:61)
        at android.os.Binder.execTransact(Binder.java:574)
        at android.media.MediaPlayer._release(Native Method)
        at android.media.MediaPlayer.release(MediaPlayer.java:1719)
        at cn.jzvd.JZMediaSystem.release(JZMediaSystem.java:74)
        at cn.jzvd.JZMediaManager$MediaHandler.handleMessage(JZMediaManager.java:157)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:203)
        at android.os.HandlerThread.run(HandlerThread.java:61)
05-05 18:10:02.593 13214-13214/com.iot.xinghe.iot_master W/System.err: java.lang.IllegalStateException
        at android.media.MediaPlayer.getDuration(Native Method)
        at cn.jzvd.JZMediaSystem.getDuration(JZMediaSystem.java:89)
05-05 18:10:02.593 13214-13214/com.iot.xinghe.iot_master W/System.err:     at cn.jzvd.JZMediaManager.getDuration(JZMediaManager.java:74)
        at cn.jzvd.JZVideoPlayer.getDuration(JZVideoPlayer.java:923)
        at cn.jzvd.JZVideoPlayer$ProgressTimerTask$1.run(JZVideoPlayer.java:1161)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6406)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)

**Comment by lipangit** [comment]
remove之前releaseAllVideos
