### ISSUE TITLE
Demo运行错误:java.lang.NullPointerException: Attempt to read from field 'int cn.jzvd.JZVideoPlayer.currentScreen' on a null object reference

### ISSUE THREAD

**Issue by zimengfang** [lipangit/JiaoZiVideoPlayer#1841]
java.lang.NullPointerException: Attempt to read from field 'int cn.jzvd.JZVideoPlayer.currentScreen' on a null object reference
 at cn.jzvd.demo.ActivityTinyWindowRecycleViewMultiHolder$1.onChildViewDetachedFromWindow(ActivityTinyWindowRecycleViewMultiHolder.java:60)
 at android.support.v7.widget.RecyclerView.dispatchChildDetached(RecyclerView.java:7152)
 at android.support.v7.widget.RecyclerView$5.removeViewAt(RecyclerView.java:794)
 at android.support.v7.widget.ChildHelper.removeViewAt(ChildHelper.java:168)
 at android.support.v7.widget.RecyclerView$LayoutManager.removeViewAt(RecyclerView.java:8260)
 at android.support.v7.widget.RecyclerView$LayoutManager.removeAndRecycleViewAt(RecyclerView.java:8532)
 at android.support.v7.widget.LinearLayoutManager.recycleChildren(LinearLayoutManager.java:1375)
 at android.support.v7.widget.LinearLayoutManager.recycleViewsFromEnd(LinearLayoutManager.java:1461)
 at android.support.v7.widget.LinearLayoutManager.recycleByLayoutState(LinearLayoutManager.java:1484)
 at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1510)
 at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1333)
 at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1077)
 at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4960)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:873)
 at android.view.Choreographer.doCallbacks(Choreographer.java:685)
 at android.view.Choreographer.doFrame(Choreographer.java:618)
 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:859)
 at android.os.Handler.handleCallback(Handler.java:754)
 at android.os.Handler.dispatchMessage(Handler.java:95)
 at android.os.Looper.loop(Looper.java:163)
 at android.app.ActivityThread.main(ActivityThread.java:6321)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)

**Comment by lipangit** [comment]
试试新版本，记得最近修改过，加了一个判断。 再对比一下新的demo
