### ISSUE TITLE
更换播放引擎以后，我断开网络再开启网络点击重新加载，他会再次走一遍初始化的方法，然后就播放地址就报空

### ISSUE THREAD

**Issue by liu1070832898** [lipangit/JiaoZiVideoPlayer#1851]
java.lang.IllegalStateException: mpjni: setDataSource: null mp
        at tv.danmaku.ijk.media.player.IjkMediaPlayer._setDataSource(Native Method)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.setDataSource(IjkMediaPlayer.java:408)
        at com.example.nacheng.qingli.IjkplayerVideo.JZMediaIjkplayer.prepare(JZMediaIjkplayer.java:56)
        at cn.jzvd.JZMediaManager$MediaHandler.handleMessage(JZMediaManager.java:146)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by lipangit** [comment]
亲测不会，切换ijkplayer，断开网络，链接网络，重新播放，正常。你的能录个小视频看看效果吗

**Comment by liu1070832898** [comment]
我录了小视频发到你邮箱了，我现在只能在JZMediaIjkplayer这里类里面自己写了一个方法把URL值单独传进来,就可以

**Comment by liu1070832898** [comment]
https://pan.baidu.com/s/1K4MarMzyco4-xKSjC8SQbQ    里面是录的一个小视频

**Comment by liu1070832898** [comment]
我找到了问题  你在JZMediaIjkplayer类里面 prepare()下面初始化了IjkMediaPlayer类  但是我又加了判断  如果为空才去初始化 不为空就不初始化

**Comment by lipangit** [comment]
可以，我更新一下

**Comment by reverseAndroid** [comment]
@liu1070832898 你好，请问一下，你切换成JZMediaIjkplayer这个引擎，是不是编译他的 .so库，然后才可以的？

**Comment by lipangit** [comment]
@reverseAndroid 引入库就行了
