### ISSUE TITLE
java.lang.IllegalArgumentException: Receiver not registered: cn.jzvd.JZVideoPlayerStandard$1@ea503b8

### ISSUE THREAD

**Issue by liu1070832898** [lipangit/JiaoZiVideoPlayer#1867]
java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.BATTERY_CHANGED flg=0x60000010 (has extras) } in cn.jzvd.JZVideoPlayerStandard$1@ea503b8
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:974)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:179)
	at android.app.ActivityThread.main(ActivityThread.java:5769)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)
Caused by: java.lang.IllegalArgumentException: Receiver not registered: cn.jzvd.JZVideoPlayerStandard$1@ea503b8
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:821)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1230)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:587)
	at cn.jzvd.JZVideoPlayerStandard$1.onReceive(JZVideoPlayerStandard.java:80)
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:957)
	... 7 more
java.lang.IllegalArgumentException: Receiver not registered: cn.jzvd.JZVideoPlayerStandard$1@ea503b8
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:821)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1230)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:587)
	at cn.jzvd.JZVideoPlayerStandard$1.onReceive(JZVideoPlayerStandard.java:80)
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:957)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:179)
	at android.app.ActivityThread.main(ActivityThread.java:5769)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)

**Comment by lipangit** [comment]
用的什么版本？ 新版不会频繁取得电量，然后这个log是什么现象的，ui上显示的什么

**Comment by liu1070832898** [comment]
我是前天在你github上下载下来的源码的，然后替换源码的，这个log是友盟收集的，我的版本已经发出去了

**Comment by liu1070832898** [comment]
![image](https://user-images.githubusercontent.com/29189440/40162902-e23da8b6-59e7-11e8-832a-feae091472db.png)

**Comment by lipangit** [comment]
保持关注先

**Comment by msrlin** [comment]
我也遇到了这个问题，希望能解决下

**Comment by mhaiyue** [comment]
同遇到这个问题, 次数还不少

**Comment by lipangit** [comment]
已经修复

**Comment by luckybilly** [comment]
今天看到线上也报了这个crash，来github上一看确实存在这个问题（其它issue还有： #1809 #1515 ，但这两个issue都被挂起了）

@lipangit 看到你19天前的回复说是已经修复了，但我并没有找到相关的commit，最新的源码上也没有这方面的修改，可能跟我理解的方式不一样吧。下面说一下我的思路，仅供参考：

看了下日志，再对照源码查了下，感觉问题应该是出在[注销broadcastReceiver](https://github.com/lipangit/JiaoZiVideoPlayer/blob/4cad45dce6ca50b148e7c460a580b77949ebbfac/jiaozivideoplayer/src/main/java/cn/jzvd/JzvdStd.java#L79)上
```
//在老版本上，所在的类名为：JZVideoPlayerStandard 
//6.3版重构后，目前最新代码类名为：JzvdStd
    private BroadcastReceiver battertReceiver = new BroadcastReceiver() {
        public void onReceive(Context context, Intent intent) {
            String action = intent.getAction();
            if (Intent.ACTION_BATTERY_CHANGED.equals(action)) {
                int level = intent.getIntExtra("level", 0);
                int scale = intent.getIntExtra("scale", 100);
                int percent = level * 100 / scale;
                LAST_GET_BATTERYLEVEL_PERCENT = percent;
                setBatteryLevel();
                getContext().unregisterReceiver(battertReceiver);
            }
        }
    };
```

问题原因推测：
`Intent.ACTION_BATTERY_CHANGED`是系统发出的粘性广播，所以我们一开始`registerReceiver`后马上就能收到当前电量信息，get到电量信息后再注销广播接收器，一般情况下没有问题。

但**如果注册receiver到注销receiver期间电量发生了变化导致receiver.onReceive会被执行不止1次，第2次执行`unregisterReceiver`时将会报这个错** 

__PS: 这大概也是线上偶尔crash但数量非常少的原因吧__

我们假设有以下这种情况：
1. 注册广播接收器
2. 获得粘性广播里的值，在`LoadedApk$ReceiverDispatcher.performReceive(...)`方法中将执行`receiver.onReceive(context, intent)`的一个`Runnable`给post到了名为`mActivityThread`的Handler中
3. 在等待这个runnable在主线程中执行期间，设备电量发生变化，再发送了一个系统粘性广播（Intent.ACTION_BATTERY_CHANGED）
4. 再次出发步骤2
5. `receiver.onRecive(context, intent)`方法执行第1次时，调用了`getContext().unregisterReceiver(battertReceiver);`
6. `receiver.onRecive(context, intent)`方法执行第2次时，再次调用`getContext().unregisterReceiver(battertReceiver);`将会报错

修复方式：
1. 作者可以通过在`battertReceiver`中添加成员变量，在onReceive中判断`battertReceiver`是否已注销
2. 简单粗暴一点就是给注销`battertReceiver`的那行代码加上try-catch

在作者修复问题发布新版本之前我们使用者可用的**临时修复方式**：

由于battertReceiver是private的，我们不方便给它赋值（当然反射也是可以的），可以按如下步骤解决：
1. 创建一个JZVideoPlayerStandard的子类
2. 在子类中重新定义一个`BroadcastReceiver`，将`battertReceiver`的代码copy过来改一下
3. 重写`setSystemTimeAndBattery()`方法，这个方法里所用到的变量及方法都是public的，可以直接copy到子类中并用子类中的定义的`BroadcastReceiver`替换原来的`battertReceiver`
4. 在使用到视频播放器的地方使用这个子类代替JZVideoPlayerStandard

最后，非常感谢作者提供这么棒的开源库给我们使用，感恩作者的付出！

以上！

**Comment by lipangit** [comment]
1. LAST_GET_BATTERYLEVEL_PERCENT 之前没有这个变量，每次setup都会取得一次电量，修复之后30秒取得一次电量，并缓存起来，30秒之内不取得电量直接用这个变量。

2.你说的两个解决办法都能解决问题，我个人更倾向于第二个，try catch之后亲测多次调用getContext().unregisterReceiver(battertReceiver);不会报错。

如果还有问题随时沟通
