### ISSUE TITLE
群主好，我切换ijk的时候，相关配置和文件都引入了，播放的时候还是异常

### ISSUE THREAD

**Issue by ymw2017** [lipangit/JiaoZiVideoPlayer#1871]
1.这些引入了；
    implementation 'tv.danmaku.ijk.media:ijkplayer-java:0.8.4'
    implementation 'tv.danmaku.ijk.media:ijkplayer-armv7a:0.8.4' 
2.so文件也加了；
![1526556623 1](https://user-images.githubusercontent.com/24970365/40174857-e650fc48-5a08-11e8-87c7-75be6cd195e4.jpg)
3.报错日志；
E/AndroidRuntime: FATAL EXCEPTION: JiaoZiVideoPlayer
                                                                          Process: com.bkd.bkdmobileandroid, PID: 14531
                                                                          java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.bkd.bkdmobileandroid-2/base.apk"],nativeLibraryDirectories=[/data/app/com.bkd.bkdmobileandroid-2/lib/arm, /data/app/com.bkd.bkdmobileandroid-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libtxsdl.so"
                                                                              at java.lang.Runtime.loadLibrary0(Runtime.java:972)
                                                                              at java.lang.System.loadLibrary(System.java:1530)
                                                                              at com.tencent.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:181)
                                                                              at com.tencent.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:193)
                                                                              at com.tencent.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:233)
                                                                              at com.tencent.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:229)
                                                                              at com.tencent.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:220)
                                                                              at com.bkd.bkdmobileandroid.txplayer.JZMediaIjkplayer.prepare(JZMediaIjkplayer.java:30)
                                                                              at cn.jzvd.JZMediaManager$MediaHandler.handleMessage(JZMediaManager.java:146)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                              at android.os.Looper.loop(Looper.java:203)
                                                                              at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by FlyArthur** [comment]
怎么解决的？

**Comment by yangwenwu** [comment]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader  

出现这个问题，说的是缺少so 库，可以这样解决  abiFilters  "armeabi","armeabi-v7a","arm64-v8a"
选择性的添加so `abiFilters  "armeabi","armeabi-v7a","arm64-v8a"`

**Comment by faith-hb** [comment]
demo里面没有so文件啊

**Comment by lipangit** [comment]
通过引用ijkplayer来引入
