### ISSUE TITLE
4.4华为手机全屏崩溃问题。

### ISSUE THREAD

**Issue by xiaojintongxue** [lipangit/JiaoZiVideoPlayer#1873]
java.lang.NullPointerException
                                                                          at android.graphics.Typeface.setThemeFontTypeface(Typeface.java:371)
                                                                          at android.graphics.Typeface.setThemeFont(Typeface.java:277)
                                                                          at android.app.Application.setThemeFontOnConfigChg(Application.java:316)
                                                                          at android.app.Application.onConfigurationChanged(Application.java:119)
                                                                          at android.app.ActivityThread.performConfigurationChanged(ActivityThread.java:4044)
                                                                          at android.app.ActivityThread.handleConfigurationChanged(ActivityThread.java:4120)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1382)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:136)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5336)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:515)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:871)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
                                                                          at dalvik.system.NativeStart.main(Native Method)

**Comment by lipangit** [comment]
和视频播放没看出来什么关系，有其他信息吗

**Comment by lipangit** [comment]
最近有崩溃的log吗
