### ISSUE TITLE
java.lang.IllegalStateException: Only fullscreen activities can request orientation (urgent help needed)

### ISSUE THREAD

**Issue by developerashish01** [lipangit/JiaoZiVideoPlayer#1889]
Fatal Exception: java.lang.RuntimeException
Unable to pause activity {pruminds.unchartedminds.com.prudential/pruminds.unchartedminds.com.prudential.activity.JzVideoPlayer}: java.lang.IllegalStateException: Only fullscreen activities can request orientation

Caused by java.lang.IllegalStateException
Only fullscreen activities can request orientation
android.os.Parcel.readException (Parcel.java:1966)
android.app.Activity.setRequestedOrientation (Activity.java:5831)
cn.jzvd.JZUtils.setRequestedOrientation (JZUtils.java:90)
pruminds.unchartedminds.com.prudential.activity.JzVideoPlayer.onPause (JzVideoPlayer.java:72)
android.app.Activity.performPause (Activity.java:7391)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1374)

**Comment by lipangit** [comment]
是不是你的屏幕无法横屏，调用横屏的代码报的错

**Comment by DurgaPentoz** [comment]
Hi i am also facing same issue pl provide a solution 


  java.lang.IllegalStateException: Only fullscreen activities can request orientation
                                                                 at com.android.server.am.ActivityRecord.setRequestedOrientation(ActivityRecord.java:2198)
                                                                 at com.android.server.am.ActivityManagerService.setRequestedOrientation(ActivityManagerService.java:5004)
                                                                 at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:1101)
                                                                 at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2992)
                                                                 at android.os.Binder.execTransact(Binder.java:674)
08-22 10:49:33.843 19176-19176/com.coptrade E/AndroidRuntime: FATAL EXCEPTION: main
                                                              Process: com.coptrade, PID: 19176
                                                              java.lang.IllegalStateException: Only fullscreen activities can request orientation
                                                                  at android.os.Parcel.readException(Parcel.java:1950)
                                                                  at android.os.Parcel.readException(Parcel.java:1888)
                                                                  at android.app.IActivityManager$Stub$Proxy.setRequestedOrientation(IActivityManager.java:5675)
                                                                  at android.app.Activity.setRequestedOrientation(Activity.java:5739)
                                                                  at cn.jzvd.JZUtils.setRequestedOrientation(JZUtils.java:90)
                                                                  at cn.jzvd.JZVideoPlayer.onCompletion(JZVideoPlayer.java:778)
                                                                  at cn.jzvd.JZVideoPlayerStandard.onCompletion(JZVideoPlayerStandard.java:806)
                                                                  at cn.jzvd.JZVideoPlayerManager.completeAll(JZVideoPlayerManager.java:42)
                                                                  at cn.jzvd.JZVideoPlayer.startVideo(JZVideoPlayer.java:599)
                                                                  at cn.jzvd.JZVideoPlayer.onClick(JZVideoPlayer.java:463)
                                                                  at cn.jzvd.JZVideoPlayerStandard.onClick(JZVideoPlayerStandard.java:254)
                                                                  at android.view.View.performClick(View.java:6256)
                                                                  at android.view.View$PerformClick.run(View.java:24697)
                                                                  at android.os.Handler.handleCallback(Handler.java:789)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                  at android.os.Looper.loop(Looper.java:164)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by lipangit** [comment]
Hello did you fix the problem
