### ISSUE TITLE
crash, The surface has been released

### ISSUE THREAD

**Issue by lzhhh** [lipangit/JiaoZiVideoPlayer#1911]
at android.media.MediaPlayer._setVideoSurface(Native Method)
	at android.media.MediaPlayer.setSurface(MediaPlayer.java:753)
	at cn.jzvd.d.a(JZMediaSystem.java:97)
	at cn.jzvd.c$a.handleMessage(JZMediaManager.java:168)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:224)
	at android.os.HandlerThread.run(HandlerThread.java:61)

概率性报错，5000用户7天报错2次。猜测是线程安全问题引起的，在JzVideoPlayer的onCompletion函数中有将surface realease的操作，这个方法的调用在主线程，MediaPlayer.setSurface的操作是在handleThread中，看代码handleMessage中：
                    if (savedSurfaceTexture != null) {
                        if (surface != null) {
                            surface.release();
                        }
                        surface = new Surface(savedSurfaceTexture);
                        jzMediaInterface.setSurface(surface);
                    }
已经有将之前的surface release的动作，麻烦看下有无必要在JzVideoPlayer的onCompletion函数中将surface release。

**Comment by lipangit** [comment]
有道理，兄弟有时间可以提交一下pr吗，参考MediaPlayer.release()，在JZMediaManager中，把surface的release放到handleThread中
