### ISSUE TITLE
rotate screen when play a video in Recyclerveiw

### ISSUE THREAD

**Issue by mhkhajehpoor** [lipangit/JiaoZiVideoPlayer#1981]
hi , tanx you for JiaoZiVideoPlayer

my defult orintion is landscap , when i play a video item and go to play other video item ,the screen rotate auto to portrat.

**Comment by lipangit** [comment]
landscap = fullscreen?

**Comment by mhkhajehpoor** [comment]
Solved with this code
holder.videoplayer.NORMAL_ORIENTATION = SCREEN_ORIENTATION_LANDSCAPE;
        holder.videoplayer.FULLSCREEN_ORIENTATION = SCREEN_ORIENTATION_LANDSCAPE;

**Comment by mhkhajehpoor** [comment]
Thanks for the answer. How do I get a fullscreen video inside Recyclerveiw when I click on the play icon?

**Comment by lipangit** [comment]
JZVideoManager.getCurrentJZVD().

**Comment by mhkhajehpoor** [comment]
Hello .
Where do you have to use this method?
![video](https://user-images.githubusercontent.com/38702413/42292720-b4c78a00-7fe9-11e8-9086-674e5498bea0.png)

**Comment by lipangit** [comment]
JZVideoPlayerManager.getCurrentJzvd() if can call that method every where.

if == null means video not play.

**Comment by mhkhajehpoor** [comment]
How do you use it right? Do you mean?
I want to get a fullscreen video when I click on the play icon of videoveiw.
this my code:


![a](https://user-images.githubusercontent.com/38702413/42329547-27a9ae30-8086-11e8-81fe-2f260f6a88e7.png)

I'm sorry for being an amateur, if it's easy to explain

**Comment by lipangit** [comment]
extends JZVideoPlayerStandard，
Override onClick(){
    //click what icon, write your event.
  
}

**Comment by mhkhajehpoor** [comment]
Do you mean
![image](https://user-images.githubusercontent.com/38702413/42416204-8575d144-827d-11e8-8aee-5c3d1ff8575b.png)

**Comment by lipangit** [comment]
Yes , right, see smallChangeUIActivity in demo.

**Comment by mhkhajehpoor** [comment]
ok,After this I went to overwrite these methods
![image](https://user-images.githubusercontent.com/38702413/42449684-dc553896-8396-11e8-996d-0886d12f2b3a.png)
And then  inside the Recyclerview Adapter in the View Holder :
![cast](https://user-images.githubusercontent.com/38702413/42449861-7d35f930-8397-11e8-8ca9-212fb45f889c.png)
And finally, I made the settings in the onBindViewHolder section:
![cast](https://user-images.githubusercontent.com/38702413/42449983-f0ac70b0-8397-11e8-8987-d5d0ca352a11.png)

But when I run the app, the app closes (Unfortunately, has stopped)

I am very thankful for your help

**Comment by mhkhajehpoor** [comment]
Something else how to change the video playback error?
![image](https://user-images.githubusercontent.com/38702413/42454699-6c37d442-83a5-11e8-8815-0339943e3d19.png)

**Comment by lipangit** [comment]
app close what log

**Comment by mhkhajehpoor** [comment]
E/dalvikvm: Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method android.support.v7.widget.AppCompatImageHelper.hasOverlappingRendering
07-10 20:05:08.313 3773-3773/ir.offsi.offsi E/cat_id: 1
07-10 20:05:10.383 3773-3773/ir.olm.olmE/AndroidRuntime: FATAL EXCEPTION: main
    Process: ir.olm.olm, PID: 3773
    java.lang.ClassCastException: cn.jzvd.JZVideoPlayerStandard cannot be cast to ir.offsi.offsi.customVideoPlayer
        at ir.olm.olm.Adapter.VideoAdapter$VideoViewHolder.<init>(VideoAdapter.java:138)
        at ir.olm.olm.Adapter.VideoAdapter.onCreateViewHolder(VideoAdapter.java:53)
        at ir.olm.olm.Adapter.VideoAdapter.onCreateViewHolder(VideoAdapter.java:37)
        at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6367)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5555)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:570)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
        at android.view.View.layout(View.java:14817)
        at android.view.ViewGroup.layout(ViewGroup.java:4631)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
        at android.view.View.layout(View.java:14817)
        at android.view.ViewGroup.layout(ViewGroup.java:4631)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
        at android.view.View.layout(View.java:14817)
        at android.view.ViewGroup.layout(ViewGroup.java:4631)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
        at android.view.View.layout(View.java:14817)
        at android.view.ViewGroup.layout(ViewGroup.java:4631)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
        at android.view.View.layout(View.java:14817)
        at android.view.ViewGroup.layout(ViewGroup.java:4631)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
        at android.view.View.layout(View.java:14817)
        at android.view.ViewGroup.layout(ViewGroup.java:4631)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
        at android.view.View.layout(View.java:14817)
        at android.view.ViewGroup.layout(ViewGroup.java:4631)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2011)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1768)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1024)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5694)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
        at android.view.Choreographer.doCallbacks(Choreographer.java:574)
        at android.view.Choreographer.doFrame(Choreographer.java:544)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5019)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
    	at com.androi

**Comment by lipangit** [comment]
java.lang.ClassCastException: cn.jzvd.JZVideoPlayerStandard cannot be cast to ir.olm.olm.customVideoPlayer

That is the point

**Comment by lipangit** [comment]
the same as change quality, see apiactivity in demo.

**Comment by mhkhajehpoor** [comment]
tanx
