### ISSUE TITLE
Play the next video after the video finishes

### ISSUE THREAD

**Issue by mhkhajehpoor** [lipangit/JiaoZiVideoPlayer#2018]
How can I play the next video automatically when the video is playing out?
Thank you so much

**Comment by lipangit** [comment]
It is the same as change clarity.

when autoComplete to change the clarity.

**Comment by deryfath** [comment]
I dont understand what you mean, can you explain more detail? I have been search for autoComplete implement code, but nothing found.
thank you so much

**Comment by deryfath** [comment]
i've been already make a class extend JZVideoPlayerStandard but I have error like this when call in my activity: 

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.dapurilmu.mobile, PID: 29754
                  java.lang.ClassCastException: cn.jzvd.JZVideoPlayerStandard cannot be cast to com.dapurilmu.mobile.extension.PlaylistModuleVideoLayout
                      at com.dapurilmu.mobile.activity.ui.main.module.ModuleDetailActivity$onLoadModuleDetailSuccess$4.onClick(ModuleDetailActivity.kt:192)
                      at android.view.View.performClick(View.java:4785)
                      at android.view.View$PerformClick.run(View.java:19888)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:135)
                      at android.app.ActivityThread.main(ActivityThread.java:5273)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)


and this is my new class extend : 

class PlaylistModuleVideoLayout : JZVideoPlayerStandard {

    constructor(context: Context) : super(context) {}

    constructor(context: Context, attrs: AttributeSet) : super(context, attrs) {}

    override fun init(context: Context) {
        super.init(context)

    }

    override fun getLayoutId(): Int {
        return R.layout.playlist_module_video_layout
    }

    override fun onClick(v: View) {
        super.onClick(v)

    }


}

**Comment by deryfath** [comment]
i've been already make a class extend JZVideoPlayerStandard but I have error like this when call in my activity:

E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.dapurilmu.mobile, PID: 29754
java.lang.ClassCastException: cn.jzvd.JZVideoPlayerStandard cannot be cast to com.dapurilmu.mobile.extension.PlaylistModuleVideoLayout
at com.dapurilmu.mobile.activity.ui.main.module.ModuleDetailActivity$onLoadModuleDetailSuccess$4.onClick(ModuleDetailActivity.kt:192)
at android.view.View.performClick(View.java:4785)
at android.view.View$PerformClick.run(View.java:19888)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5273)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)

and this is my new class extend :

class PlaylistModuleVideoLayout : JZVideoPlayerStandard {

constructor(context: Context) : super(context) {}

constructor(context: Context, attrs: AttributeSet) : super(context, attrs) {}

override fun init(context: Context) {
    super.init(context)

}

override fun getLayoutId(): Int {
    return R.layout.playlist_module_video_layout
}

override fun onClick(v: View) {
    super.onClick(v)

}
}

**Comment by mhkhajehpoor** [comment]
Hello, thanks for the comment, is it possible to explain more and more easily?

**Comment by deryfath** [comment]
Sorry for this, it was solved when I created new issue.

**Comment by mhkhajehpoor** [comment]
Hello, my friend, lipangit. Unfortunately, I still could not solve this problem. First, I play video on the main activity 
![image](https://user-images.githubusercontent.com/38702413/44300718-fc2eb300-a320-11e8-89c2-2d62aa2ef514.png)
, then I created a class and extracted from your library and wrote the onAutoCompletion () method and wrote it inside this method
![image](https://user-images.githubusercontent.com/38702413/44300747-75c6a100-a321-11e8-9665-e611bb300912.png)
, but The app closes and has logs. Thanks for your help

**Comment by lipangit** [comment]
what log

**Comment by mhkhajehpoor** [comment]
08-19 21:58:15.613 2015-2239/ir.offsi.offsi E/MediaPlayer: Should have subtitle controller already set
08-19 21:58:23.223 2015-2015/ir.offsi.offsi E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ir.offsi.offsi, PID: 2015
    java.lang.NullPointerException
        at ir.offsi.offsi.AutoVideoPlayer.onAutoCompletion(AutoVideoPlayer.java:93)
        at cn.jzvd.JZMediaSystem$2.run(JZMediaSystem.java:126)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5019)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/44323196-6c554a00-a483-11e8-8e93-755669ea4d0e.png)

This is the wrong usage.

**Comment by mhkhajehpoor** [comment]
![image](https://user-images.githubusercontent.com/38702413/44420373-f3ddae80-a592-11e8-8be2-ef2160dd6713.png)

What do you mean by Clarity ? How do you change it? 
this way?
I did that, right?


![image](https://user-images.githubusercontent.com/38702413/44420454-37381d00-a593-11e8-8c6a-5580ee13e834.png)

I did that, but did not work

**Comment by lipangit** [comment]
clarity in demo in apiActivity when fullscreen you can see it

**Comment by mhkhajehpoor** [comment]
In this section:    JiaoZiVideoPlayer/app/src/main/java/cn/jzvd/demo/ActivityApi.java  
 you did not use the ironing method.
What kind of method should I use to play the next video?
That is, the first video to be played, then the second video will be played

**Comment by lipangit** [comment]
call onStatePreparingChangingUrl()

**Comment by mhkhajehpoor** [comment]
How do I put the next video url inside this method?

**Comment by lipangit** [comment]
see apiactivity in demo

**Comment by mhkhajehpoor** [comment]
My problem is solved, I'm leaving the code:
in Main Activity:

`autoVideoPlayer.setUp(video_urls[index],JZVideoPlayerStandard.SCREEN_WINDOW_FULLSCREEN,"");
                        autoVideoPlayer.NORMAL_ORIENTATION = SCREEN_ORIENTATION_LANDSCAPE;
                        autoVideoPlayer.changeUiToNormal();
                        //autoVideoPlayer.FULLSCREEN_ORIENTATION = SCREEN_ORIENTATION_LANDSCAPE;
                        autoVideoPlayer.startVideo();
                        autoVideoPlayer.nextVideo = new AutoVideoPlayer.NextVideo() {
                            @Override
                            public void nextVideo(AutoVideoPlayer a) {
                                Intent intent = new Intent(AutoPlay.this, AutoPlay.class);
                                intent.putExtra("list", video_urls);
                                index++;
                                intent.putExtra("index", index);
                                if (index < video_urls.length)
                                    startActivity(intent);
                                finish();
                            }
                        }; `


in class AutoVideoPlayer extends JZVideoPlayerStandard  :

`public class AutoVideoPlayer extends JZVideoPlayerStandard implements View.OnClickListener {

    public NextVideo nextVideo;

    public AutoVideoPlayer(Context context) {
        super(context);
    }

    public AutoVideoPlayer(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    @Override
    public void init(Context context) {
        super.init(context);
    }

    @Override
    public void onAutoCompletion() {
        super.onAutoCompletion();

        if (nextVideo != null) {
            nextVideo.nextVideo(this);
        }
    }

    public interface NextVideo {
        void nextVideo(AutoVideoPlayer a);
    }
}`

**Comment by deryfath** [comment]
i have error like this when I try ur code, can u solved

/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.dapurilmu.mobile, PID: 21421
                  java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.dapurilmu.mobile/com.dapurilmu.mobile.extension.PlaylistModuleVideoLayout}: java.lang.InstantiationException: class com.dapurilmu.mobile.extension.PlaylistModuleVideoLayout has no zero argument constructor
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2241)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392)
                      at android.app.ActivityThread.access$800(ActivityThread.java:154)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:135)
                      at android.app.ActivityThread.main(ActivityThread.java:5273)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
                   Caused by: java.lang.InstantiationException: class com.dapurilmu.mobile.extension.PlaylistModuleVideoLayout has no zero argument constructor
                      at java.lang.Class.newInstance(Class.java:1597)
                      at android.app.Instrumentation.newActivity(Instrumentation.java:1069)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2231)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392) 
                      at android.app.ActivityThread.access$800(ActivityThread.java:154) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:135) 
                      at android.app.ActivityThread.main(ActivityThread.java:5273) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:372) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703) 
                   Caused by: java.lang.NoSuchMethodException: <init> []
                      at java.lang.Class.getConstructor(Class.java:531)
                      at java.lang.Class.getDeclaredConstructor(Class.java:510)
                      at java.lang.Class.newInstance(Class.java:1595)
                      at android.app.Instrumentation.newActivity(Instrumentation.java:1069) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2231) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392) 
                      at android.app.ActivityThread.access$800(ActivityThread.java:154) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:135) 
                      at android.app.ActivityThread.main(ActivityThread.java:5273) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:372) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)

**Comment by lipangit** [comment]
Caused by: java.lang.InstantiationException: class com.dapurilmu.mobile.extension.PlaylistModuleVideoLayout has no zero argument constructor
that is the point. What is PlaylistModuleVideoLayout.

**Comment by deryfath** [comment]
PlaylistModuleVideoLayout class that extends JZvideoplayerstandard

**Comment by deryfath** [comment]
how to stay fullscreen when in fullscreen mode in onAutoCompletion function?

**Comment by mhkhajehpoor** [comment]
`autoVideoPlayer.setUp(proxyUrl,JZVideoPlayerStandard.SCREEN_WINDOW_FULLSCREEN,"");
                        autoVideoPlayer.NORMAL_ORIENTATION = SCREEN_ORIENTATION_LANDSCAPE;`

**Comment by mhkhajehpoor** [comment]
This code is in the activity that your player has and you do not need to use the OnAutoCompilition method for full screen and stay

**Comment by lipangit** [comment]
See demo SmallChangeActivity show you how to stay fullscreen in fullscreen.

**Comment by nilrambhad** [comment]
hi @lipangit please help me for  continue play next video  normal mode or full screen mode without affecting last mode exp if I am watching in any normal mode or full screen mode needs to maintain.
