### ISSUE TITLE
 Error inflating class cn.jzvd.demo.CustomView.MyJZVideoPlayerStandard

### ISSUE THREAD

**Issue by unosbaghaie** [lipangit/JiaoZiVideoPlayer#2041]
hi

I followed the demo app, when the play activity opens up, app crashes
this is the error

`E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: ir.swifttips.fidiboo, PID: 7454
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{ir.swifttips.fidiboo/my.activities.PlayVideoActivity}: android.view.InflateException: Binary XML file line #17: Binary XML file line #17: Error inflating class cn.jzvd.demo.CustomView.MyJZVideoPlayerStandard
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                      at android.app.ActivityThread.-wrap11(Unknown Source:0)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                      at android.os.Handler.dispatchMessage(Handler.java:105)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6541)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                   Caused by: android.view.InflateException: Binary XML file line #17: Binary XML file line #17: Error inflating class cn.jzvd.demo.CustomView.MyJZVideoPlayerStandard
                   Caused by: android.view.InflateException: Binary XML file line #17: Error inflating class cn.jzvd.demo.CustomView.MyJZVideoPlayerStandard
                   Caused by: java.lang.ClassNotFoundException: Didn't find class "cn.jzvd.demo.CustomView.MyJZVideoPlayerStandard" on path: DexPathList[[zip file "/data/app/ir.swifttips.fidiboo-KVoyNc1_GQJTXJRINNlvcQ==/base.apk"],nativeLibraryDirectories=[/data/app/ir.swifttips.fidiboo-KVoyNc1_GQJTXJRINNlvcQ==/lib/x86, /data/app/ir.swifttips.fidiboo-KVoyNc1_GQJTXJRINNlvcQ==/base.apk!/lib/x86, /system/lib, /system/vendor/lib]]
                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                      at android.view.LayoutInflater.createView(LayoutInflater.java:606)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                      at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                      at my.activities.PlayVideoActivity.onCreate(PlayVideoActivity.java:33)
                      at android.app.Activity.performCreate(Activity.java:6975)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                      at android.app.ActivityThread.-wrap11(Unknown Source:0)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                      at android.os.Handler.dispatchMessage(Handler.java:105)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6541)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)`

**Comment by lipangit** [comment]
check every id in xml. I is the only way to the log.
