### ISSUE TITLE
Cant create new class extend JZVideoPlayerStandard

### ISSUE THREAD

**Issue by deryfath** [lipangit/JiaoZiVideoPlayer#2043]
i've been already make a class extend JZVideoPlayerStandard but I have error like this when call in my activity:

E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.dapurilmu.mobile, PID: 29754
java.lang.ClassCastException: cn.jzvd.JZVideoPlayerStandard cannot be cast to com.dapurilmu.mobile.extension.PlaylistModuleVideoLayout
at com.dapurilmu.mobile.activity.ui.main.module.ModuleDetailActivity$onLoadModuleDetailSuccess$4.onClick(ModuleDetailActivity.kt:192)
at android.view.View.performClick(View.java:4785)
at android.view.View$PerformClick.run(View.java:19888)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5273)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)

and this is my new class extend :

class PlaylistModuleVideoLayout : JZVideoPlayerStandard {

constructor(context: Context) : super(context) {}

constructor(context: Context, attrs: AttributeSet) : super(context, attrs) {}

override fun init(context: Context) {
    super.init(context)

}

override fun getLayoutId(): Int {
    return R.layout.playlist_module_video_layout
}

override fun onClick(v: View) {
    super.onClick(v)

}
}

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/43902596-1443f924-9c1d-11e8-93ab-7c5542709415.png)

this is the point

**Comment by deryfath** [comment]
thanks a lot, sorry for my fault not to see more detail.
