### ISSUE TITLE
full screen problem

### ISSUE THREAD

**Issue by abas1** [lipangit/JiaoZiVideoPlayer#2047]
Hi, I'm use JZVideoPlayerStandard in ListView and play videos from asset (by CustomMediaPlayerAssertFolder). but when video play in full screen mode, back button can't stop video and app is crashed while video is playing. also pause button causing null pointer exception.

**Comment by lipangit** [comment]
what log when crashed

**Comment by abas1** [comment]
08-13 10:31:38.646 1846-1846/com.vocabulary.hrs.vocabulary E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: com.vocabulary.hrs.vocabulary, PID: 1846
                                                                             java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.MediaPlayer.pause()' on a null object reference
                                                                                 at tools.CustomMediaPlayer.CustomMediaPlayerAssertFolder.pause(CustomMediaPlayerAssertFolder.java:48)
                                                                                 at cn.jzvd.JZMediaManager.pause(JZMediaManager.java:82)
                                                                                 at cn.jzvd.JZVideoPlayer.onClick(JZVideoPlayer.java:455)
                                                                                 at cn.jzvd.JZVideoPlayerStandard.onClick(JZVideoPlayerStandard.java:254)
                                                                                 at android.view.View.performClick(View.java:5637)
                                                                                 at android.view.View$PerformClick.run(View.java:22429)
                                                                                 at android.os.Handler.handleCallback(Handler.java:751)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                 at android.os.Looper.loop(Looper.java:154)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by lipangit** [comment]
break Point at  JZVideoPlayer.releaseAllVideos(), because the MediaPlayer is null.

**Comment by abas1** [comment]
one of my problem is that I don't know where is code behind of buttons in full screen mode.

**Comment by lipangit** [comment]
JZVideoPlayerStandard onClick() function
