### ISSUE TITLE
change mediainterface to Exo but can not play rtsp url

### ISSUE THREAD

**Issue by fukemy** [lipangit/JiaoZiVideoPlayer#2056]
i copy JZExoPlayer class to my project and change mediaInterface to Exo. Then i see the device can not play rtsp but work well in other exo lib.  here is the log

```
08-18 23:10:58.059 10184-10426/com.futurisx.icamera E/JZExoPlayer: prepare
08-18 23:10:58.256 10184-10426/com.futurisx.icamera E/JZExoPlayer: URL Link = rtsp://184.72.239.149/vod/mp4:BigBuckBunny_175k.mov
08-18 23:10:58.260 10184-10426/com.futurisx.icamera E/JZExoPlayer: onPlayerStateChanged2/ready=false
08-18 23:10:58.262 10184-10426/com.futurisx.icamera E/JZExoPlayer: onPlayerStateChanged2/ready=true
08-18 23:10:58.269 10184-10426/com.futurisx.icamera E/JZExoPlayer: setSurface
08-18 23:10:58.270 10184-10426/com.futurisx.icamera E/JZExoPlayer: onTimelineChanged
08-18 23:10:58.368 10184-10426/com.futurisx.icamera E/JZExoPlayer: onLoadingChanged
08-18 23:11:01.408 10184-10452/com.futurisx.icamera E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to rtsp://184.72.239.149/vod/mp4:BigBuckBunny_175k.mov
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:194)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:147)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:841)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.net.MalformedURLException: unknown protocol: rtsp
        at java.net.URL.<init>(URL.java:597)
        at java.net.URL.<init>(URL.java:487)
        at java.net.URL.<init>(URL.java:436)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:341)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:192)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:147) 
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:841) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
08-18 23:11:01.413 10184-10426/com.futurisx.icamera E/JZExoPlayer: onPlayerErrorcom.google.android.exoplayer2.ExoPlaybackException
08-18 23:11:01.414 10184-10426/com.futurisx.icamera E/JZExoPlayer: onLoadingChanged
08-18 23:11:01.416 10184-10426/com.futurisx.icamera E/JZExoPlayer: onPlayerStateChanged1/ready=true
08-18 23:11:01.421 10184-10184/com.futurisx.icamera E/JiaoZiVideoPlayer: onError 1000 - 1000 [40997727] 
```

here is my code:

```
 JZVideoPlayerStandard.setMediaInterface(new JZExoPlayer());
        JZVideoPlayerStandard jzVideoPlayerStandard = findViewById(R.id.videoplayer);
        jzVideoPlayerStandard.thumbImageView.setScaleType(ImageView.ScaleType.CENTER_CROP);

        jzVideoPlayerStandard.setUp("rtsp://184.72.239.149/vod/mp4:BigBuckBunny_175k.mov",
                JZVideoPlayerStandard.SCREEN_WINDOW_NORMAL, "");

        Picasso.get()
                .load("https://user-images.githubusercontent.com/2038071/31045150-a077cc8a-a5a2-11e7-8dc2-7a0e3a9f3e62.jpg")
                .placeholder(R.mipmap.logo_tranporx_large)
                .resize(getResources().getDisplayMetrics().heightPixels, getResources().getDisplayMetrics().widthPixels)
                .into(jzVideoPlayerStandard.thumbImageView);
```
my gradle:

````
implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:27.1.0'
    implementation 'com.android.support:design:27.1.0'

    implementation 'com.jakewharton.rxbinding2:rxbinding:2.1.1'
    implementation 'com.amitshekhar.android:rx-android-networking:1.0.0'
    implementation 'com.amitshekhar.android:android-networking:1.0.2'
    implementation 'com.google.code.gson:gson:2.8.1'
    implementation 'com.github.rafakob:DrawMe:0.1.6'
    implementation 'fr.tvbarthel.blurdialogfragment:lib:2.2.0'
    implementation 'com.github.florent37:viewanimator:1.0.5'
    implementation 'com.tbruyelle.rxpermissions2:rxpermissions:0.9.5@aar'
    implementation 'com.jakewharton:butterknife:8.8.1'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'
    implementation 'com.aurelhubert:ahbottomnavigation:2.1.0'
    implementation 'cn.jzvd:jiaozivideoplayer:6.2.12'
    implementation 'com.squareup.picasso:picasso:2.71828'
    implementation 'com.google.android.exoplayer:exoplayer:2.7.1'
```

**Comment by lipangit** [comment]
Caused by: java.net.MalformedURLException: unknown protocol: rtsp   that is the point.

**Comment by fukemy** [comment]
thanks for quick response, i changed to use your ijk then now it work 💯 %
