### ISSUE TITLE
Issue with oreo device

### ISSUE THREAD

**Issue by DurgaPentoz** [lipangit/JiaoZiVideoPlayer#2064]
Solution for below issue will be helping me a lot.Kindly provide a solution. 

 java.lang.IllegalStateException: Only fullscreen activities can request orientation
                                                                 at com.android.server.am.ActivityRecord.setRequestedOrientation(ActivityRecord.java:2198)
                                                                 at com.android.server.am.ActivityManagerService.setRequestedOrientation(ActivityManagerService.java:5004)
                                                                 at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:1101)
                                                                 at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2992)
                                                                 at android.os.Binder.execTransact(Binder.java:674)
08-22 10:49:33.843 19176-19176/com.coptrade E/AndroidRuntime: FATAL EXCEPTION: main
                                                              Process: com.coptrade, PID: 19176
                                                              java.lang.IllegalStateException: Only fullscreen activities can request orientation
                                                                  at android.os.Parcel.readException(Parcel.java:1950)
                                                                  at android.os.Parcel.readException(Parcel.java:1888)
                                                                  at android.app.IActivityManager$Stub$Proxy.setRequestedOrientation(IActivityManager.java:5675)
                                                                  at android.app.Activity.setRequestedOrientation(Activity.java:5739)
                                                                  at cn.jzvd.JZUtils.setRequestedOrientation(JZUtils.java:90)
                                                                  at cn.jzvd.JZVideoPlayer.onCompletion(JZVideoPlayer.java:778)
                                                                  at cn.jzvd.JZVideoPlayerStandard.onCompletion(JZVideoPlayerStandard.java:806)
                                                                  at cn.jzvd.JZVideoPlayerManager.completeAll(JZVideoPlayerManager.java:42)
                                                                  at cn.jzvd.JZVideoPlayer.startVideo(JZVideoPlayer.java:599)
                                                                  at cn.jzvd.JZVideoPlayer.onClick(JZVideoPlayer.java:463)
                                                                  at cn.jzvd.JZVideoPlayerStandard.onClick(JZVideoPlayerStandard.java:254)
                                                                  at android.view.View.performClick(View.java:6256)
                                                                  at android.view.View$PerformClick.run(View.java:24697)
                                                                  at android.os.Handler.handleCallback(Handler.java:789)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                  at android.os.Looper.loop(Looper.java:164)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by DurgaPentoz** [comment]
Yes with Oreo device video is playing but when I reply or on pause the
issue I mentioned is found.pl provide a solution.

Regards
Durga

**Comment by DurgaPentoz** [comment]
And When i pause Activity also Facing this issue.With oreo version portrait screen orientation should not be given in Manifest

**Comment by lipangit** [comment]
Stay concerned
