### ISSUE TITLE
请教一下,播放网络视频,在同一个页面,我先播放一个视频,没有任何问题,但是切换另一个视频地址,然后在按全屏播放就闪退了.请问何解?

### ISSUE THREAD

**Issue by winfuckyou** [lipangit/JiaoZiVideoPlayer#2069]
**什么jzvd版本

**是否和安卓版本有关系，什么版本

**是否和特定品牌的手机机型有关系，什么机型

**相关log是什么

**复现流程

**最好有截图或者视频说明情况

**Comment by winfuckyou** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference
                                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:435)
                                                                                        at android.view.View.measure(View.java:17621)
                                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5548)
                                                                                        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1467)
                                                                                        at android.widget.LinearLayout.measureVertical(LinearLayout.java:747)
                                                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:638)
                                                                                        at android.view.View.measure(View.java:17621)
                                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5548)
                                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
                                                                                        at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2636)
                                                                                        at android.view.View.measure(View.java:17621)
                                                                                        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2081)
                                                                                        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1217)
                                                                                        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1423)
                                                                                        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1105)
                                                                                        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6204)
                                                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:799)
                                                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:612)
                                                                                        at android.view.Choreographer.doFrame(Choreographer.java:581)
                                                                                        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:785)
                                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                        at android.os.Looper.loop(Looper.java:135)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:5593)
                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                        at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)

**Comment by lipangit** [comment]
在releaseAllVideos函数中打断点，在不应该调这个函数的时候调用了它。

**Comment by winfuckyou** [comment]
protected void onPause() {
        super.onPause();
        VideoPlayerStandard.releaseAllVideos();
    }
我只有在onPause()调用了,没其他地方调用的

**Comment by winfuckyou** [comment]
我qq827032104能加一下吗?你们上面的qq加了都没反应

**Comment by lipangit** [comment]
运行的时候打断点

**Comment by winfuckyou** [comment]
打了,不会到VideoPlayerStandard.releaseAllVideos()的任何地方,
VideoPlayerStandard.setUp(url,JZVideoPlayerStandard.SCREEN_WINDOW_NORMAL,"")这个方法,一个视频正在播放,我再去使用一次这个方法,然后按全屏就会出这个错误,100%出现

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/44770344-58ec6200-ab9a-11e8-8ab8-ba1fb6101261.png)


断点一下这里试试

**Comment by winfuckyou** [comment]
调了,切换会到这里,我该怎么做猜不到这里呢

**Comment by lipangit** [comment]
@winfuckyou 兄弟，你看行数的调用堆栈，怎么样了解决了吗
