### ISSUE TITLE
 JZMediaManager.pause();

### ISSUE THREAD

**Issue by ag2m** [lipangit/JiaoZiVideoPlayer#2076]
when a video is finish and press back button
app show force close 
here is my code"
   if (JZMediaManager.getCurrentDataSource() != null) {
  
                JZMediaManager.pause();

        }

**Comment by lipangit** [comment]
what log

**Comment by ag2m** [comment]
09-02 16:08:42.481 6517-6517/ir.ag2m.videotutorial E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ir.ag2m.videotutorial, PID: 6517
    java.lang.RuntimeException: Unable to start activity ComponentInfo{ir.ag2m.videotutorial/ir.ag2m.videotutorial.Activity.MainActivity}: java.lang.IllegalStateException
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
     Caused by: java.lang.IllegalStateException
        at android.media.MediaPlayer._pause(Native Method)
        at android.media.MediaPlayer.pause(MediaPlayer.java:1249)
        at cn.jzvd.JZMediaSystem.pause(JZMediaSystem.java:54)
        at cn.jzvd.JZMediaManager.pause(JZMediaManager.java:82)
        at ir.ag2m.videotutorial.CustomUtil.pauseVideo(CustomUtil.java:16)
        at ir.ag2m.videotutorial.Activity.MainActivity$2.onSelectedItemChanged(MainActivity.java:99)
        at com.ss.bottomnavigation.BottomNavigation.setOnSelectedItemChangeListener(BottomNavigation.java:283)
        at ir.ag2m.videotutorial.Activity.MainActivity.onCreate(MainActivity.java:96)
        at android.app.Activity.performCreate(Activity.java:6679)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6119) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
09-02 16:08:43.122 1361-6304/? E/AudioFlinger: not enough memory for AudioTrack size=131296
09-02 16:08:43.123 1361-6304/? E/AudioFlinger: createRecordTrack_l() initCheck failed -12; no control block?
09-02 16:08:43.123 2382-5076/com.google.android.googlequicksearchbox:search E/AudioRecord: AudioFlinger could not create record track, status: -12
09-02 16:08:43.128 2382-5076/com.google.android.googlequicksearchbox:search E/AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -12.
09-02 16:08:43.128 2382-5076/com.google.android.googlequicksearchbox:search E/android.media.AudioRecord: Error code -20 when initializing native AudioRecord object.
09-02 16:08:43.143 2382-5076/com.google.android.googlequicksearchbox:search E/ActivityThread: Failed to find provider info for com.google.android.apps.gsa.testing.ui.audio.recorded

**Comment by ag2m** [comment]
09-02 16:13:36.732 7431-7431/ir.ag2m.videotutorial E/InputEventSender: Exception dispatching finished signal.
09-02 16:13:36.732 7431-7431/ir.ag2m.videotutorial E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
09-02 16:13:36.733 7431-7431/ir.ag2m.videotutorial E/MessageQueue-JNI: java.lang.IllegalStateException
        at android.media.MediaPlayer.isPlaying(Native Method)
        at cn.jzvd.JZMediaSystem.isPlaying(JZMediaSystem.java:59)
        at cn.jzvd.JZMediaManager.isPlaying(JZMediaManager.java:90)
        at ir.ag2m.videotutorial.Activity.MainActivity.onBackPressed(MainActivity.java:208)
        at android.app.Activity.onKeyUp(Activity.java:2725)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2712)
        at android.support.v4.view.KeyEventDispatcher.activitySuperDispatchKeyEventPre28(KeyEventDispatcher.java:137)
        at android.support.v4.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:87)
        at android.support.v4.app.SupportActivity.dispatchKeyEvent(ComponentActivity.java:126)
        at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:535)
        at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        at android.support.v7.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:2533)
        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:319)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4331)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4302)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3999)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4056)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4032)
        at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4193)
        at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2400)
        at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1964)
        at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1955)
        at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2377)
        at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:323)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
09-02 16:13:36.733 7431-7431/ir.ag2m.videotutorial E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ir.ag2m.videotutorial, PID: 7431
    java.lang.IllegalStateException
        at android.media.MediaPlayer.isPlaying(Native Method)
        at cn.jzvd.JZMediaSystem.isPlaying(JZMediaSystem.java:59)
        at cn.jzvd.JZMediaManager.isPlaying(JZMediaManager.java:90)
        at ir.ag2m.videotutorial.Activity.MainActivity.onBackPressed(MainActivity.java:208)
        at android.app.Activity.onKeyUp(Activity.java:2725)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2712)
        at android.support.v4.view.KeyEventDispatcher.activitySuperDispatchKeyEventPre28(KeyEventDispatcher.java:137)
        at android.support.v4.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:87)
        at android.support.v4.app.SupportActivity.dispatchKeyEvent(ComponentActivity.java:126)
        at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:535)
        at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        at android.support.v7.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:2533)
        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:319)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4331)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4302)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3999)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4056)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4032)
        at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4193)
        at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2400)
        at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1964)
        at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1955)
        at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2377)
        at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:323)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
    
    
    --------- beginning of system
09-02 16:13:37.294 1306-1306/? E/EGL_emulation: tid 1306: eglCreateSyncKHR(1881): error 0x3004 (EGL_BAD_ATTRIBUTE)
09-02 16:13:37.502 1361-6305/? E/AudioFlinger: not enough memory for AudioTrack size=131296
09-02 16:13:37.502 1361-6305/? E/AudioFlinger: createRecordTrack_l() initCheck failed -12; no control block?
09-02 16:13:37.502 2382-5076/com.google.android.googlequicksearchbox:search E/AudioRecord: AudioFlinger could not create record track, status: -12
09-02 16:13:37.512 2382-5076/com.google.android.googlequicksearchbox:search E/AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -12.
09-02 16:13:37.512 2382-5076/com.google.android.googlequicksearchbox:search E/android.media.AudioRecord: Error code -20 when initializing native AudioRecord object.
09-02 16:13:37.524 2382-5076/com.google.android.googlequicksearchbox:search E/ActivityThread: Failed to find provider info for com.google.android.apps.gsa.testing.ui.audio.recorded

**Comment by ag2m** [comment]
and when the internet is on and I exit from app an set internet turn off  and again open the app this line cause 
app show force close

**Comment by ag2m** [comment]
I solved it with
[https://github.com/lipangit/JiaoZiVideoPlayer/issues/2061#issuecomment-414991762](your previous answer)

**Comment by ag2m** [comment]
I solved it with
your previous answer:
https://github.com/lipangit/JiaoZiVideoPlayer/issues/2061#issuecomment-414991762

thanks!

**Comment by lipangit** [comment]
good
