### ISSUE TITLE
更新到最新版之后报错 java.lang.NoSuchMethodError: No static method getCurrentUrl()

### ISSUE THREAD

**Issue by Yrdan** [lipangit/JiaoZiVideoPlayer#2087]
更新到最新版之后，setup()报错
LOG信息：
`  java.lang.NoSuchMethodError: No static method getCurrentUrl()Ljava/lang/Object; in class Lcn/jzvd/JZMediaManager; or its super classes (declaration of 'cn.jzvd.JZMediaManager' appears in /data/app/com.shijinsz.shijinsz-1/base.apk:classes5.dex)
                                                                           at cn.jzvd.Jzvd.setUp(Jzvd.java:415)
                                                                           at cn.jzvd.JzvdStd.setUp(JzvdStd.java:117)
                                                                           at cn.jzvd.Jzvd.setUp(Jzvd.java:394)
                                                                           at com.shijinsz.shijinsz.ui.ad.VideoDetailActivity.initHead(VideoDetailActivity.java:387)
                                                                           at com.shijinsz.shijinsz.ui.ad.VideoDetailActivity.initAdapter(VideoDetailActivity.java:166)
                                                                           at com.shijinsz.shijinsz.ui.ad.VideoDetailActivity.initView(VideoDetailActivity.java:134)
                                                                           at com.shijinsz.shijinsz.base.BaseActivity.onResume(BaseActivity.java:293)
                                                                           at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1266)
                                                                           at android.app.Activity.performResume(Activity.java:6446)
                                                                           at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3129)
                                                                           at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3170)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2516)
                                                                           at android.app.ActivityThread.access$900(ActivityThread.java:165)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1375)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:150)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5621)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)`

代码：
`playerStandard.setUp("http://jzvd.nathen.cn/342a5f7ef6124a4a8faf00e738b8bee4/cf6d9db0bd4d41f59d09ea0a81e918fd-5287d2089db37e62345123a1be272f8b.mp4"
                , "饺子快长大", JzvdStd.SCREEN_WINDOW_NORMAL);`

**Comment by lipangit** [comment]
这个函数好像删除了，我看库里没地方用到。。  你可以参考旧版把这个函数的内容考出来，一样可以用

**Comment by cdcdec** [comment]
感觉这样新旧版更换  对使用者是个大问题呀
