### ISSUE TITLE
OOM异常

### ISSUE THREAD

**Issue by youarenowhere** [lipangit/JiaoZiVideoPlayer#2098]
**什么jzvd版本
6.2.12
**是否和安卓版本有关系，什么版本

**是否和特定品牌的手机机型有关系，什么机型
魅族note6
**相关log是什么
java.lang.OutOfMemoryError: Failed to allocate a 291612 byte allocation with 36104 free bytes and 35KB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:620)
	at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:455)
	at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1155)
	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:749)
	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:597)
	at android.content.res.Resources.loadDrawable(Resources.java:885)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:928)
	at android.graphics.drawable.StateListDrawable.inflateChildElements(StateListDrawable.java:171)
	at android.graphics.drawable.StateListDrawable.inflate(StateListDrawable.java:116)
	at android.graphics.drawable.DrawableInflater.inflateFromXml(DrawableInflater.java:130)
	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1227)
	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1200)
	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:741)
	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:597)
	at android.content.res.Resources.getDrawable(Resources.java:798)
	at android.content.Context.getDrawable(Context.java:530)
	at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:358)
	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:198)
	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:186)
	at android.support.v7.content.res.AppCompatResources.getDrawable(AppCompatResources.java:100)
	at android.support.v7.widget.AppCompatImageHelper.setImageResource(AppCompatImageHelper.java:85)
	at android.support.v7.widget.AppCompatImageView.setImageResource(AppCompatImageView.java:93)
	at cn.jzvd.JZVideoPlayerStandard.updateStartImage(JZVideoPlayerStandard.java:662)
	at cn.jzvd.JZVideoPlayerStandard.changeUiToNormal(JZVideoPlayerStandard.java:498)
	at cn.jzvd.JZVideoPlayerStandard.onStateNormal(JZVideoPlayerStandard.java:174)
	at cn.jzvd.JZVideoPlayer.onCompletion(JZVideoPlayer.java:769)
	at cn.jzvd.JZVideoPlayerStandard.onCompletion(JZVideoPlayerStandard.java:806)
	at cn.jzvd.JZVideoPlayerManager.completeAll(JZVideoPlayerManager.java:42)
	at cn.jzvd.JZVideoPlayer.releaseAllVideos(JZVideoPlayer.java:144)
	at vip.meilianhui.ui.publish.activity.VideoActivity.onPause(VideoActivity.java:92)
	at android.app.Activity.performPause(Activity.java:6947)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1331)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3926)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3903)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3877)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3851)
	at android.app.ActivityThread.-wrap16(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1605)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6321)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:939)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:829)
**复现流程

**最好有截图或者视频说明情况

**Comment by youarenowhere** [comment]
貌似好几个人都是这块OOM
at android.support.v7.widget.AppCompatImageView.setImageResource(AppCompatImageView.java:93)
### _at cn.jzvd.JZVideoPlayerStandard.updateStartImage(JZVideoPlayerStandard.java:662)_
at cn.jzvd.JZVideoPlayerStandard.changeUiToNormal(JZVideoPlayerStandard.java:498)
at cn.jzvd.JZVideoPlayerStandard.onStateNormal(JZVideoPlayerStandard.java:174)
at cn.jzvd.JZVideoPlayer.onCompletion(JZVideoPlayer.java:769)
at cn.jzvd.JZVideoPlayerStandard.onCompletion(JZVideoPlayerStandard.java:806)
at cn.jzvd.JZVideoPlayerManager.completeAll(JZVideoPlayerManager.java:42)
at cn.jzvd.JZVideoPlayer.releaseAllVideos(JZVideoPlayer.java:144)
at vip.meilianhui.ui.publish.activity.VideoActivity.onPause(VideoActivity.java:92)

**Comment by lipangit** [comment]
在releaseAllVideos的时候讲视频控件的开始按钮设置成了start的图像，导致oom，releaseAllVideos会频繁调用吗，本质上是这个问题，你有什么线索吗

**Comment by youarenowhere** [comment]
我这边是在一个详情页面加载了大量图片，然后点击视频，然后再关闭视频的时候OOM了（有时候是点击全屏OOM）。感觉和加载大量图也有问题。只不过最后一根稻草是releaseAllVideos了。。

**Comment by lipangit** [comment]
可以尝试切换图片加载库
