### ISSUE TITLE
生成SupportRequestManagerFragment,点击视频全屏时,会崩溃

### ISSUE THREAD

**Issue by wxyass** [lipangit/JiaoZiVideoPlayer#2103]
** 最新版本6.3.1

** 设备: 联想4.2.2 (在小米8.0上没问题)  

问题: 
仿写官方Demo 当在ActivityMain中的onCreate(...)方法中调用setUp(...)方法时,会在当前Activity栈中生成SupportRequestManagerFragment的这么个东西? 当点击视频全屏时,会崩溃
```java
@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_jiecao_main);

    // ...

    jzvdStd = (com.yass.jiecao.CustomView.MyJzvdStd) findViewById(R.id.videoplayer);
    jzvdStd.setUp(mp4url, "饺子快长大", JzvdStd.SCREEN_WINDOW_NORMAL);
    Glide.with(this).load(imgurl).into(jzvdStd.thumbImageView);
}
```

日志:  
```java
{devicemodel=Lenovo A3500-HV, 
 versioncode=84, 
 versionname=6.3.1, 
 androidversion=4.2.2, 
 sdkversion=17, 
 exceptionsdetail=java.lang.RuntimeException: Error during detachFromGLContext (see logcat for details)
	at android.graphics.SurfaceTexture.attachToGLContext(SurfaceTexture.java:237)
	at android.view.GLES20TextureLayer.setSurfaceTexture(GLES20TextureLayer.java:81)
	at android.view.HardwareRenderer$Gl20Renderer.setSurfaceTexture(HardwareRenderer.java:1576)
	at android.view.TextureView.getHardwareLayer(TextureView.java:393)
	at android.view.View.getDisplayList(View.java:12795)
	at android.view.View.getDisplayList(View.java:12876)
	at android.view.View.draw(View.java:13621)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3037)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2901)
	at android.view.View.getDisplayList(View.java:12827)
	at android.view.View.getDisplayList(View.java:12876)
	at android.view.View.draw(View.java:13621)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3037)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2901)
	at android.view.View.draw(View.java:13928)
	at android.view.View.getDisplayList(View.java:12832)
	at android.view.View.getDisplayList(View.java:12876)
	at android.view.View.draw(View.java:13621)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3037)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2901)
	at android.view.View.getDisplayList(View.java:12827)
	at android.view.View.getDisplayList(View.java:12876)
	at android.view.View.draw(View.java:13621)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3037)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2901)
	at android.view.View.draw(View.java:13928)
	at android.widget.FrameLayout.draw(FrameLayout.java:467)
	at android.view.View.getDisplayList(View.java:12832)
	at android.view.View.getDisplayList(View.java:12876)
	at android.view.View.draw(View.java:13621)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3037)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2901)
	at android.view.View.draw(View.java:13928)
	at android.support.v7.widget.ActionBarOverlayLayout.draw(ActionBarOverlayLayout.java:451)
	at android.view.View.getDisplayList(View.java:12832)
	at android.view.View.getDisplayList(View.java:12876)
	at android.view.View.draw(View.java:13621)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3037)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2901)
	at android.view.View.getDisplayList(View.java:12827)
	at android.view.View.getDisplayList(View.java:12876)
	at android.view.View.draw(View.java:13621)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3037)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2901)
	at android.view.View.getDisplayList(View.java:12827)
	at android.view.View.getDisplayList(View.java:12876)
	at android.view.View.draw(View.java:13621)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3037)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2901)
	at android.view.View.draw(View.java:13928)
	at android.widget.FrameLayout.draw(FrameLayout.java:467)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2228)
	at android.view.View.getDisplayList(View.java:12832)
	at android.view.View.getDisplayList(View.java:12876)
	at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1249)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2520)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2387)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2189)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1181)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4942)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:776)
	at android.view.Choreographer.doCallbacks(Choreographer.java:579)
	at android.view.Choreographer.doFrame(Choreographer.java:548)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:762)
	at android.os.Handler.handleCallback(Handler.java:800)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5370)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
	at dalvik.system.NativeStart.main(Native Method)
}
```

**Comment by lipangit** [comment]
SupportRequestManagerFragment不知道这是什么东西

com.yass.jiecao.CustomView.MyJzvdStd 这里面是怎么写的

目测log是textureView的问题，是点击开始播放之后崩溃的吧
