### ISSUE TITLE
OOM

### ISSUE THREAD

**Issue by mytaihong** [lipangit/JiaoZiVideoPlayer#2128]
java.lang.OutOfMemoryError: Failed to allocate a 120 byte allocation with 48 free bytes and 48B until OOM
        at dalvik.system.VMStack.getThreadStackTrace(Native Method)
        at java.lang.Thread.getStackTrace(Thread.java:580)
        at android.os.Debug.getCallers(Debug.java:1675)
        at android.widget.ProgressBar.setSecondaryProgress(ProgressBar.java:1352)
        at cn.jzvd.Jzvd.setBufferProgress(Jzvd.java:905)
        at com.wyt.download.video.VideoJzvdStd.setBufferProgress(VideoJzvdStd.java:504)
        at com.wyt.download.video.JZExoPlayer$onBufferingUpdate$1.run(JZExoPlayer.java:131)
播放在线视频偶尔出现

**Comment by lipangit** [comment]
这种还需要仔细研究，根据log显示，在设置progress的进度时oom，很奇怪。

**Comment by mytaihong** [comment]
VideoJzvdStd和JZExoPlayer都是原封不动复制过来的    郁闷了不知道哪里错了

**Comment by lipangit** [comment]
兄弟试下新版本
