### ISSUE TITLE
java.lang.NullPointerException: Attempt to read from field 'java.util.LinkedHashMap

### ISSUE THREAD

**Issue by ausboyue** [lipangit/JiaoZiVideoPlayer#2131]
**什么jzvd版本
6.3.1

**是否和安卓版本有关系，什么版本
没有

**是否和特定品牌的手机机型有关系，什么机型
没有

**相关log是什么
   java.lang.NullPointerException: Attempt to read from field 'java.util.LinkedHashMap cn.jzvd.JZDataSource.urlsMap' on a null object reference
        at cn.jzvd.JzvdStd.onClick(JzvdStd.java:333)
        at android.view.View.performClick(View.java:6367)
        at android.view.View$PerformClick.run(View.java:25032)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6753)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**复现流程
点击播放按钮快速关闭Activity，快速再次打开该Activity再次点击播放按钮，容易出现

**最好有截图或者视频说明情况
没有，直接闪退了，报空指针异常

**Comment by ausboyue** [comment]
不是这段代码，是下面这段：
```java
          if (jzDataSource.urlsMap.isEmpty() || jzDataSource.getCurrentUrl() == null) {
                Toast.makeText(getContext(), getResources().getString(R.string.no_url), Toast.LENGTH_SHORT).show();
                return;
            }
```

"urlsMap"为null，所以调用isEmpty()方法会引起空指针异常。

**Comment by lipangit** [comment]
demo会有这个问题吗，jzDataSource为空说明没setUp
