### ISSUE TITLE
long tv.danmaku.ijk.media.player.IjkMediaPlayer.getDuration()' on a null object reference

### ISSUE THREAD

**Issue by y2653904** [lipangit/JiaoZiVideoPlayer#2153]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'long tv.danmaku.ijk.media.player.IjkMediaPlayer.getDuration()' on a null object reference
        at com.yarward.widget.videoplayer.JZMediaIjkplayer.getDuration(JZMediaIjkplayer.java:89)
        at com.yarward.widget.videoplayer.jzplayer.JZMediaManager.getDuration(JZMediaManager.java:79)
        at com.yarward.widget.videoplayer.jzplayer.JZVideoPlayer.getDuration(JZVideoPlayer.java:933)
        at com.yarward.widget.videoplayer.jzplayer.JZVideoPlayer.onProgressChanged(JZVideoPlayer.java:979)
        at android.widget.SeekBar.onProgressRefresh(SeekBar.java:95)
        at android.widget.ProgressBar.doRefreshProgress(ProgressBar.java:1262)
        at android.widget.ProgressBar.refreshProgress(ProgressBar.java:1274)
        at android.widget.ProgressBar.setProgress(ProgressBar.java:1321)
        at android.widget.AbsSeekBar.trackTouchEvent(AbsSeekBar.java:661)
        at android.widget.AbsSeekBar.onTouchEvent(AbsSeekBar.java:605)
        at android.view.View.dispatchTouchEvent(View.java:8515)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
    	at android.view.ViewGroup.dispatchTransformedTouchEvent(
报这个错误是什么原因呢？

**Comment by lipangit** [comment]
从log看是不是IjkMediaPlayer为空，你都做了哪些修改

**Comment by windfone** [comment]
是ijkMediaplayer 为空，我也遇到这个问题了，7.0.5版本。视频播放完毕后崩溃，按demo上写的，没做修改@lipangit

**Comment by lipangit** [comment]
已经解决
