### ISSUE TITLE
项目运行崩溃

### ISSUE THREAD

**Issue by yyhyplxyz** [lipangit/JiaoZiVideoPlayer#2179]
##什么jzvd版本
6.3.1

##是否和安卓版本有关系，什么版本
compileSdkVersion 28  targetSdkVersion 28

##是否和特定品牌的手机机型有关系，什么机型
Android Studio模拟运行

##相关log是什么
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.example.yangyuanhao.myapplication, PID: 17812
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.yangyuanhao.myapplication/com.example.yangyuanhao.myapplication.MainActivity}: android.view.InflateException: Binary XML file line #228: Binary XML file line #228: Error inflating class cn.jzvd.JZVideoPlayerStandard
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
                      at android.app.ActivityThread.-wrap11(Unknown Source:0)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
                      at android.os.Handler.dispatchMessage(Handler.java:106)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6494)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                   Caused by: android.view.InflateException: Binary XML file line #228: Binary XML file line #228: Error inflating class cn.jzvd.JZVideoPlayerStandard
                   Caused by: android.view.InflateException: Binary XML file line #228: Error inflating class cn.jzvd.JZVideoPlayerStandard
                   Caused by: java.lang.ClassNotFoundException: Didn't find class "cn.jzvd.JZVideoPlayerStandard" on path: DexPathList[[zip file "/data/app/com.example.yangyuanhao.myapplication-UUdMsL-T-pt-WhvdUPQbVQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.yangyuanhao.myapplication-UUdMsL-T-pt-WhvdUPQbVQ==/lib/x86, /data/app/com.example.yangyuanhao.myapplication-UUdMsL-T-pt-WhvdUPQbVQ==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                      at android.view.LayoutInflater.createView(LayoutInflater.java:606)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                      at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                      at com.example.yangyuanhao.myapplication.MainActivity.onCreate(MainActivity.java:121)
                      at android.app.Activity.performCreate(Activity.java:7009)
                      at android.app.Activity.performCreate(Activity.java:7000)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
                      at android.app.ActivityThread.-wrap11(Unknown Source:0)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
                      at android.os.Handler.dispatchMessage(Handler.java:106)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6494)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
##复现流程
按照readme设置好后一运行项目就崩溃，当把所有跟jzvd有关的代码注释掉后正常运行

##最好有截图或者视频说明情况
因为代码并不复杂，将mainactivity代码贴出，如果是我用错了jzvd的话，谢谢指出，抱歉打扰
`package com.example.yangyuanhao.myapplication;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.os.Bundle;
import android.support.annotation.NonNull;
import android.support.design.widget.BottomNavigationView;
import android.support.v7.app.AppCompatActivity;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.widget.ImageView;
import android.widget.TextView;
import android.widget.Toast;
import com.bumptech.glide.Glide;
import com.donkingliang.banner.CustomBanner;
import com.squareup.picasso.Picasso;
import java.util.ArrayList;
import cn.jzvd.Jzvd;
import cn.jzvd.JzvdStd;

public class MainActivity extends AppCompatActivity   {

    private TextView mTextMessage;
    private CustomBanner<String> mBanner;
    FullPhotoView photoView ;
    JzvdStd jzvdStd;
    private BottomNavigationView.OnNavigationItemSelectedListener mOnNavigationItemSelectedListener
            = new BottomNavigationView.OnNavigationItemSelectedListener() {

        @Override
        public boolean onNavigationItemSelected(@NonNull MenuItem item) {
            switch (item.getItemId()) {
                case R.id.navigation_home:
                    mTextMessage.setText(R.string.title_home);
                    return true;
                case R.id.navigation_dashboard:
                    mTextMessage.setText(R.string.title_dashboard);
                    return true;
                case R.id.navigation_notifications:
                    mTextMessage.setText(R.string.title_notifications);
                    return true;
            }
            return false;
        }
    };

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        getMenuInflater().inflate(R.menu.detail_menu,menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {

        switch (item.getItemId()){
            case R.id.share:
                Toast.makeText(this, "分享", Toast.LENGTH_SHORT).show();
                break;
            default:
                break;
        }

        return true;
    }

    private void setBanner()
    {
        mBanner = (CustomBanner) findViewById(R.id.banner);
        ArrayList<String> images = new ArrayList<>();
        images.add("https://ss1.bdstatic.com/70cFuXSh_Q1YnxGkpoWK1HF6hhy/it/u=3778456200,3076998411&fm=23&gp=0.jpg");
        images.add("https://ss0.bdstatic.com/70cFvHSh_Q1YnxGkpoWK1HF6hhy/it/u=3535338527,4000198595&fm=23&gp=0.jpg");
        images.add("https://ss3.bdstatic.com/70cFv8Sh_Q1YnxGkpoWK1HF6hhy/it/u=1017904219,2460650030&fm=23&gp=0.jpg");
        images.add("https://ss3.bdstatic.com/70cFv8Sh_Q1YnxGkpoWK1HF6hhy/it/u=2863927798,667335035&fm=23&gp=0.jpg");
        images.add("https://ss3.bdstatic.com/70cFv8Sh_Q1YnxGkpoWK1HF6hhy/it/u=3885596348,1190704919&fm=23&gp=0.jpg");
        images.add("https://ss0.bdstatic.com/70cFvHSh_Q1YnxGkpoWK1HF6hhy/it/u=1597254274,1405139366&fm=23&gp=0.jpg");
        images.add("https://ss1.bdstatic.com/70cFuXSh_Q1YnxGkpoWK1HF6hhy/it/u=3513269361,2662598514&fm=23&gp=0.jpg");
        setBean(images);
    }

    private void setVideo()
    {
        photoView = (FullPhotoView) findViewById(R.id.photo_view);
        photoView.setImageResource(R.drawable.zhugeliang);

        jzvdStd = findViewById(R.id.videoplayer);
        jzvdStd.setUp("http://jzvd.nathen.cn/c6e3dc12a1154626b3476d9bf3bd7266/6b56c5f0dc31428083757a45764763b0-5287d2089db37e62345123a1be272f8b.mp4"
                , "饺子闭眼睛" , Jzvd.SCREEN_WINDOW_NORMAL);
        Picasso.with(this)
                .load("http://jzvd-pic.nathen.cn/jzvd-pic/1bb2ebbe-140d-4e2e-abd2-9e7e564f71ac.png")
                .into(jzvdStd.thumbImageView);
    }

    @Override
    public void onBackPressed() {
        if (jzvdStd.backPress()) {
            return;
        }
        super.onBackPressed();
    }

    @Override
    protected void onPause() {
        super.onPause();
        jzvdStd.releaseAllVideos();
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
//        setContentView(R.layout.activity_main);
//        setBanner();
        HeroInfo minfo = new HeroInfo(this);
        SQLiteDatabase db = minfo.mydb.getWritableDatabase();
        setContentView(R.layout.detail);
        setVideo();
       // mAdsdkContext = new VideoAdContext(this, new Gson().tojson(),null);
        //setContentView(R.layout.edit);
        //setContentView(R.layout.edit2);
        //mTextMessage = (TextView) findViewById(R.id.message);
        //BottomNavigationView navigation = (BottomNavigationView) findViewById(R.id.navigation);
        //navigation.setOnNavigationItemSelectedListener(mOnNavigationItemSelectedListener);
    }

    private void setBean(final ArrayList<String> beans) {
        mBanner.setPages(new CustomBanner.ViewCreator<String>() {
            @Override
            public View createView(Context context, int position) {
                ImageView imageView = new ImageView(context);
                imageView.setScaleType(ImageView.ScaleType.FIT_XY);
                return imageView;
            }

            @Override
            public void updateUI(Context context, View view, int position, String entity) {
                Glide.with(context).load(entity).into((ImageView) view);
            }
        }, beans)  .startTurning(5000);
    }

}
`

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/48598988-b70e3180-e9a0-11e8-8274-825baa4658f3.png)


目测应该是xml文件的控件和代码中的控件不一致，建议使用最新版本，重新引入

**Comment by faith-hb** [comment]
我也遇到同样的问题，最新版本7.3.0

android.view.InflateException: Binary XML file line #6: Binary XML file line #6: Error inflating class cn.jzvd.JzvdStd
    Caused by: android.view.InflateException: Binary XML file line #6: Error inflating class cn.jzvd.JzvdStd
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
        at android.view.LayoutInflater.createView(LayoutInflater.java:645)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:694)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:160)
        at com.abm.material.ui.activity.PlayerActivity.onCreate(PlayerActivity.java:54)
        at android.app.Activity.performCreate(Activity.java:6813)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
        at com.qiyukf.unicorn.i.a.callActivityOnCreate(Unknown Source)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2805)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2927)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:159)
        at android.app.ActivityThread.main(ActivityThread.java:6364)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)
     Caused by: java.lang.NoSuchFieldError: No field poster of type I in class Lcn/jzvd/R$id; or its superclasses (declaration of 'cn.jzvd.R$id' appears in /data/app/com.dt.abm-2/base.apk:classes2.dex)
        at cn.jzvd.JzvdStd.init(JzvdStd.java:123)
        at cn.jzvd.Jzvd.<init>(Jzvd.java:139)
        at cn.jzvd.JzvdStd.<init>(JzvdStd.java:113)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:645) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:858) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:518) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:377) 
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:694) 
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:160) 
        at com.abm.material.ui.activity.PlayerActivity.onCreate(PlayerActivity.java:54) 
        at android.app.Activity.performCreate(Activity.java:6813) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119) 
        at com.qiyukf.unicorn.i.a.callActivityOnCreate(Unknown Source) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2805) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2927) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:159) 
        at android.app.ActivityThread.main(ActivityThread.java:6364) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883) 
2020-05-07 10:44:31.855 18116-18116/com.dt.abm E/APP: 1/************* crash *************
    ** Thread: com.dt.abm/main **
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dt.abm/com.abm.material.ui.activity.PlayerActivity}: android.view.InflateException: Binary XML file line #6: Binary XML file line #6: Error inflating class cn.jzvd.JzvdStd
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2865)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2927)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:159)
        at android.app.ActivityThread.main(ActivityThread.java:6364)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)
     Caused by: android.view.InflateException: Binary XML file line #6: Binary XML file line #6: Error inflating class cn.jzvd.JzvdStd
     Caused by: android.view.InflateException: Binary XML file line #6: Error inflating class cn.jzvd.JzvdStd
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
        at android.view.LayoutInflater.createView(LayoutInflater.java:645)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:694)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:160)
        at com.abm.material.ui.activity.PlayerActivity.onCreate(PlayerActivity.java:54)
        at android.app.Activity.performCreate(Activity.java:6813)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
        at com.qiyukf.unicorn.i.a.callActivityOnCreate(Unknown Source)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2805)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2927)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:159)
        at android.app.ActivityThread.main(ActivityThread.java:6364)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)
     Caused by: java.lang.NoSuchFieldError: No field poster of type I in class Lcn/jzvd/R$id; or its superclasses (declaration of 'cn.jzvd.R$id' appears in /data/app/com.dt.abm-2/base.apk:classes2.dex)
        at cn.jzvd.JzvdStd.init(JzvdStd.java:123)
        at cn.jzvd.Jzvd.<init>(Jzvd.java:139)
        at cn.jzvd.JzvdStd.<init>(JzvdStd.java:113)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:645) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:858) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:518) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:377) 
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:694) 
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:160) 
        at com.abm.material.ui.activity.PlayerActivity.onCreate(PlayerActivity.java:54) 
        at android.app.Activity.performCreate(Activity.java:6813) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119) 
        at com.qiyukf.unicorn.i.a.callActivityOnCreate(Unknown Source) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2805) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2927) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:159) 
        at android.app.ActivityThread.main(ActivityThread.java:6364) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)

**Comment by lipangit** [comment]
没找到重点log保持关注



---原始邮件---
发件人: "hongbing"<notifications@github.com&gt;
发送时间: 2020年5月7日(周四) 中午11:00
收件人: "lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [lipangit/JiaoZiVideoPlayer] 项目运行崩溃 (#2179)




 
我也遇到同样的问题，最新版本7.3.0
 
android.view.InflateException: Binary XML file line #6: Binary XML file line #6: Error inflating class cn.jzvd.JzvdStd
 Caused by: android.view.InflateException: Binary XML file line #6: Error inflating class cn.jzvd.JzvdStd
 Caused by: java.lang.reflect.InvocationTargetException
 at java.lang.reflect.Constructor.newInstance0(Native Method)
 at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
 at android.view.LayoutInflater.createView(LayoutInflater.java:645)
 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
 at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
 at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
 at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
 at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
 at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:694)
 at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:160)
 at com.abm.material.ui.activity.PlayerActivity.onCreate(PlayerActivity.java:54)
 at android.app.Activity.performCreate(Activity.java:6813)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
 at com.qiyukf.unicorn.i.a.callActivityOnCreate(Unknown Source)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2805)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2927)
 at android.app.ActivityThread.-wrap12(ActivityThread.java)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loop(Looper.java:159)
 at android.app.ActivityThread.main(ActivityThread.java:6364)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)
 Caused by: java.lang.NoSuchFieldError: No field poster of type I in class Lcn/jzvd/R$id; or its superclasses (declaration of 'cn.jzvd.R$id' appears in /data/app/com.dt.abm-2/base.apk:classes2.dex)
 at cn.jzvd.JzvdStd.init(JzvdStd.java:123)
 at cn.jzvd.Jzvd.(Jzvd.java:139)
 at cn.jzvd.JzvdStd.(JzvdStd.java:113)
 at java.lang.reflect.Constructor.newInstance0(Native Method)&nbsp;
 at java.lang.reflect.Constructor.newInstance(Constructor.java:430)&nbsp;
 at android.view.LayoutInflater.createView(LayoutInflater.java:645)&nbsp;
 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)&nbsp;
 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)&nbsp;
 at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)&nbsp;
 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)&nbsp;
 at android.view.LayoutInflater.inflate(LayoutInflater.java:518)&nbsp;
 at android.view.LayoutInflater.inflate(LayoutInflater.java:426)&nbsp;
 at android.view.LayoutInflater.inflate(LayoutInflater.java:377)&nbsp;
 at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:694)&nbsp;
 at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:160)&nbsp;
 at com.abm.material.ui.activity.PlayerActivity.onCreate(PlayerActivity.java:54)&nbsp;
 at android.app.Activity.performCreate(Activity.java:6813)&nbsp;
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)&nbsp;
 at com.qiyukf.unicorn.i.a.callActivityOnCreate(Unknown Source)&nbsp;
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2805)&nbsp;
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2927)&nbsp;
 at android.app.ActivityThread.-wrap12(ActivityThread.java)&nbsp;
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)&nbsp;
 at android.os.Handler.dispatchMessage(Handler.java:102)&nbsp;
 at android.os.Looper.loop(Looper.java:159)&nbsp;
 at android.app.ActivityThread.main(ActivityThread.java:6364)&nbsp;
 at java.lang.reflect.Method.invoke(Native Method)&nbsp;
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096)&nbsp;
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)&nbsp;
 2020-05-07 10:44:31.855 18116-18116/com.dt.abm E/APP: 1/************* crash *************
 ** Thread: com.dt.abm/main **
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dt.abm/com.abm.material.ui.activity.PlayerActivity}: android.view.InflateException: Binary XML file line #6: Binary XML file line #6: Error inflating class cn.jzvd.JzvdStd
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2865)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2927)
 at android.app.ActivityThread.-wrap12(ActivityThread.java)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loop(Looper.java:159)
 at android.app.ActivityThread.main(ActivityThread.java:6364)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)
 Caused by: android.view.InflateException: Binary XML file line #6: Binary XML file line #6: Error inflating class cn.jzvd.JzvdStd
 Caused by: android.view.InflateException: Binary XML file line #6: Error inflating class cn.jzvd.JzvdStd
 Caused by: java.lang.reflect.InvocationTargetException
 at java.lang.reflect.Constructor.newInstance0(Native Method)
 at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
 at android.view.LayoutInflater.createView(LayoutInflater.java:645)
 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
 at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
 at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
 at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
 at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
 at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:694)
 at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:160)
 at com.abm.material.ui.activity.PlayerActivity.onCreate(PlayerActivity.java:54)
 at android.app.Activity.performCreate(Activity.java:6813)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
 at com.qiyukf.unicorn.i.a.callActivityOnCreate(Unknown Source)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2805)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2927)
 at android.app.ActivityThread.-wrap12(ActivityThread.java)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loop(Looper.java:159)
 at android.app.ActivityThread.main(ActivityThread.java:6364)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)
 Caused by: java.lang.NoSuchFieldError: No field poster of type I in class Lcn/jzvd/R$id; or its superclasses (declaration of 'cn.jzvd.R$id' appears in /data/app/com.dt.abm-2/base.apk:classes2.dex)
 at cn.jzvd.JzvdStd.init(JzvdStd.java:123)
 at cn.jzvd.Jzvd.(Jzvd.java:139)
 at cn.jzvd.JzvdStd.(JzvdStd.java:113)
 at java.lang.reflect.Constructor.newInstance0(Native Method)&nbsp;
 at java.lang.reflect.Constructor.newInstance(Constructor.java:430)&nbsp;
 at android.view.LayoutInflater.createView(LayoutInflater.java:645)&nbsp;
 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)&nbsp;
 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)&nbsp;
 at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)&nbsp;
 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)&nbsp;
 at android.view.LayoutInflater.inflate(LayoutInflater.java:518)&nbsp;
 at android.view.LayoutInflater.inflate(LayoutInflater.java:426)&nbsp;
 at android.view.LayoutInflater.inflate(LayoutInflater.java:377)&nbsp;
 at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:694)&nbsp;
 at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:160)&nbsp;
 at com.abm.material.ui.activity.PlayerActivity.onCreate(PlayerActivity.java:54)&nbsp;
 at android.app.Activity.performCreate(Activity.java:6813)&nbsp;
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)&nbsp;
 at com.qiyukf.unicorn.i.a.callActivityOnCreate(Unknown Source)&nbsp;
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2805)&nbsp;
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2927)&nbsp;
 at android.app.ActivityThread.-wrap12(ActivityThread.java)&nbsp;
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)&nbsp;
 at android.os.Handler.dispatchMessage(Handler.java:102)&nbsp;
 at android.os.Looper.loop(Looper.java:159)&nbsp;
 at android.app.ActivityThread.main(ActivityThread.java:6364)&nbsp;
 at java.lang.reflect.Method.invoke(Native Method)&nbsp;
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096)&nbsp;
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)&nbsp;
