### ISSUE TITLE
实现小视频上下翻动切换功能

### ISSUE THREAD

**Issue by lrain-lv** [lipangit/JiaoZiVideoPlayer#2210]
**需求描述
实现小视频上下翻动切换功能
**其他app是否实现
抖音、懂球帝
**截图或者小视频说明
@Override
    public void onInitComplete() {
        Logger.e("-------onInitComplete");
        if (mActivity != null && !mActivity.isFinishing()) {
            playVideo(0);
        }
    }

    @Override
    public void onPageRelease(boolean isNext, int position) {
        Logger.e("-------onPageRelease" + position + isNext + "child" + mRecyclerView.getChildCount());
        int index = 0;
        if (isNext) {
            index = 0;
        } else {
            index = 1;
        }
        releaseVideo(index);
    }

    @Override
    public void onPageSelected(int position, boolean isBottom) {
        Logger.e("-------onPageSelected" + "选中位置:" + position + "  是否是滑动到底部:" + isBottom);
        playVideo(0);
    }

public void playVideo(int index) {
        if (mActivity != null && !mActivity.isFinishing()) {
            View itemView = mRecyclerView.getChildAt(index);
            DDCBVideoPlayer jzvd = itemView.findViewById(R.id.video_view);
            if (null != jzvd) {
                jzvd.startVideo();
            }
        }
    }

    public void releaseVideo(int index) {
        if (null != mActivity && !mActivity.isFinishing()) {
            View itemView = mRecyclerView.getChildAt(index);
            DDCBVideoPlayer jzvd = itemView.findViewById(R.id.video_view);
            if (jzvd != null && jzvd.jzDataSource.containsTheUrl(JZMediaManager.getCurrentUrl())) {
                Jzvd currentJzvd = JzvdMgr.getCurrentJzvd();
                if (currentJzvd != null && currentJzvd.currentScreen != DDCBVideoPlayer.SCREEN_WINDOW_FULLSCREEN) {
                    Jzvd.releaseAllVideos();
                }
            }
        }
    }

**Comment by lrain-lv** [comment]
当我使用mrec.scrollToPosition()的时候轻轻滑动一下 不切换item，就会报
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
        at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2589)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:887)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:664)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:166)
        at android.os.HandlerThread.run(HandlerThread.java:65)

 java.lang.IllegalStateException
        at android.media.MediaCodec.native_stop(Native Method)
        at android.media.MediaCodec.stop(MediaCodec.java:2087)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.releaseCodec(MediaCodecRenderer.java:608)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.releaseCodec(MediaCodecVideoRenderer.java:508)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:562)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:377)
        at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:153)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:983)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:771)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:742)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:358)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:166)
        at android.os.HandlerThread.run(HandlerThread.java:65)

我使用的引擎是google的那个

**Comment by lipangit** [comment]
兄弟，这样，把你当前的代码整理一下放到demo中，提交pr，加一个activity一个列表，你把主干做完，剩下的我来调试，正准备做这个功能呢。

**Comment by shenjiabing** [comment]
有这个demo吗？
