### ISSUE TITLE
视频从暂停变为继续播放时报错。

### ISSUE THREAD

**Issue by StevenNick88** [lipangit/JiaoZiVideoPlayer#2243]
**什么jzvd版本
6.2.10
**是否和安卓版本有关系，什么版本
没有，android7.0
**是否和特定品牌的手机机型有关系，什么机型
没有，tecno手机
**相关log是什么
2018-12-18-16-23-00==  ==  ==java.lang.RuntimeException: Unable to resume activity {com.afmobi.boomplayer/com.tecno.boomplayer.newUI.DetailVideoActivity}: java.lang.IllegalStateException
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3609)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3649)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1663)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6524)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:451)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:888)
Caused by: java.lang.IllegalStateException
	at android.media.MediaPlayer._start(Native Method)
	at android.media.MediaPlayer.startImpl(MediaPlayer.java:1358)
	at android.media.MediaPlayer.start(MediaPlayer.java:1332)
	at cn.jzvd.c.a(JZMediaSystem.java:23)
	at cn.jzvd.b.f(JZMediaManager.java:93)
	at cn.jzvd.JZVideoPlayer.d(JZVideoPlayer.java:268)
	at com.tecno.boomplayer.newUI.DetailVideoActivity.onResume(DetailVideoActivity.java:800)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1355)
	at android.app.Activity.performResume(Activity.java:7152)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3584)
	... 8 more
java.lang.IllegalStateException
	at android.media.MediaPlayer._start(Native Method)
	at android.media.MediaPlayer.startImpl(MediaPlayer.java:1358)
	at android.media.MediaPlayer.start(MediaPlayer.java:1332)
	at cn.jzvd.c.a(JZMediaSystem.java:23)
	at cn.jzvd.b.f(JZMediaManager.java:93)
	at cn.jzvd.JZVideoPlayer.d(JZVideoPlayer.java:268)
	at com.tecno.boomplayer.newUI.DetailVideoActivity.onResume(DetailVideoActivity.java:800)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1355)
	at android.app.Activity.performResume(Activity.java:7152)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3584)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3649)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1663)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6524)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:451)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:888)

**复现流程
跑monkey
**最好有截图或者视频说明情况

**Comment by lipangit** [comment]
跑monkey的时候你能看到界面吧，是不是有其他状态的干扰，还是单纯的在播放的过程中，频繁点开始按钮，暂停继续暂停继续暂停继续，就会闪退
