### ISSUE TITLE
播放完成后点击按钮导致的崩溃问题

### ISSUE THREAD

**Issue by jiapengtao** [lipangit/JiaoZiVideoPlayer#2245]
jzvd  6.4.1版本

在类似收银用的双面屏机器中测试，系统是5.1.1

崩溃日志：E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.videoplayerdemo, PID: 13738
    java.lang.NullPointerException: Attempt to read from field 'java.util.LinkedHashMap cn.jzvd.JZDataSource.urlsMap' on a null object reference
        at cn.jzvd.JzvdStd.onClick(JzvdStd.java:335)
        at com.example.videoplayerdemo.MyJzvdStd.onClick(MyJzvdStd.java:31)
        at android.view.View.performClick(View.java:4809)
        at android.view.View$PerformClick.run(View.java:20006)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5280)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)

复现流程：
1，在antivity中直接使用全屏播放API播放视频，代码如下
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        MyJzvdStd.startFullscreen(this, MyJzvdStd.class,
                "http://jzvd.nathen.cn/342a5f7ef6124a4a8faf00e738b8bee4/cf6d9db0bd4d41f59d09ea0a81e918fd-5287d2089db37e62345123a1be272f8b.mp4", "饺子");
    }

2，编译运行后等待视频播放完毕，然后在屏幕中央出现的按钮处点击一下，就会出现应用崩溃退出问题，概率为90%以上，基本会崩。

**Comment by jiapengtao** [comment]
我就是用Demo播放的，然后把Demo的代码删掉后改成上述第一步中的代码，这样在播放完后就会出现一个尖头朝右的三角图标，当你点击图标时应用就会崩溃退出，你可以复现试试

**Comment by lipangit** [comment]
这个和全屏没有关系，MyJzvdStd.startFullscreen(this, MyJzvdStd.class,  和这行代码没有关系

因为在MainActivity中，本来的布局里有一个jzvd，旧版本在没有setup的时候点击开始按钮会崩溃，你现在升级新版会解决这个问题
