### ISSUE TITLE
在 recycleview 中 点击第一个视频全屏时 崩溃

### ISSUE THREAD

**Issue by hyl87** [lipangit/JiaoZiVideoPlayer#2247]
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:275)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20715)
        at android.view.ViewGroup.layout(ViewGroup.java:6200)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:20715)
        at android.view.ViewGroup.layout(ViewGroup.java:6200)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20715)
        at android.view.ViewGroup.layout(ViewGroup.java:6200)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:20715)
        at android.view.ViewGroup.layout(ViewGroup.java:6200)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:903)
        at android.view.View.layout(View.java:20715)
        at android.view.ViewGroup.layout(ViewGroup.java:6200)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2802)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2329)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1469)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7209)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1016)
        at android.view.Choreographer.doCallbacks(Choreographer.java:828)
        at android.view.Choreographer.doFrame(Choreographer.java:763)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1002)
        at android.os.Handler.handleCallback(Handler.java:874)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:198)
        at android.app.ActivityThread.main(ActivityThread.java:6729)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by lipangit** [comment]
是在没有任何播放的情况下点第一个崩溃吗，demo 有这问题吗
