### ISSUE TITLE
full screen issue

### ISSUE THREAD

**Issue by cpappzoro** [lipangit/JiaoZiVideoPlayer#2281]
when proguard rule enable now my video cannot play in full screen

**Comment by lipangit** [comment]
what log

**Comment by cpappzoro** [comment]
> 
> 
> what log

2019-01-25 18:29:34.490 4934-4934/com.appzoro.videoplayer W/System.err: java.lang.NoSuchMethodException: <init> [class android.content.Context]
2019-01-25 18:29:34.490 4934-4934/com.appzoro.videoplayer W/System.err:     at java.lang.Class.getConstructor0(Class.java:2320)
2019-01-25 18:29:34.490 4934-4934/com.appzoro.videoplayer W/System.err:     at java.lang.Class.getConstructor(Class.java:1725)
2019-01-25 18:29:34.490 4934-4934/com.appzoro.videoplayer W/System.err:     at cn.jzvd.h.x(Unknown Source:85)
2019-01-25 18:29:34.491 4934-4934/com.appzoro.videoplayer W/System.err:     at cn.jzvd.h.onClick(Unknown Source:304)
2019-01-25 18:29:34.491 4934-4934/com.appzoro.videoplayer W/System.err:     at cn.jzvd.JzvdStd.onClick(Unknown Source:0)
2019-01-25 18:29:34.491 4934-4934/com.appzoro.videoplayer W/System.err:     at android.view.View.performClick(View.java:6909)
2019-01-25 18:29:34.491 4934-4934/com.appzoro.videoplayer W/System.err:     at android.view.View$PerformClick.run(View.java:26199)
2019-01-25 18:29:34.491 4934-4934/com.appzoro.videoplayer W/System.err:     at android.os.Handler.handleCallback(Handler.java:789)
2019-01-25 18:29:34.491 4934-4934/com.appzoro.videoplayer W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
2019-01-25 18:29:34.491 4934-4934/com.appzoro.videoplayer W/System.err:     at android.os.Looper.loop(Looper.java:164)
2019-01-25 18:29:34.491 4934-4934/com.appzoro.videoplayer W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6944)
2019-01-25 18:29:34.492 4934-4934/com.appzoro.videoplayer W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-01-25 18:29:34.492 4934-4934/com.appzoro.videoplayer W/System.err:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
2019-01-25 18:29:34.492 4934-4934/com.appzoro.videoplayer W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by lipangit** [comment]
https://github.com/lipangit/JiaoZiVideoPlayer/issues/2273   试试这个

**Comment by cpappzoro** [comment]
show errors after added proguard rule  according to #2273 

Exception while processing task java.io.IOException: proguard.ParseException:
Expecting java type before '(' in line 22 of file 'E:\Get Sound\player_recycler\JiaoZiVideoPlayer-develop\JiaoZiVideoPlayer-develop\app\proguard-rules.pro'
