### ISSUE TITLE
关于startWindowTiny小窗口

### ISSUE THREAD

**Issue by Scorption** [lipangit/JiaoZiVideoPlayer#2333]
**什么jzvd版本   6.4.1

**是否和安卓版本有关系，什么版本  无 android 8.0

**是否和特定品牌的手机机型有关系，什么机型 小米8

**相关log是什么 
 java.lang.NullPointerException: Attempt to read from field 'int android.view.View.mViewFlags' on a null object reference
                                                                     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4293)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:19096)
                                                                     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
                                                                     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:19096)
                                                                     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
                                                                     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:19096)
                                                                     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
                                                                     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:19096)
                                                                     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
                                                                     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:19096)
                                                                     at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
                                                                     at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
                                                                     at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:801)
                                                                     at android.view.ViewRootImpl.draw(ViewRootImpl.java:3406)
                                                                     at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3179)
                                                                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2548)
                                                                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1523)
                                                                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7395)
                                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1065)
                                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:877)
                                                                     at android.view.Choreographer.doFrame(Choreographer.java:808)
                                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1051)
                                                                     at android.os.Handler.handleCallback(Handler.java:873)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                     at android.os.Looper.loop(Looper.java:201)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6806)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**复现流程
  JzvdMgr.getCurrentJzvd().startWindowTiny() 启动小窗口之后，调用
 JzvdMgr.getFirstFloor().playOnThisJzvd();或Jzvd.backpress()，于 CollapsingToolbarLayout折叠-展开状态关闭小窗， 
缓慢滑动没有问题，当快速滑动时才会出现这个闪退，源码中try了NullPointerException但还是闪退

**最好有截图或者视频说明情况

**Comment by lipangit** [comment]
列表setUp是怎么设置的，什么时候调用的startWindowTiny

**Comment by Scorption** [comment]
> 列表的setUp是怎么设置的，什么时候调用的startWindowTiny

     jzvdStd.setUp(proxyUrl
                    , "", Jzvd.SCREEN_WINDOW_NORMAL);
            GlideHelper.load(context, (String) path, jzvdStd.thumbImageView);
 在CollapsingToolbarLayout折叠的时候startWindowTiny，展开的时候关闭windowtiny。

**Comment by lipangit** [comment]
现在折叠之后进入小窗是正常的对吧，然后你先展开，等展开完全的时候，通过点击其他按钮关闭小窗。
这么做的目的就是排除展开折叠对小窗的影响。
