### ISSUE TITLE
Activity 中recyclerview 视频列表，正在播放视频时，上下滚动报空指针

### ISSUE THREAD

**Issue by WangHongTaoAH** [lipangit/JiaoZiVideoPlayer#2347]

**Comment by WangHongTaoAH** [comment]
以下是我写的相关代码：
recyclerView.addOnChildAttachStateChangeListener(new RecyclerView.OnChildAttachStateChangeListener() {
            @Override
            public void onChildViewAttachedToWindow(View view) {

            }

            @Override
            public void onChildViewDetachedFromWindow(View view) {
                Jzvd jzvd = view.findViewById(R.id.my_video);
                if (jzvd != null && JzvdMgr.getCurrentJzvd() != null && jzvd.jzDataSource.containsTheUrl(JzvdMgr.getCurrentJzvd().jzDataSource.getCurrentUrl())) {
                    if (JzvdMgr.getCurrentJzvd() != null && JzvdMgr.getCurrentJzvd().currentScreen != Jzvd.SCREEN_WINDOW_FULLSCREEN) {
                        Jzvd.releaseAllVideos();
                    }
                }
            }
        });

报错log如下：
java.lang.NullPointerException: Attempt to invoke virtual method 'long tv.danmaku.ijk.media.player.IjkMediaPlayer.getCurrentPosition()' on a null object reference
        at com.gaodun.cpa.utils.JZMediaIjkplayer.getCurrentPosition(JZMediaIjkplayer.java:82)
        at cn.jzvd.JZMediaManager.getCurrentPosition(JZMediaManager.java:71)
        at cn.jzvd.Jzvd.getCurrentPositionWhenPlaying(Jzvd.java:930)
        at cn.jzvd.Jzvd$ProgressTimerTask$1.run(Jzvd.java:1183)
        at android.os.Handler.handleCallback(Handler.java:808)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7529)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by WangHongTaoAH** [comment]
> _No description provided._
