### ISSUE TITLE
mp4

### ISSUE THREAD

**Issue by cuijigang** [lipangit/JiaoZiVideoPlayer#2367]

**Comment by cuijigang** [comment]
http://mu.eveln.com/730buluo/dynamicFile/video/2019-04-01/9fa21aff476f3d12952d58c663a71f0f.mp4这个视频不能播放      
 E/LoadTask: Unexpected exception loading stream
    java.lang.IllegalArgumentException
        at com.google.android.exoplayer2.util.Assertions.checkArgument(Assertions.java:37)
        at com.google.android.exoplayer2.util.ParsableByteArray.setPosition(ParsableByteArray.java:146)
        at com.google.android.exoplayer2.util.ParsableByteArray.skipBytes(ParsableByteArray.java:158)
        at com.google.android.exoplayer2.video.AvcConfig.parse(AvcConfig.java:48)
        at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseVideoSampleEntry(AtomParsers.java:748)
        at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseStsd(AtomParsers.java:640)
        at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseTrak(AtomParsers.java:90)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:400)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:364)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:355)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:186)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:853)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

**Comment by lipangit** [comment]
不清楚这log的含义，请到exoplay项目中提问
