### ISSUE TITLE
recyclerview Item点击播放报错

### ISSUE THREAD

**Issue by SunshineCui** [lipangit/JiaoZiVideoPlayer#2382]
**什么jzvd版本
7.0_preview
**相关log是什么
`java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Window android.app.Activity.getWindow()' on a null object reference
        at cn.jzvd.Jzvd.startVideo(Jzvd.java:491)
        at cn.jzvd.Jzvd.onClick(Jzvd.java:343)
        at cn.jzvd.JzvdStd.onClick(JzvdStd.java:284)
        at android.view.View.performClick(View.java:6257)
        at android.view.View$PerformClick.run(View.java:23705)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6780)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1500)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1390)`

**Comment by SunshineCui** [comment]
错误出在 列表adapter  初始化item布局时LayoutInflater.from(activity)  ,初始化LayoutInflater 参数用activity,上下文不要使用全局的或者getSystemService(LAYOUT_INFLATER_SERVICE)

**Comment by lipangit** [comment]
ok
