### ISSUE TITLE
嵌入到fragment中的recyclerview，运行直接报错

### ISSUE THREAD

**Issue by Zev8320** [lipangit/JiaoZiVideoPlayer#2386]
**什么jzvd版本
6.4.3
**是否和安卓版本有关系，什么版本
9.0
**相关log是什么
```
java.lang.VerifyError: Verifier rejected class cn.jzvd.JzvdStd: void cn.jzvd.JzvdStd.dissmissControlView() failed to verify: void cn.jzvd.JzvdStd.dissmissControlView(): [0xE] Call site #10 bootstrap return type is not a reference
void cn.jzvd.JzvdStd.showWifiDialog() failed to verify: void cn.jzvd.JzvdStd.showWifiDialog(): [0x23] Call site #7 bootstrap return type is not a reference (declaration of 'cn.jzvd.JzvdStd' appears in /data/app/com.android.mediaplayer-rLxLfJtezlYIZSFGTckF-w==/base.apk)
```
报错行
```
View view = LayoutInflater.from(mContext).inflate(R.layout.video_item, parent, false);
```
**复现流程
嵌入到fragment中的recyclerview，运行直接报错

**Comment by lipangit** [comment]
为什么呢，用demo的方式不行吗

**Comment by yaofangwx123** [comment]
我也是遇到同样的问题
E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.iplay, PID: 11730
                                                   java.lang.VerifyError: Verifier rejected class cn.jzvd.JzvdStd: void cn.jzvd.JzvdStd.dissmissControlView() failed to verify: void cn.jzvd.JzvdStd.dissmissControlView(): [0xE] Call site #18 bootstrap return type is not a reference
                                                    void cn.jzvd.JzvdStd.onClick(android.view.View) failed to verify: void cn.jzvd.JzvdStd.onClick(android.view.View): [0xB3] Call site #14 bootstrap return type is not a reference
                                                    void cn.jzvd.JzvdStd.showWifiDialog() failed to verify: void cn.jzvd.JzvdStd.showWifiDialog(): [0x23] Call site #15 bootstrap return type is not a reference (declaration of 'cn.jzvd.JzvdStd' appears in /data/app/com.iplay-_CC8ha3rpFhLt6PtbZp7jg==/base.apk)
                                                       at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:647)
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
                                                       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
                                                       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                       at com.chad.library.adapter.base.BaseQuickAdapter.getItemView(BaseQuickAdapter.java:1639)
                                                       at com.chad.library.adapter.base.BaseQuickAdapter.createBaseViewHolder(BaseQuickAdapter.java:1140)
                                                       at com.chad.library.adapter.base.BaseQuickAdapter.onCreateDefViewHolder(BaseQuickAdapter.java:1136)
                                                       at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:858)
                                                       at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:72)
                                                       at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6493)
                                                       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5680)
                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5563)
                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5559)
                                                       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2229)
                                                       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1556)
                                                       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1516)
                                                       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:608)
                                                       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3693)
                                                       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3410)
                                                       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3962)
                                                       at android.view.View.layout(View.java:20831)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:6203)
                                                       at android.support.constraint.ConstraintLayout.onLayout(ConstraintLayout.java:1915)
                                                       at android.view.View.layout(View.java:20831)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:6203)
                                                       at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1767)
                                                       at android.view.View.layout(View.java:20831)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:6203)
                                                       at android.support.constraint.ConstraintLayout.onLayout(ConstraintLayout.java:1915)
                                                       at android.view.View.layout(View.java:20831)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:6203)
                                                       at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:132)
                                                       at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                       at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1361)
09-26 00:00:29.198 11730-11730/? E/AndroidRuntime:     at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:869)

**Comment by XD-Z** [comment]
FATAL EXCEPTION: main
                                                   Process: com.xiangche.dogal.testdemo, PID: 26283
                                                   java.lang.VerifyError: Verifier rejected class cn.jzvd.JzvdStd: void cn.jzvd.JzvdStd.dissmissControlView() failed to verify: void cn.jzvd.JzvdStd.dissmissControlView(): [0xE] Call site #18 bootstrap return type is not a reference
                                                    void cn.jzvd.JzvdStd.onClick(android.view.View) failed to verify: void cn.jzvd.JzvdStd.onClick(android.view.View): [0xB3] Call site #14 bootstrap return type is not a reference
                                                    void cn.jzvd.JzvdStd.showWifiDialog() failed to verify: void cn.jzvd.JzvdStd.showWifiDialog(): [0x23] Call site #15 bootstrap return type is not a reference (declaration of 'cn.jzvd.JzvdStd' appears in /data/app/com.xiangche.dogal.testdemo-Av8htxHZ4OhQqHy8JB9mMw==/base.apk)
同样是这个问题，为了测试，新建的项目，运行就崩溃

**Comment by lipangit** [comment]
怎么样了，demo有这问题吗
