### ISSUE TITLE
发现一个问题，try 异常少了

### ISSUE THREAD

**Issue by fff4** [lipangit/JiaoZiVideoPlayer#2411]
**什么jzvd版本
7.0_preview
**是否和安卓版本有关系，什么版本

**是否和特定品牌的手机机型有关系，什么机型

**相关log是什么
Process: com.ld.mirror, PID: 14850
    java.lang.NullPointerException: Attempt to invoke virtual method 'long tv.danmaku.ijk.media.player.IjkMediaPlayer.getDuration()' on a null object reference
        at com.ld.ldm.activity.technique.vide.JZMediaIjk.getDuration(JZMediaIjk.java:106)
        at cn.jzvd.Jzvd.getDuration(Jzvd.java:786)
        at cn.jzvd.Jzvd$ProgressTimerTask.lambda$run$0(Jzvd.java:989)
        at cn.jzvd.-$$Lambda$Jzvd$ProgressTimerTask$1zOf0X1AJWTfG4NszoBAvJB_9MM.run(lambda)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)
**复现流程
public long getDuration() {
        long duration = 0;
        //TODO MediaPlayer 判空的问题
//        if (JZMediaPlayer.instance().mediaPlayer == null) return duration;
        try {
            duration = mediaInterface.getDuration();
        } catch (IllegalStateException e) {
            e.printStackTrace();
            return duration;
        }
        return duration;
    }
**最好有截图或者视频说明情况
这里有空指针异常的情况，但是只try了非法参数异常

**Comment by lipangit** [comment]
getDuration 这块一直有问题。。具体场景什么样？try 这个nullpoint能解决问题吗

**Comment by maaudrana** [comment]
@lipangit Hey sir apk download link is broken ,can you pls fix it or can you pls publish the app in f-droid ro playstore?

**Comment by lipangit** [comment]
uploaded------------------ 原始邮件 ------------------
发件人: "Md Masud Rana"<notifications@github.com>
发送时间: 2019年5月2日(星期四) 中午12:23
收件人: "lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com>;
抄送: "Nathen"<1066666651@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [lipangit/JiaoZiVideoPlayer] 发现一个问题，try 异常少了 (#2411)



@lipangit Hey sir apk download link is broken ,can you pls fix it or can you pls publish the app in f-droid ro playstore?
 
&mdash;

**Comment by maaudrana** [comment]
Tnx

**Comment by coder-pig** [comment]
JZMediaSystem.start() 时mMediaHandler为空，调用post()引起空指针异常；
复现不了，但是友盟很多这个报错，希望作者可以做下判空~感谢

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.post(java.lang.Runnable)' on a null object reference
    at cn.jzvd.JZMediaSystem.start(JZMediaSystem.java:62)
    at cn.jzvd.Jzvd.onPrepared(Jzvd.java:350)
    at cn.jzvd.JZMediaSystem.lambda$onPrepared$6(JZMediaSystem.java:139)
    at cn.jzvd.-$$Lambda$JZMediaSystem$zIW9UuYfRsLvwe6Lu-iDTY-nGW8.run(Unknown Source:2)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:238)
    at android.app.ActivityThread.main(ActivityThread.java:7905)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:984)
```
