### ISSUE TITLE
App crashed when i clicked on stop play 

### ISSUE THREAD

**Issue by darewealth** [lipangit/JiaoZiVideoPlayer#2413]
### Describe the bug.
When I clicked to play the video in the app, it poped up that the player will continue to consume traffic so I clicked on stop play and the app crashed.

### Steps to reproduce.
* Launch the app.

* Clicked on the video in the app

* Then, click on stop play when it pops up a an info

* And note the bug

### Expected Behaviour

I was expecting it not to play the video and return me back to the app
### Screen recording
https://youtu.be/IEknMPRNqEM

### Devices and Versions):)
* Device: [Itel]

* Version [6.1]

* App version [7.0.1]

### log

```05-02 10:48:13.580 30501 30501 E AndroidRuntime: FATAL EXCEPTION: main
05-02 10:48:13.580 30501 30501 E AndroidRuntime: Process: cn.jzvd.demo, PID: 30501
05-02 10:48:13.580 30501 30501 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void cn.jzvd.u.g()' on a null object reference
05-02 10:48:13.580 30501 30501 E AndroidRuntime: 	at cn.jzvd.z.d()
05-02 10:48:13.580 30501 30501 E AndroidRuntime: 	at cn.jzvd.JzvdStd.b()
05-02 10:48:13.580 30501 30501 E AndroidRuntime: 	at cn.jzvd.r.onClick(lambda)
05-02 10:48:13.580 30501 30501 E AndroidRuntime: 	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:163)
05-02 10:48:13.580 30501 30501 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-02 10:48:13.580 30501 30501 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
05-02 10:48:13.580 30501 30501 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5452)
05-02 10:48:13.580 30501 30501 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-02 10:48:13.580 30501 30501 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
05-02 10:48:13.580 30501 30501 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:671)```

**Comment by lipangit** [comment]
fixed
