### ISSUE TITLE
[JiaoZiVideoPlayer version 7.0.1]  The app gets crashes when I click the Small Change UI option 

### ISSUE THREAD

**Issue by XAMIR555** [lipangit/JiaoZiVideoPlayer#2415]
#### Project Information
* Repository-----------------:  [Here](https://github.com/lipangit/JiaoZiVideoPlayer)
* Project Name-------------:  [JiaoZiVideoPlayer](https://github.com/lipangit/JiaoZiVideoPlayer/releases)
* Publisher------------------:  [Nathen lipangit](https://github.com/lipangit)
* My GitHub account----:  [Here](https://github.com/XAMIR555)

#### Expected behavior
I was hoping that when I click the Small Change UI option, the application should not be crashed.

#### Actual behavior
After I open the application, I click on the Small Change UI option. The application  crashes as you can see in the video

#### How to reproduce
* [Download](https://github.com/lipangit/JiaoZiVideoPlayer/releases) the latest version of the application
* After installing the application, open it
* Click on API 
* Click on SMALL CHANGE UL
* Note the Bug
* Browser/App version-: 7.0.1
* Operating system----: 9.0.0

# Operating system 9.0.0 Proof 

![Screenshot_20190502-220130_Settings.jpg](https://ipfs.busy.org/ipfs/QmRnqQTiuyHnRgdUGj3ZS6nyimqHkeCCP6Xk3GPC6LALty)

#### Recording Of The Bug
![20190502_211623.gif](https://ipfs.busy.org/ipfs/Qmbn6TrioeXPWkxtnkpdZCAZhqvTC4ff2FuzHok7jaDWyC)

# Logcat

<pre><code>05-02 21:01:03.926 30882 30882 E AndroidRuntime: FATAL EXCEPTION: main
05-02 21:01:03.926 30882 30882 E AndroidRuntime: Process: cn.jzvd.demo, PID: 30882
05-02 21:01:03.926 30882 30882 E AndroidRuntime: java.lang.RuntimeException: Unable to pause activity {cn.jzvd.demo/cn.jzvd.demo.ActivityApi}: java.lang.NullPointerException: Attempt to invoke virtual method 'void cn.jzvd.u.e()' on a null object reference
05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4262)
05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4217)
05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4169)
05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:45)
05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7073)
05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
05-02 21:01:03.926 30882 30882 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void cn.jzvd.u.e()' on a null object reference
05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at cn.jzvd.z.h(Unknown Source:24)
05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at cn.jzvd.demo.ActivityApi.onPause(Unknown Source:14)
05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at android.app.Activity.performPause(Activity.java:7606)
05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1469)
05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4252)
</code></pre>

**Comment by lipangit** [comment]
I am very sorry and even ashamed, I can't play after the confusion, the bug is serious, I am trying to modify it.
