### ISSUE TITLE
[JiaoZiVideoPlayer version 7.0.1] The app gets crashes when I click the STOP PLAY

### ISSUE THREAD

**Issue by XAMIR555** [lipangit/JiaoZiVideoPlayer#2416]
#### Project Information
* Repository-----------------:  [Here](https://github.com/lipangit/JiaoZiVideoPlayer)
* Project Name-------------:  [JiaoZiVideoPlayer](https://github.com/lipangit/JiaoZiVideoPlayer/releases)
* Publisher------------------:  [Nathen lipangit](https://github.com/lipangit)
* My GitHub account----:  [Here](https://github.com/XAMIR555)

#### Expected behavior
When I click on STOP PLAY, the application  should not crash, Rather, the running video should be stopped

#### Actual behavior
The app gets crashes when I click the STOP PLAY option 

#### How to reproduce
* [Download](https://github.com/lipangit/JiaoZiVideoPlayer/releases) the latest version of the application
* After installing the application, open it
* click on the video icon
* click on Stope Play
* Note the Bug
* Browser/App version-: 7.0.1
* Operating system----: 9.0.0

#### Recording Of The Bug

![20190502_220822](https://user-images.githubusercontent.com/49812927/57093999-362fc180-6cc4-11e9-8b52-d83a46e8b953.gif)

# Logcat

<pre><code>05-02 21:01:03.926 30882 30882 E AndroidRuntime: FATAL EXCEPTION: main
05-02 21:01:03.926 30882 30882 E AndroidRuntime: Process: cn.jzvd.demo, PID: 30882
05-02 21:01:03.926 30882 30882 E AndroidRuntime: java.lang.RuntimeException: Unable to pause activity {cn.jzvd.demo/cn.jzvd.demo.ActivityApi}: java.lang.NullPointerException: Attempt to invoke virtual method 'void cn.jzvd.u.e()' on a null object reference
05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4262)
05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4217)
05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4169)
05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:45)
05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7073)
05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
05-02 21:01:03.926 30882 30882 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void cn.jzvd.u.e()' on a null object reference
05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at cn.jzvd.z.h(Unknown Source:24)
05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at cn.jzvd.demo.ActivityApi.onPause(Unknown Source:14)
05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at android.app.Activity.performPause(Activity.java:7606)
05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1469)
05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4252)
</code></pre>

**Comment by lipangit** [comment]
it is bug, after proguard,can you help to find out where is crash,which line of code------------------ 原始邮件 ------------------
发件人: "XAMIR555"<notifications@github.com>
发送时间: 2019年5月3日(星期五) 凌晨1:23
收件人: "lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [lipangit/JiaoZiVideoPlayer] [JiaoZiVideoPlayer version 7.0.1] Theapp gets crashes when I click the STOP PLAY (#2416)



Project Information
  
Repository-----------------:  Here
 
Project Name-------------:  JiaoZiVideoPlayer
 
Publisher------------------:  Nathen lipangit
 
My GitHub account----:  Here
  
Expected behavior
 
When I click on STOP PLAY, the application  should not crash, Rather, the running video should be stopped
 
Actual behavior
 
The app gets crashes when I click the STOP PLAY option
 
How to reproduce
  
Download the latest version of the application
 
After installing the application, open it
 
click on the video icon
 
click on Stope Play
 
Note the Bug
 
Browser/App version-: 7.0.1
 
Operating system----: 9.0.0
  
Recording Of The Bug
 

 
Logcat
 05-02 21:01:03.926 30882 30882 E AndroidRuntime: FATAL EXCEPTION: main 05-02 21:01:03.926 30882 30882 E AndroidRuntime: Process: cn.jzvd.demo, PID: 30882 05-02 21:01:03.926 30882 30882 E AndroidRuntime: java.lang.RuntimeException: Unable to pause activity {cn.jzvd.demo/cn.jzvd.demo.ActivityApi}: java.lang.NullPointerException: Attempt to invoke virtual method 'void cn.jzvd.u.e()' on a null object reference 05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4262) 05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4217) 05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4169) 05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:45) 05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145) 05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70) 05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955) 05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106) 05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214) 05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7073) 05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method) 05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964) 05-02 21:01:03.926 30882 30882 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void cn.jzvd.u.e()' on a null object reference 05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at cn.jzvd.z.h(Unknown Source:24) 05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at cn.jzvd.demo.ActivityApi.onPause(Unknown Source:14) 05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at android.app.Activity.performPause(Activity.java:7606) 05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1469) 05-02 21:01:03.926 30882 30882 E AndroidRuntime: 	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4252)  
&mdash;

**Comment by XAMIR555** [comment]
I don,t know where is a bug I am not a developer

**Comment by lipangit** [comment]
what are you looking for------------------ 原始邮件 ------------------
发件人: "XAMIR555"<notifications@github.com>
发送时间: 2019年5月3日(星期五) 凌晨1:59
收件人: "lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com>;
抄送: "Nathen"<1066666651@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [lipangit/JiaoZiVideoPlayer] [JiaoZiVideoPlayer version 7.0.1]The app gets crashes when I click the STOP PLAY (#2416)



I don,t know where is a bug I am not a developer
 
&mdash;
