### ISSUE TITLE
App crashed in  Change to android.media.Mediaplayer when I clicked on the back button

### ISSUE THREAD

**Issue by darewealth** [lipangit/JiaoZiVideoPlayer#2419]
### Describe the bug.
When I clicked on ***Api*** and click on Custom Mediaplayer, then click on ***Change to android.media.Mediaplayer*** and when I click on the phones back button, the app crashed.

### Steps to reproduce.
* Launch the app.

* Clicked on the 'Api'

* Then, click on 'Custom Mediaplayer' 

* Click on 'Change to android.media.Mediaplayer' and press the phone back button.

* And note the bug

### Expected Behaviour

I don't expect the app to crash when I made the changes, and click on the back button.

### Screen recording
https://youtu.be/_mbPjc1wA5M

### Devices and Versions):)
* Device: [Itel]

* Version [6.1]

* App version [7.0.1]

### Log

```05-06 17:40:23.408 10587 10587 E AndroidRuntime: FATAL EXCEPTION: main
05-06 17:40:23.408 10587 10587 E AndroidRuntime: Process: cn.jzvd.demo, PID: 10587
meException: Unable to pause activity {cn.jzvd.demo/cn.jzvd.demo.ActivityApiCustomMedia}: java.lang.NullPointerException: Attempt to invoke virtual method 'void cn.jzvd.u.g()' on a null object reference05-06 17:40:23.408 10587 10587 E AndroidRuntime: java.lang.Runti
05-06 17:40:23.408 10587 10587 E AndroidRuntime: 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3396)
05-06 17:40:23.408 10587 10587 E AndroidRuntime: 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3355)
05-06 17:40:23.408 10587 10587 E AndroidRuntime: 	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3330)
05-06 17:40:23.408 10587 10587 E AndroidRuntime: 	at android.app.ActivityThread.-wrap13(ActivityThread.java)
05-06 17:40:23.408 10587 10587 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
05-06 17:40:23.408 10587 10587 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-06 17:40:23.408 10587 10587 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
05-06 17:40:23.408 10587 10587 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5452)
05-06 17:40:23.408 10587 10587 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-06 17:40:23.408 10587 10587 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
05-06 17:40:23.408 10587 10587 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:671)
05-06 17:40:23.408 10587 10587 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void cn.jzvd.u.g()' on a null object reference
05-06 17:40:23.408 10587 10587 E AndroidRuntime: 	at cn.jzvd.z.v()
05-06 17:40:23.408 10587 10587 E AndroidRuntime: 	at cn.jzvd.JzvdStd.v()
05-06 17:40:23.408 10587 10587 E AndroidRuntime: 	at cn.jzvd.z.w()
05-06 17:40:23.408 10587 10587 E AndroidRuntime: 	at cn.jzvd.demo.ActivityApiCustomMedia.onPause()
05-06 17:40:23.408 10587 10587 E AndroidRuntime: 	at android.app.Activity.performPause(Activity.java:6417)
05-06 17:40:23.408 10587 10587 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1314)
05-06 17:40:23.408 10587 10587 E AndroidRuntime: 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3382)```

**Comment by lipangit** [comment]
Relaxed, just fixed.

Thank you for your test.

**Comment by darewealth** [comment]
Glad you fixed it :+1:
