### ISSUE TITLE
使用移动流量播放时，弹出提示，点击取消后崩溃

### ISSUE THREAD

**Issue by hczmail** [lipangit/JiaoZiVideoPlayer#2435]
**什么jzvd版本
v7.0.3

**是否和安卓版本有关系，什么版本

**是否和特定品牌的手机机型有关系，什么机型

**相关log是什么
java.lang.NullPointerException: Attempt to invoke virtual method 'void cn.jzvd.JZMediaInterface.release()' on a null object reference
    at cn.jzvd.Jzvd.clearFloatScreen(Jzvd.java:564)
    at cn.jzvd.JzvdStd.lambda$showWifiDialog$2$JzvdStd(JzvdStd.java:345)
    at cn.jzvd.-$$Lambda$JzvdStd$tSCWAsxj_MPu0eqRSrsl1-oC8xk.onClick(Unknown Source:2)
    at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:174)
    at android.os.Handler.dispatchMessage(Handler.java:109)
    at android.os.Looper.loop(Looper.java:207)
    at android.app.ActivityThread.main(ActivityThread.java:7539)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
**复现流程
使用移动流量播放时，弹出提示，点击取消后崩溃
**最好有截图或者视频说明情况

**Comment by lipangit** [comment]
感谢你的反馈，已经修复，给你2000JZT  https://github.com/lipangit/JZT 下载币威钱包 https://www.bitcv.app/?from=bitcvCom  把里面的以太坊地址发给我。

**Comment by Alen-Liu** [comment]
怎么解决的

**Comment by lipangit** [comment]
2f714fb3d2fe50c5df27c99bdf937149badb2dbb
