### ISSUE TITLE
JZMediaExo v7.0.3 crashes

### ISSUE THREAD

**Issue by sosasang** [lipangit/JiaoZiVideoPlayer#2436]
**什么jzvd版本
v7.0.3
**是否和安卓版本有关系，什么版本
No
**是否和特定品牌的手机机型有关系，什么机型
No
**相关log是什么
- surfaceTexture must not be null
- NPE
**复现流程
From bug report, no idea how to reproduce.
JZMediaExo.java
line 100: addVideoListener -> NPE
line 112: setPlayWhenReady(true) -> NPE
line 115: setVideoSurface -> surfaceTexture must not be null

**最好有截图或者视频说明情况

**Comment by jerry9433** [comment]
我也遇到了，使用Exo内核的时候回报这个错，目前我只是判了空

**Comment by lipangit** [comment]
能把你的判空代码截图一下吗

**Comment by jerry9433** [comment]
额，刚才又遇到了这个问题，很显然我的判空代码还是不行
`2019-05-27 16:01:31.263 I/ExoPlayerImpl: Release 4e39527 [ExoPlayerLib/2.9.1] [dreamqltechn, SM-G9500, samsung, 28] [goog.exo.core]
2019-05-27 16:01:31.263  E/JZMediaExo: URL Link = http://192.168.1.200:81/group1/M01/01/2D/wKgByFznaSSECvW5AAAAAD5DnAM403.mp4
2019-05-27 16:01:31.264  W/MessageQueue: Handler (android.os.Handler) {f8293d4} sending message to a Handler on a dead thread
    java.lang.IllegalStateException: Handler (android.os.Handler) {f8293d4} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:546)
        at android.os.Handler.enqueueMessage(Handler.java:745)
        at android.os.Handler.sendMessageAtTime(Handler.java:697)
        at android.os.Handler.sendMessageDelayed(Handler.java:667)
        at android.os.Handler.sendMessage(Handler.java:604)
        at android.os.Message.sendToTarget(Message.java:436)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.prepare(ExoPlayerImplInternal.java:179)
        at com.google.android.exoplayer2.ExoPlayerImpl.prepare(ExoPlayerImpl.java:217)
        at com.google.android.exoplayer2.SimpleExoPlayer.prepare(SimpleExoPlayer.java:883)
        at com.google.android.exoplayer2.SimpleExoPlayer.prepare(SimpleExoPlayer.java:868)
        at Utils.JZMediaExo.lambda$prepare$0(JZMediaExo.java:111)
        at Utils.-$$Lambda$JZMediaExo$6nSGKS08eq8EEooNYGJ61aj36hM.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2019-05-27 16:01:31.264  E/JZMediaExo: onPlayerStateChanged2/ready=false
2019-05-27 16:01:31.265  W/MessageQueue: Handler (android.os.Handler) {f8293d4} sending message to a Handler on a dead thread
    java.lang.IllegalStateException: Handler (android.os.Handler) {f8293d4} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:546)
        at android.os.Handler.enqueueMessage(Handler.java:745)
        at android.os.Handler.sendMessageAtTime(Handler.java:697)
        at android.os.Handler.sendMessageDelayed(Handler.java:667)
        at android.os.Handler.sendMessage(Handler.java:604)
        at android.os.Message.sendToTarget(Message.java:436)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.setPlayWhenReady(ExoPlayerImplInternal.java:183)
        at com.google.android.exoplayer2.ExoPlayerImpl.setPlayWhenReady(ExoPlayerImpl.java:236)
        at com.google.android.exoplayer2.SimpleExoPlayer.updatePlayWhenReady(SimpleExoPlayer.java:1183)
        at com.google.android.exoplayer2.SimpleExoPlayer.setPlayWhenReady(SimpleExoPlayer.java:891)
        at Utils.JZMediaExo.lambda$prepare$0(JZMediaExo.java:112)
        at Utils.-$$Lambda$JZMediaExo$6nSGKS08eq8EEooNYGJ61aj36hM.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2019-05-27 16:01:31.265 E/JZMediaExo: onPlayerStateChanged2/ready=true
2019-05-27 16:01:31.266 E/AndroidRuntime: FATAL EXCEPTION: JZVD
    java.lang.IllegalArgumentException: surfaceTexture must not be null
        at android.view.Surface.<init>(Surface.java:196)
        at Utils.JZMediaExo.lambda$prepare$0(JZMediaExo.java:116)
        at Utils.-$$Lambda$JZMediaExo$6nSGKS08eq8EEooNYGJ61aj36hM.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2019-05-27 16:01:31.267  I/ExoPlayerImpl: Release 4e39527 [ExoPlayerLib/2.9.1] [dreamqltechn, SM-G9500, samsung, 28] [goog.exo.core]
2019-05-27 16:01:31.270  E/CrashHandler: In thread: Thread[JZVD,5,main]
    UncaughtException detected: java.lang.IllegalArgumentException: surfaceTexture must not be null
        at android.view.Surface.<init>(Surface.java:196)
        at Utils.JZMediaExo.lambda$prepare$0(JZMediaExo.java:116)
        at Utils.-$$Lambda$JZMediaExo$6nSGKS08eq8EEooNYGJ61aj36hM.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2019-05-27 16:01:31.270  I/crash_recorder: recordTbsCrash:
     {java.lang.IllegalArgumentException: surfaceTexture must not be null
        at android.view.Surface.<init>(Surface.java:196)
        at Utils.JZMediaExo.lambda$prepare$0(JZMediaExo.java:116)
        at Utils.-$$Lambda$JZMediaExo$6nSGKS08eq8EEooNYGJ61aj36hM.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:65)
    }
2019-05-27 16:01:31.270I/crash_recorder: isInTbsContext, webviewType: unknown, isLoading: 0
`

**Comment by lipangit** [comment]
IllegalStateException 这个log是，不是空指针

**Comment by lipangit** [comment]
JZMediaExo 这个类 参考JZMediaSystem研究一下，改一改，JZMediaExo这个类我没深入研究，是别人写的。

**Comment by sosasang** [comment]
JZMediaSystem的prepare方法里有个try catch
