### ISSUE TITLE
在设置严苛模式下，app崩溃！！！！

### ISSUE THREAD

**Issue by huangzhijin** [lipangit/JiaoZiVideoPlayer#2447]
**需求描述
设置严苛模式：
   @Override
    public void onCreate() {
        if (BuildConfig.DEBUG) {
            // 针对线程的相关策略
            StrictMode.setThreadPolicy(new StrictMode.ThreadPolicy.Builder()
                    .detectDiskReads()
                    .detectDiskWrites()
                    .detectNetwork()   // or .detectAll() for all detectable problems
                    .penaltyLog()
                    .build());

            // 针对VM的相关策略
            StrictMode.setVmPolicy(new StrictMode.VmPolicy.Builder()
                    .detectLeakedSqlLiteObjects()
                    .detectLeakedClosableObjects()
                    .penaltyLog()
                    .penaltyDeath()
                    .build());
        }
        super.onCreate();
报错信息：
06-05 18:19:29.123 12069-12087/readsense.face24 E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
    java.lang.Throwable: Explicit termination method 'release' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:184)
        at android.view.Surface.setNativeObjectLocked(Surface.java:460)
        at android.view.Surface.<init>(Surface.java:145)
        at cn.jzvd.JZMediaSystem.lambda$prepare$0$JZMediaSystem(JZMediaSystem.java:53)
        at cn.jzvd.JZMediaSystem$$Lambda$0.run(Unknown Source)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:224)
        at android.os.HandlerThread.run(HandlerThread.java:61)
  提示此行有问题：  mediaPlayer.setSurface(new Surface(SAVED_SURFACE));

**Comment by lipangit** [comment]
log的意思是不是有没关闭的MediaPlayer。

![image](https://user-images.githubusercontent.com/2038071/58956933-25e29900-87d2-11e9-9069-1192216e0241.png)

每次播放之前都会release MediaPlayer 重新 new，兄弟能帮忙研究一下什么情况下回出现log的情况吗

**Comment by huangzhijin** [comment]
视屏播放完之后就奔溃了

**Comment by huangzhijin** [comment]
在application中的oncreate加上严苛模式，视频播放完就会崩溃！   @Override
    public void onCreate() {
        if (BuildConfig.DEBUG) {
            // 针对线程的相关策略
            StrictMode.setThreadPolicy(new StrictMode.ThreadPolicy.Builder()
                    .detectDiskReads()
                    .detectDiskWrites()
                    .detectNetwork()   // or .detectAll() for all detectable problems
                    .penaltyLog()
                    .build());

            // 针对VM的相关策略
            StrictMode.setVmPolicy(new StrictMode.VmPolicy.Builder()
                    .detectLeakedSqlLiteObjects()
                    .detectLeakedClosableObjects()
                    .penaltyLog()
                    .penaltyDeath()
                    .build());
        }
        super.onCreate();
  
    }

**Comment by huangzhijin** [comment]
06-06 09:46:00.851 919-1015/cn.jzvd.demo E/Parcel: Reading a NULL string not supported here.
06-06 09:46:00.896 919-1015/cn.jzvd.demo E/Parcel: Reading a NULL string not supported here.
06-06 09:46:00.931 919-1015/cn.jzvd.demo E/Parcel: Reading a NULL string not supported here.
06-06 09:46:00.963 919-1015/cn.jzvd.demo E/Parcel: Reading a NULL string not supported here.
06-06 09:46:01.013 919-1015/cn.jzvd.demo E/Parcel: Reading a NULL string not supported here.
06-06 09:46:01.047 919-1015/cn.jzvd.demo E/Parcel: Reading a NULL string not supported here.
06-06 09:46:01.098 919-1015/cn.jzvd.demo E/Parcel: Reading a NULL string not supported here.
06-06 09:46:01.134 919-1015/cn.jzvd.demo E/Parcel: Reading a NULL string not supported here.
06-06 09:46:01.166 919-1015/cn.jzvd.demo E/Parcel: Reading a NULL string not supported here.

**Comment by lipangit** [comment]
在demo的application的onCreate函数里设置严苛模式，MainActivity的视频第一次播放完就会出错是吗？

**Comment by huangzhijin** [comment]
嗯，是的
