### ISSUE TITLE
调用changeUrl切换url的bug

### ISSUE THREAD

**Issue by zhuxiaohao** [lipangit/JiaoZiVideoPlayer#2448]
**什么jzvd版本
7.04

**是否和安卓版本有关系，什么版本
所有手机
**是否和特定品牌的手机机型有关系，什么机型
测试过一加，小米，华为，
**相关log是什么
    Process: cn.jzvd.demo, PID: 29667
    java.lang.IllegalStateException: mpjni: prepareAsync: null mp
        at tv.danmaku.ijk.media.player.IjkMediaPlayer._prepareAsync(Native Method)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.prepareAsync(IjkMediaPlayer.java:515)
        at cn.jzvd.demo.CustomMedia.JZMediaIjk.lambda$prepare$0$JZMediaIjk(JZMediaIjk.java:68)
        at cn.jzvd.demo.CustomMedia.-$$Lambda$JZMediaIjk$j54qzRRHtS1XuUqfdO9dyeNMzfE.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)

**复现流程
 在demo ActivityApiCustomMedia 操作切换播放器内核，用MyJzvdStd复写onAutoCompletion 增加回调调用changeUrl会出现以下情况。
1.在调用changeUrl如果调用jzvdStd.startButton.performClick(); 不闪退，会出现有声音画面停留上一个视频的末尾。
2.在调用changeUrl如果调用jzvdStd.startVideo(); 闪退，必现。但是视频能正常切换，声音正常。闪退的概率在多切换几次就出现上面的log。 

**最好有截图或者视频说明情况
需要附上demo吗？

**Comment by lipangit** [comment]
需要更多信息

**Comment by zhuxiaohao** [comment]
不好意思，刚才忘记填写了，我需要把这个demo发给你吗？

**Comment by zhuxiaohao** [comment]
留下邮箱我发你邮箱吧，你看可以吗？

**Comment by zhuxiaohao** [comment]
链接: https://pan.baidu.com/s/1yChi2O9iNuL7zQ9mn3YqlA 提取码: djad 复制这段内容后打开百度网盘手机App，操作更方便哦     在这个 ActivityApiCustomMedia 下面有操作。

**Comment by zmCao** [comment]
想问下这个问题有没有解决了，我也遇到changeUrl闪退的问题，想实现自动播放下一集，以及播放状态下插播另外一部视频

**Comment by xiaoshuai1** [comment]
可以使用setUp切换吗

**Comment by kjtown** [comment]
这个问题有解决方案了没有，我也遇到了，不知道怎么解决。

**Comment by SmallWinter** [comment]
请问前辈解决了吗？ 我是change就报错

**Comment by SmallWinter** [comment]
![image](https://user-images.githubusercontent.com/8638180/65503577-c67ed500-def7-11e9-97fa-491f15642145.png)

**Comment by W252016021** [comment]
同样的问题：
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.MediaPlayer.setSurface(android.view.Surface)' on a null object reference
        at cn.jzvd.JZMediaSystem.setSurface(JZMediaSystem.java:1)
        at cn.jzvd.Jzvd.a(Jzvd.java:46)
        at cn.jzvd.JzvdStd.a(JzvdStd.java:27)
        at cn.jzvd.Jzvd.a(Jzvd.java:36)
        at com.walixiwa.easyplayer.widget.DetailVideoPlayer.a(DetailVideoPlayer.java:16)
        at com.walixiwa.easyplayer.widget.DetailVideoPlayer.i(DetailVideoPlayer.java:2)
        at cn.jzvd.JZMediaSystem.a(JZMediaSystem.java:7)
        at e.a.k.run(lambda)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

**Comment by lipangit** [comment]
这就解决
