### ISSUE TITLE
在onAutoComplete里调用changeUrl出错

### ISSUE THREAD

**Issue by kennir** [lipangit/JiaoZiVideoPlayer#2468]
**什么jzvd版本
7.0.4
**是否和安卓版本有关系，什么版本
无
**是否和特定品牌的手机机型有关系，什么机型
无
**相关log是什么

```
06-19 16:16:09.974 29052-29052/com.knew.feed E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.knew.feed, PID: 29052
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.MediaPlayer.setSurface(android.view.Surface)' on a null object reference
        at cn.jzvd.JZMediaSystem.setSurface(JZMediaSystem.java:187)
        at cn.jzvd.Jzvd.changeUrl(Jzvd.java:522)
        at cn.jzvd.JzvdStd.changeUrl(JzvdStd.java:171)
        at cn.jzvd.Jzvd.changeUrl(Jzvd.java:506)
        at com.knew.feed.ui.view.MaskedVideoPlayer.onAutoCompletion(MaskedVideoPlayer.kt:191)
        at cn.jzvd.JZMediaSystem.lambda$onCompletion$7(JZMediaSystem.java:146)
        at cn.jzvd.-$$Lambda$JZMediaSystem$s7EAuXFloE1cNvllAZucygtXI6Y.run(lambda)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5845)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:768)
```

**复现流程

按照文档里的做法自动播放下一集

```
override fun onAutoCompletion() {
  super.onAutoCompletion()
     if (current + 1 < urls.count()) {
       current++
       changeUrl(urls[current], "", 0)
    }
}
```

如果去掉super.onAutoCompletion() 不崩溃了，但是UI等就不正确了，看代码里可能是 super.onAutoCompletion里已经调用了mediaInterface.release， 导致changleUrl里调用mediaInterface.setSurface出错

**最好有截图或者视频说明情况

**Comment by kennir** [comment]
原因查到了，文档里的代码已经过时了， 如果调用过了 super.onAutoCompletion()， 那么之后调用changeUrl必然出错

```
    override fun onAutoCompletion() {
        if (current + 1 < urls.count()) {
            current++
            changeUrl(urls[current], "", 0)
            onStatePreparing()
        } else {
            super.onAutoCompletion()
        }
    }
```

**Comment by lipangit** [comment]
ui哪里不正确？

super.onAutoCompletion()   有他会销毁mediaplayer导致崩溃。没有他和普通的播放中changeUrl是一样的。

刚亲测

**Comment by kennir** [comment]
@lipangit  UI的问题是没有调用OnStatePreparing

**Comment by lipangit** [comment]
就是这样的，切换进度，切换url都没有loading状态。

**Comment by kroben-ha** [comment]
if (UrlIndex<list.size()-1){
            LogDoc.d(list.size()+"");
            UrlIndex++;
            changeUrl("https://dwoq2ae2ivebn.cloudfront.net/_306085_ldqj_Legio.S03E02.720p.WEB.x265-MiNX%5Beztv%5D.mkv", "hahahahahah", 0);
            onStatePreparing();
        }else {
            super.onAutoCompletion();
        }

为什么会出现视频播放失败，点击重试后正常？？

**Comment by lipangit** [comment]
changeurl之后不需要onStatePreparing（）
