### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "cn.jzvd.demo.CustomJzvd.MyJzvdStd"

### ISSUE THREAD

**Issue by charafboulmerk** [lipangit/JiaoZiVideoPlayer#2475]
`android.view.InflateException: Binary XML file line #57: Binary XML file line #57: Error inflating class cn.jzvd.demo.CustomJzvd.MyJzvdStd
    Caused by: android.view.InflateException: Binary XML file line #57: Error inflating class cn.jzvd.demo.CustomJzvd.MyJzvdStd
    Caused by: java.lang.ClassNotFoundException: Didn't find class "cn.jzvd.demo.CustomJzvd.MyJzvdStd" on path: DexPathList[[zip file "/data/app/com.boulmerka.simplevip.socialmedia-2/base.apk"],nativeLibraryDirectories=[/data/app/com.boulmerka.simplevip.socialmedia-2/lib/arm64, /system/lib64, /vendor/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.view.LayoutInflater.createView(LayoutInflater.java:609)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
        at com.boulmerka.simplevip.socialmedia.Utils.HalperClass$UsersPosts.getView(HalperClass.kt:262)
        at android.widget.AbsListView.obtainView(AbsListView.java:2496)
        at android.widget.ListView.makeAndAddView(ListView.java:2018)
        at android.widget.ListView.fillDown(ListView.java:721)
        at android.widget.ListView.fillFromTop(ListView.java:782)
        at android.widget.ListView.layoutChildren(ListView.java:1750)
        at android.widget.AbsListView.onLayout(AbsListView.java:2254)
        at android.view.View.layout(View.java:17890)
        at android.view.ViewGroup.layout(ViewGroup.java:5757)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1189)
        at android.view.View.layout(View.java:17890)
        at android.view.ViewGroup.layout(ViewGroup.java:5757)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
        at android.view.View.layout(View.java:17890)
        at android.view.ViewGroup.layout(ViewGroup.java:5757)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1982)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1826)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1735)
        at android.view.View.layout(View.java:17890)
        at android.view.ViewGroup.layout(ViewGroup.java:5757)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
        at android.view.View.layout(View.java:17890)
        at android.view.ViewGroup.layout(ViewGroup.java:5757)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1982)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1826)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1735)
        at android.view.View.layout(View.java:17890)
        at android.view.ViewGroup.layout(ViewGroup.java:5757)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
        at android.view.View.layout(View.java:17890)
        at android.view.ViewGroup.layout(ViewGroup.java:5757)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1982)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1826)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1735)
        at android.view.View.layout(View.java:17890)
2019-06-21 21:37:53.262 8550-8550/com.boulmerka.simplevip.socialmedia E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5757)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:751)
        at android.view.View.layout(View.java:17890)
        at android.view.ViewGroup.layout(ViewGroup.java:5757)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2732)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2405)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1479)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7019)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:907)
        at android.view.Choreographer.doCallbacks(Choreographer.java:709)
        at android.view.Choreographer.doFrame(Choreographer.java:644)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:893)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6269)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
`

i have create an adapter class and i'm trying to show a list of video in ListView but i got this error

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/59963077-7b33df80-9520-11e9-8909-c11781627f5f.png)

I think something wrong with the implementation.

**Comment by sungbin5304** [comment]
Use `cn.jzvd.JzvdStd` this

**Comment by lipangit** [comment]
try  to build and try to other way to build.
