### ISSUE TITLE
使用exoplayer内核播放视频报错301,会有http,https重定向问题

### ISSUE THREAD

**Issue by hyccode** [lipangit/JiaoZiVideoPlayer#2478]
**版本7.0.4

**相关log是什么
ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 301
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:300)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

**解决方式
https://stackoverflow.com/questions/41517440/exoplayer2-how-can-i-make-a-http-301-redirect-work/41524566#41524566
![image](https://user-images.githubusercontent.com/26076350/59997922-b48b5d00-9690-11e9-83b9-880b20ea751e.png)
![image](https://user-images.githubusercontent.com/26076350/59997936-be14c500-9690-11e9-8d29-908ee327c338.png)

**Comment by lipangit** [comment]
Thank you
