### ISSUE TITLE
OOM

### ISSUE THREAD

**Issue by fengjuan** [lipangit/JiaoZiVideoPlayer#2487]
**什么jzvd版本
6.2.12版本
**是否和安卓版本有关系，什么版本
Android 7.1
**是否和特定品牌的手机机型有关系，什么机型
三星A7100
**相关log是什么
2019-06-27 16:58:28.326 4262-4262/com.qicloud.easygame E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.qicloud.easygame, PID: 4262
    java.lang.OutOfMemoryError: Failed to allocate a 291612 byte allocation with 91432 free bytes and 89KB until OOM
        at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
        at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
        at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:700)
        at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:535)
        at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1182)
        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:770)
        at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:621)
        at android.content.res.Resources.loadDrawable(Resources.java:1733)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:945)
        at android.graphics.drawable.StateListDrawable.inflateChildElements(StateListDrawable.java:171)
        at android.graphics.drawable.StateListDrawable.inflate(StateListDrawable.java:116)
        at android.graphics.drawable.DrawableInflater.inflateFromXml(DrawableInflater.java:134)
        at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1254)
        at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1227)
        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:765)
        at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:621)
        at android.content.res.Resources.getDrawable(Resources.java:1646)
        at android.content.Context.getDrawable(Context.java:525)
        at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:454)
        at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:144)
        at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:132)
        at androidx.appcompat.content.res.AppCompatResources.getDrawable(AppCompatResources.java:104)
        at androidx.appcompat.widget.AppCompatImageHelper.setImageResource(AppCompatImageHelper.java:86)
        at androidx.appcompat.widget.AppCompatImageView.setImageResource(AppCompatImageView.java:94)
        at cn.jzvd.JZVideoPlayerStandard.updateStartImage(JZVideoPlayerStandard.java:662)
        at cn.jzvd.JZVideoPlayerStandard.changeUiToPreparing(JZVideoPlayerStandard.java:521)
        at cn.jzvd.JZVideoPlayerStandard.onStatePreparing(JZVideoPlayerStandard.java:180)
        at cn.jzvd.JZVideoPlayer.startVideo(JZVideoPlayer.java:610)
        at com.qicloud.easygame.common.MyVideoPlayer.startVideo(MyVideoPlayer.java:331)
        at com.qicloud.easygame.fragment.MainFragment$2.onScrollStateChanged(MainFragment.java:262)
        at androidx.recyclerview.widget.RecyclerView.dispatchOnScrollStateChanged(RecyclerView.java:5114)
        at androidx.recyclerview.widget.RecyclerView.setScrollState(RecyclerView.java:1552)
        at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5300)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:930)
        at android.view.Choreographer.doCallbacks(Choreographer.java:705)
        at android.view.Choreographer.doFrame(Choreographer.java:637)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:916)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6816)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1567)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1455)

**复现流程
滑动列表时偶现
**最好有截图或者视频说明情况

**Comment by lipangit** [comment]
从log看是设置图片oom

**Comment by fengjuan** [comment]
> 从log看是设置图片oom
从这个log看，像是饺子播放里面导致的？
at cn.jzvd.JZVideoPlayerStandard.updateStartImage(JZVideoPlayerStandard.java:662)

**Comment by lipangit** [comment]
是的，这里面需要更新开始按钮的图标

**Comment by fengjuan** [comment]
> 是的，这里面需要更新开始按钮的图标
有没有解决方案建议呢？顺便问一下，有提供隐藏控制按钮（播放、暂停）的接口吗，如果隐藏掉不更新的画是不是能解决？因为我们的页面是不需要这些按钮的，目前是拷贝了一份jz_layout_standard.xml文件，设置GONE 来隐藏

**Comment by lipangit** [comment]
oom不知道怎么解决，一起想想办法。

显示隐藏按钮，参考demo的继承JzvdStd复写各个状态的函数，在各个状态中分别显示隐藏按钮
