### ISSUE TITLE
混淆开启后列表滑动暂停播放崩溃

### ISSUE THREAD

**Issue by jerry9433** [lipangit/JiaoZiVideoPlayer#2517]
**什么jzvd版本
7.4
**是否和安卓版本有关系，什么版本
无关
**是否和特定品牌的手机机型有关系，什么机型
无关
**相关log是什么
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void cn.jzvd.b.pause()' on a null object reference
at cn.jzvd.Jzvd.B(SourceFile:905)
at com.petbanny.app.Note.NoteDetailRecyclerActivity$1.onScrolled(SourceFile:235)
at android.support.v7.widget.RecyclerView.dispatchOnScrolled(SourceFile:4961)
at android.support.v7.widget.RecyclerView.scrollByInternal(SourceFile:1954)
at android.support.v7.widget.RecyclerView.onTouchEvent(SourceFile:3187)
at android.view.View.dispatchTouchEvent(View.java:13485)


 java.lang.NullPointerException: Attempt to invoke virtual method 'long cn.jzvd.b.getCurrentPosition()' on a null object reference
        at cn.jzvd.Jzvd.getCurrentPositionWhenPlaying(SourceFile:632)
        at cn.jzvd.Jzvd$a.a(SourceFile:845)
        at cn.jzvd.q.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7045)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```
**复现流程
在列表中，待视频播放后向下滑，调用
```
Jzvd.goOnPlayOnPause();
Jzvd.resetAllVideos();
videoHelper.<JzvdStd>getView(R.id.videoPlayer).mediaInterface.release();
videoHelper.<JzvdStd>getView(R.id.videoPlayer).onStateNormal();
```
就崩溃了，之前用的7.0_preview没有问题，这期刚升级到7.4
**最好有截图或者视频说明情况

**Comment by jerry9433** [comment]
主要是混淆开启后会出现崩溃，不开启就没事，混淆规则我也添加了啊

**Comment by lipangit** [comment]
demo有这个问题吗

**Comment by jerry9433** [comment]
```
public long getCurrentPositionWhenPlaying() {
        long position = 0;
        if (state == STATE_PLAYING ||
                state == STATE_PAUSE) {
            try {
                position = mediaInterface.getCurrentPosition();
            } catch (IllegalStateException e) {
                e.printStackTrace();
                return position;
            }
        }
        return position;
    }
```
是这个方法getCurrentPosition()的时候mediaInterface为空了。没办法追踪，因为debug包没问题,我用的Exo
```
                helper.<CustomJzStd>getView(R.id.videoPlayer).setUp(RequestUrlMap.fileDownloadUrl + noteBean.getRecordUrl(), "", Jzvd.SCREEN_NORMAL,  JZMediaExo.class);

```

**Comment by lipangit** [comment]
1.运行一下混淆过的demo是否有这个问题，应该没有
2.确定自己的混淆是否写全

3.确定不用exo，混淆之后是否有这个问题
