### ISSUE TITLE
cn.jzvd.Jzvd.goOnPlayOnResume方法导致android.view.WindowManager$BadTokenException

### ISSUE THREAD

**Issue by memoryjs** [lipangit/JiaoZiVideoPlayer#2544]
**什么jzvd版本
7.0.4

**相关log是什么

java.lang.RuntimeException: Unable to resume activity {com.imohoo.shanpao/cn.migu.buniness.medal.ui.MedalInfoActivity}: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@f9488ca for displayid = 0 is not valid; is your activity running? 
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4354) 
    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4394) 
    at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51) 
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145) 
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2155) 
    at android.os.Handler.dispatchMessage(Handler.java:109) 
    at android.os.Looper.loop(Looper.java:207) 
    at android.app.ActivityThread.main(ActivityThread.java:7539) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958) 
Caused by: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@f9488ca for displayid = 0 is not valid; is your activity running? 
    at android.view.ViewRootImpl.setView(ViewRootImpl.java:931) 
    at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:400) 
    at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:129) 
    at android.app.Dialog.show(Dialog.java:471) 
    at cn.migu.library.jzvideoplayer.JzvdPlayer.alertDialog(JzvdPlayer.java:291) 
    at cn.migu.library.jzvideoplayer.JzvdPlayer.showWifiDialog(JzvdPlayer.java:303) 
    at cn.migu.library.jzvideoplayer.JzvdPlayer.onStatePlaying(JzvdPlayer.java:532) 
    at cn.jzvd.Jzvd.goOnPlayOnResume(Jzvd.java:888) 

**复现流程
界面在onresume的时候调用，cn.jzvd.Jzvd.goOnPlayOnResume(Jzvd.java:888) ，偶现

**Comment by lipangit** [comment]
demo有这个问题吗

**Comment by memoryjs** [comment]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.post(java.lang.Runnable)' on a null object reference
	at cn.jzvd.JZMediaSystem.pause(JZMediaSystem.java:67)
	at cn.jzvd.Jzvd.goOnPlayOnPause(Jzvd.java:905)

Demo没有那么详细的测试，不过我又复现了一个，我们是有不同的地方有这个播放器，估计两个串扰了

**Comment by lipangit** [comment]
不是每次alertdialog都会出现这个错误吧

**Comment by memoryjs** [comment]
不是每次都出现，偶现的，这个问题可以规避掉

你看我第二个log，这个是内部的类空指针了，我的场景主要是两个不同的页面，都用到了播放器，是不是不同页面的播放器（都继承jzdstd），每次播放之前，每次播放之前，都要 resetAllVideos一把？把之前的播放记录清除掉？JZMediaSystem这里面的handler不知道为什么会为空

**Comment by lipangit** [comment]
这个问题可能比较具体

**Comment by memoryjs** [comment]
有机会修复下哈，我们现在就是在里面加了一个 try catch，但是始终不是长久的解决方法

**Comment by lipangit** [comment]
try catch 的地方能截图看看你的修改吗

**Comment by atuldhanuka1005** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.post(java.lang.Runnable)' on a null object reference
        at cn.jzvd.JZMediaSystem.start(JZMediaSystem.java:62)
        at cn.jzvd.Jzvd.onPrepared(Jzvd.java:349)
        at xxx.onPrepared(:93)
        at cn.jzvd.JZMediaSystem.lambda$onPrepared$6$JZMediaSystem(JZMediaSystem.java:139)
        at cn.jzvd.-$$Lambda$JZMediaSystem$zIW9UuYfRsLvwe6Lu-iDTY-nGW8.run(lambda)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by BLiYing** [comment]
# JZVD(5313)
java.lang.NullPointerException
Attempt to invoke virtual method 'void android.media.MediaPlayer.pause()' on a null object reference
1 cn.jzvd.JZMediaSystem.lambda$pause$2(JZMediaSystem.java:67)
--
2 cn.jzvd.-$$Lambda$JZMediaSystem$mIo-5qb9CM2v3VEXVrwpH962n_c.run(Unknown Source:2)
3 android.os.Handler.handleCallback(Handler.java:873)
4 android.os.Handler.dispatchMessage(Handler.java:99)
5 android.os.Looper.loop(Looper.java:201)
6 android.os.HandlerThread.run(HandlerThread.java:65)
