### ISSUE TITLE
在FragmentDialog中闪退报错，我显示dialog的Activity继承了AppCompatActivity

### ISSUE THREAD

**Issue by gwl026596** [lipangit/JiaoZiVideoPlayer#2564]
**什么jzvd版本

**是否和安卓版本有关系，什么版本

**是否和特定品牌的手机机型有关系，什么机型

**相关log是什么

**复现流程

**最好有截图或者视频说明情况
版本：implementation 'fm.jiecao:jiecaovideoplayer:5.5'

 java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v7.app.ActionBar android.support.v7.app.AppCompatActivity.getSupportActionBar()' on a null object reference
                                                                            at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.showSupportActionBar(JCVideoPlayer.java:878)
                                                                            at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.clearFullscreenLayout(JCVideoPlayer.java:446)
                                                                            at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onCompletion(JCVideoPlayer.java:482)
                                                                            at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerManager.completeAll(JCVideoPlayerManager.java:42)
                                                                            at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.prepareMediaPlayer(JCVideoPlayer.java:199)
                                                                            at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.startVideo(JCVideoPlayerStandard.java:238)
                                                                            at com.asianangel.app2019.card.dialog.PlayVideoFragmentDialog.getCreateView(PlayVideoFragmentDialog.java:63)

**Comment by lipangit** [comment]
每次都报错吗？

**Comment by gwl026596** [comment]
是的

**Comment by gwl026596** [comment]
感觉不能再dialog中用，我用的系统dialog也同样错误

**Comment by gwl026596** [comment]
怎么解决在Dialog播放视频用该播放控件

**Comment by gwl026596** [comment]
我现在用的Activity改样式成Dialog，效果不是很好，希望开源者能给出解决办法

**Comment by lipangit** [comment]
继承jzvdStd，复写showWifiDialog函数，写自己的没有wifi的逻辑
