### ISSUE TITLE
cn.jzvd.JZMediaSystem.start(JZMediaSystem.java:62)报空指针

### ISSUE THREAD

**Issue by forestAndroid** [lipangit/JiaoZiVideoPlayer#2631]
**什么jzvd版本
cn.jzvd:jiaozivideoplayer:7.0.5
**是否和安卓版本有关系，什么版本

**是否和特定品牌的手机机型有关系，什么机型

**相关log是什么
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.post(java.lang.Runnable)' on a null object reference
        at cn.jzvd.JZMediaSystem.start(JZMediaSystem.java:62)
        at cn.jzvd.Jzvd.onPrepared(Jzvd.java:349)
        at com.xxxxxxxxxxxxx.widgets.JzvdStdShowTitleAfterFullscreen.onPrepared(JzvdStdShowTitleAfterFullscreen.java:53)
        at cn.jzvd.JZMediaSystem.lambda$onPrepared$6$JZMediaSystem(JZMediaSystem.java:139)
        at cn.jzvd.-$$Lambda$JZMediaSystem$zIW9UuYfRsLvwe6Lu-iDTY-nGW8.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at com.wanjian.cockroach.Cockroach$1.run(Cockroach.java:47)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7586)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
**复现流程
不好复现，联网，断网，recycleview显示封面图，点击进详情页播放视频，播放页面偶尔出现，出现此情况后，所有界面的视频均无法播放
**最好有截图或者视频说明情况

**Comment by forestAndroid** [comment]
复现流程：
视频没加载播放就立即退出，再切换另一个视频，这样操作就会出现

**Comment by forestAndroid** [comment]
报空后进入播放视频界面，debug
![image](https://user-images.githubusercontent.com/10668022/67923697-8e02a300-fbe9-11e9-8b8b-4d0833a1a694.png)

**Comment by forestAndroid** [comment]
this.mediaInterface 里面的player等都为null了

**Comment by lipangit** [comment]
开始播放视频的时候，mediaInterface是重新生成的，在任何情况下都应该生成成功。这时候是空是为什么呢

**Comment by lipangit** [comment]
mediaInterfaceClass有值吧

**Comment by forestAndroid** [comment]
复现流程：
视频没加载播放就立即退出，再切换另一个视频，这样操作就会出现

**Comment by forestAndroid** [comment]
mediaInterfaceClass有值

**Comment by lipangit** [comment]
startVideo这个函数里会生成所有需要的播放器相关的变量，这些变量在任何情况下都应该能随时被生成，现在却生成不了。

**Comment by lipangit** [comment]
你在断点之后，哪个变量无法生成，卡在哪了

**Comment by forestAndroid** [comment]
进入界面，调试mediaplayer是null，无法播放，进度条一直在加载转圈

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/68544151-2c1d1700-03fb-11ea-830f-fa7ce650a114.png)

mediaPlayers是在这里生成的，走这步了吗

**Comment by forestAndroid** [comment]
这里没注意，有空的话，我再调试下

**Comment by frinda** [comment]
大神解决了么

**Comment by lipangit** [comment]
有啥线索吗  怎么样了

**Comment by MYaoDan** [comment]
> 报空后进入播放视频界面，debug
> ![image](https://user-images.githubusercontent.com/10668022/67923697-8e02a300-fbe9-11e9-8b8b-4d0833a1a694.png)

请问您解决了吗？怎么解决的？

**Comment by lipangit** [comment]
保持关注



---原始邮件---
发件人: "MYaoDan"<notifications@github.com&gt;
发送时间: 2020年5月13日(周三) 上午10:11
收件人: "lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [lipangit/JiaoZiVideoPlayer] cn.jzvd.JZMediaSystem.start(JZMediaSystem.java:62)报空指针 (#2631)




  
报空后进入播放视频界面，debug
 
  
请问您解决了吗？怎么解决的？
