### ISSUE TITLE
部分视频在三星手机上使用会加载失败

### ISSUE THREAD

**Issue by wananxin** [lipangit/JiaoZiVideoPlayer#2641]
**需求描述
首先使用的默认播放内核，发现部分手机播放正常，流畅，但是在三星手机上使用就回加载失败，
然后我使用JZMediaExo内核去播放，三星手机上就可以正常播放，但是在其他手机上就会引起当播放完一个视频后  再去加载其他的视频都是停留在加载页面，再也不会正常播放了

**其他app是否实现

**截图或者小视频说明

**Comment by wananxin** [comment]
这个视频是苹果手机上处理发出的视频

**Comment by wananxin** [comment]
http://replace-i.oss-cn-hangzhou.aliyuncs.com/image/2019/9/12/2c91d0306d166c3a016d2505eaa101aa.mp4类似于这个

**Comment by wangzixu5678** [comment]
同上 你不是一个人。

**Comment by wangzixu5678** [comment]
我觉得这些新版本有很多问题 想问一下 哪个版本最稳定 不想被这些版本搞得焦头烂额了

**Comment by lipangit** [comment]
什么问题具体说说

**Comment by joshuaGnol** [comment]
`E/ExoPlayerImplInternal: Internal runtime error.
    java.lang.IllegalStateException: Buffer too small (1572864 < 1595719)
        at com.google.android.exoplayer2.decoder.DecoderInputBuffer.createReplacementByteBuffer(DecoderInputBuffer.java:167)
        at com.google.android.exoplayer2.decoder.DecoderInputBuffer.ensureSpaceForWrite(DecoderInputBuffer.java:117)
        at com.google.android.exoplayer2.source.SampleQueue.read(SampleQueue.java:356)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod.readData(ProgressiveMediaPeriod.java:454)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$SampleStreamImpl.readData(ProgressiveMediaPeriod.java:877)
        at com.google.android.exoplayer2.BaseRenderer.readSource(BaseRenderer.java:308)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1028)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:658)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:575)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:326)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:65)`

有些视频在三星遇到， 但是其他牌子不会遇到。
