### ISSUE TITLE
java.lang.IllegalStateException: Handler (android.os.Handler) {d576486} sending message to a Handler on a dead thread

### ISSUE THREAD

**Issue by lifeidroid** [lipangit/JiaoZiVideoPlayer#2653]
**什么jzvd版本
7.0.5
**是否和安卓版本有关系，什么版本
7.1.1
**是否和特定品牌的手机机型有关系，什么机型
  联想平板TB-X304F
**相关log是什么
2019-11-25 09:43:37.691 26462-26462/? W/MessageQueue: Handler (android.os.Handler) {d576486} sending message to a Handler on a dead thread
    java.lang.IllegalStateException: Handler (android.os.Handler) {d576486} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
        at android.os.Handler.enqueueMessage(Handler.java:643)
        at android.os.Handler.sendMessageAtTime(Handler.java:612)
        at android.os.Handler.sendMessageDelayed(Handler.java:582)
        at android.os.Handler.post(Handler.java:338)
        at cn.jzvd.JZMediaSystem.start(JZMediaSystem.java:63)
        at cn.jzvd.Jzvd.c(Jzvd.java:349)
        at cn.jzvd.JZMediaSystem.lambda$onPrepared$6(JZMediaSystem.java:151)
        at cn.jzvd.-$$Lambda$JZMediaSystem$zIW9UuYfRsLvwe6Lu-iDTY-nGW8.run(lambda)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
**复现流程
 我的使用场景是在一个Activity中用播放器切换播放多个视频，多次启动关闭这个Activity后，可能会出错，播放器黑屏。重新关闭打开Activity正常
**最好有截图或者视频说明情况
出错后播放器黑屏

**Comment by lifeidroid** [comment]
我怀疑是在上一个视频播放完成时立马控制播放器播放另一个视频，会出现这个问题。
上一个视频播放完成时mMediaHandlerThread在release()中被quit了，这时立马播放另一个视频

**Comment by lipangit** [comment]
demo有这问题吗，这问题怎么样了
