### ISSUE TITLE
切换清晰度无法正常播放视频 

### ISSUE THREAD

**Issue by hekescott** [lipangit/JiaoZiVideoPlayer#2664]
**什么jzvd版本
JiaoZiVideoPlayer-7.0.5
**是否和安卓版本有关系，什么版本
无关  android 6.0.1
**是否和特定品牌的手机机型有关系，什么机型
无关    Redmi4
**相关log是什么
12-09 10:01:55.187 30768-31190/cn.jzvd.demo E/ExtMediaPlayer-JNI: env->IsInstanceOf fails
12-09 10:01:55.187 30768-31190/cn.jzvd.demo E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
12-09 10:01:55.187 30768-31190/cn.jzvd.demo E/ExtMediaPlayer-JNI: env->IsInstanceOf fails
12-09 10:01:55.187 30768-31190/cn.jzvd.demo E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
12-09 10:01:55.188 30768-31190/cn.jzvd.demo W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
12-09 10:01:55.193 30768-31190/cn.jzvd.demo W/System.err: java.lang.IllegalArgumentException: surfaceTexture must not be null
12-09 10:01:55.193 30768-31190/cn.jzvd.demo W/System.err:     at android.view.Surface.<init>(Surface.java:140)
12-09 10:01:55.193 30768-31190/cn.jzvd.demo W/System.err:     at cn.jzvd.JZMediaSystem.lambda$prepare$1(JZMediaSystem.java:53)
12-09 10:01:55.193 30768-31190/cn.jzvd.demo W/System.err:     at cn.jzvd.-$$Lambda$JZMediaSystem$e2SutBN53CzjsFLObMPROc0cb3E.run(lambda)
12-09 10:01:55.193 30768-31190/cn.jzvd.demo W/System.err:     at android.os.Handler.handleCallback(Handler.java:742)
12-09 10:01:55.194 30768-31190/cn.jzvd.demo W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
12-09 10:01:55.194 30768-31190/cn.jzvd.demo W/System.err:     at android.os.Looper.loop(Looper.java:157)
12-09 10:01:55.194 30768-31190/cn.jzvd.demo W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
12-09 10:01:55.194 30768-30779/cn.jzvd.demo D/MediaHTTPConnection: filterOutInternalHeaders: key=User-Agent, val= stagefright/1.2 (Linux;Android 6.0.1)
**复现流程
全屏播放，切换清晰度
**最好有截图或者视频说明情况
![image](https://user-images.githubusercontent.com/8383442/70401541-1850e900-1a6b-11ea-9463-0372363f90a7.png)

![image](https://user-images.githubusercontent.com/8383442/70401553-23a41480-1a6b-11ea-8866-0c5587d299f8.png)

**Comment by hekescott** [comment]
有声音视频，卡住不动

**Comment by hekescott** [comment]
![image](https://user-images.githubusercontent.com/8383442/70401640-8eede680-1a6b-11ea-9263-e2b20feae3a6.png)

**Comment by hekescott** [comment]
![image](https://user-images.githubusercontent.com/8383442/70401815-1cc9d180-1a6c-11ea-8362-aac1848fcf81.png)

**Comment by mydeerlet** [comment]
dome 中切换清晰度就这 画面卡住 声音 声音可以播放

**Comment by lipangit** [comment]
切换清晰度的本质就是换一个url播放。

**Comment by muqidi** [comment]
小米6，Android 9 系统也有出现同样的问题。
dome 中切换清晰度就这 画面卡住 声音 声音可以播放

**Comment by lipangit** [comment]
用新版



---原始邮件---
发件人: "muqidi"<notifications@github.com&gt;
发送时间: 2020年3月23日(周一) 晚上9:54
收件人: "lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [lipangit/JiaoZiVideoPlayer] 切换清晰度无法正常播放视频  (#2664)




 
小米6，Android 9 系统也有出现同样的问题。
 dome 中切换清晰度就这 画面卡住 声音 声音可以播放
