### ISSUE TITLE
The surface has been released

### ISSUE THREAD

**Issue by stardustsc** [lipangit/JiaoZiVideoPlayer#2669]
我使用的的版本是 6.2.12，经常出现崩溃的问题。
崩溃日志：   
 java.lang.IllegalArgumentException: The surface has been released
        at android.media.MediaPlayer._setVideoSurface(Native Method)
        at android.media.MediaPlayer.setSurface(MediaPlayer.java:795)
        at cn.jzvd.JZMediaSystem.setSurface(JZMediaSystem.java:97)
        at cn.jzvd.JZMediaManager$MediaHandler.handleMessage(JZMediaManager.java:154)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:222)
        at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by lipangit** [comment]
这是一个问题，怎么解决呢，有啥思路呢
