### ISSUE TITLE
7.2.0版本，直接全屏播放，结束后会出现空指针报错

### ISSUE THREAD

**Issue by Tracycuizh** [lipangit/JiaoZiVideoPlayer#2675]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Window android.app.Activity.getWindow()' on a null object reference
        at cn.jzvd.Jzvd.gotoScreenNormal(Jzvd.java:765)
        at cn.jzvd.Jzvd.onAutoCompletion(Jzvd.java:451)
        at cn.jzvd.JzvdStd.onAutoCompletion(JzvdStd.java:811)
        at cn.jzvd.JZMediaSystem.lambda$onCompletion$7$JZMediaSystem(JZMediaSystem.java:144)
        at cn.jzvd.JZMediaSystem$$Lambda$7.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7762)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)

**Comment by lipangit** [comment]
哪个jzvd版本，demo有这问题吗，实现步骤怎么样
