### ISSUE TITLE
压缩影片

### ISSUE THREAD

**Issue by joshuaGnol** [lipangit/JiaoZiVideoPlayer#2695]
**什么jzvd版本 - 7.4.1

**是否和安卓版本有关系，什么版本

**是否和特定品牌的手机机型有关系，什么机型 三星s8+(Android 9)， 三星s10+(Android 10)

**相关log是什么
`E/ExoPlayerImplInternal: Internal runtime error.
    java.lang.IllegalStateException: Buffer too small (1572864 < 1595719)
        at com.google.android.exoplayer2.decoder.DecoderInputBuffer.createReplacementByteBuffer(DecoderInputBuffer.java:167)
        at com.google.android.exoplayer2.decoder.DecoderInputBuffer.ensureSpaceForWrite(DecoderInputBuffer.java:117)
        at com.google.android.exoplayer2.source.SampleQueue.read(SampleQueue.java:356)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod.readData(ProgressiveMediaPeriod.java:454)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$SampleStreamImpl.readData(ProgressiveMediaPeriod.java:877)
        at com.google.android.exoplayer2.BaseRenderer.readSource(BaseRenderer.java:308)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1028)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:658)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:575)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:326)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:65)`

**复现流程

**最好有截图或者视频说明情况

**需求描述 - 能不能压缩影片大小 resolution . 目前在三星手机影片遇到了这个问题 （试了其他牌子没这个问题）

**其他app是否实现 - demo app 也遇到

**截图或者小视频说明

也许硬件支撑不了影片过大，能不能缩小影片来避免影片不能播放？

**Comment by lipangit** [comment]
播放内核不支持这个功能，研究一下内核有没有这个api



---原始邮件---
发件人: "joshuaGnol"<notifications@github.com&gt;
发送时间: 2020年5月29日(周五) 中午11:01
收件人: "lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [lipangit/JiaoZiVideoPlayer] 压缩影片 (#2695)




 
**什么jzvd版本 - 7.4.1
 
**是否和安卓版本有关系，什么版本
 
**是否和特定品牌的手机机型有关系，什么机型 三星s8+(Android 9)， 三星s10+(Android 10)
 
**相关log是什么
 E/ExoPlayerImplInternal: Internal runtime error. java.lang.IllegalStateException: Buffer too small (1572864 < 1595719) at com.google.android.exoplayer2.decoder.DecoderInputBuffer.createReplacementByteBuffer(DecoderInputBuffer.java:167) at com.google.android.exoplayer2.decoder.DecoderInputBuffer.ensureSpaceForWrite(DecoderInputBuffer.java:117) at com.google.android.exoplayer2.source.SampleQueue.read(SampleQueue.java:356) at com.google.android.exoplayer2.source.ProgressiveMediaPeriod.readData(ProgressiveMediaPeriod.java:454) at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$SampleStreamImpl.readData(ProgressiveMediaPeriod.java:877) at com.google.android.exoplayer2.BaseRenderer.readSource(BaseRenderer.java:308) at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1028) at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:658) at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:575) at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:326) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:214) at android.os.HandlerThread.run(HandlerThread.java:65)
 
**复现流程
 
**最好有截图或者视频说明情况
 
**需求描述 - 能不能压缩影片大小 resolution . 目前在三星手机影片遇到了这个问题 （试了其他牌子没这个问题）
 
**其他app是否实现 - demo app 也遇到
 
**截图或者小视频说明
 
也许硬件支撑不了影片过大，能不能缩小影片来避免影片不能播放？
