### ISSUE TITLE
问一下, setUp方法里面uri不支持内容提供器给的uri吗?

### ISSUE THREAD

**Issue by action-hong** [lipangit/JiaoZiVideoPlayer#760]
```
//打开资源管理器
Intent intent = new Intent(Intent.ACTION_GET_CONTENT);
intent.setType("*/*");
intent.addCategory(Intent.CATEGORY_OPENABLE);
startActivityForResult(intent, RESOURCE_REQUEST);

@Override
protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (resultCode != RESULT_OK) {
            Log.i(TAG, "onActivityResult: 失败, code = " + resultCode);
            return;
        }
        if (requestCode == RESOURCE_REQUEST) {
            //content://com.android.providers.media.documents/document/video%3A90743
            playVideo(data.getDataString());
        }
    }


private void playVideo(String uri) {
        mVideoView.setUp(uri, JCVideoPlayer.SCREEN_LAYOUT_NORMAL, "test");
        mVideoView.startVideo();
}

03-24 11:22:03.953 29552-29705/com.example.pver.constraintdemo W/System.err: java.lang.reflect.InvocationTargetException
03-24 11:22:03.953 29552-29705/com.example.pver.constraintdemo W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
03-24 11:22:03.953 29552-29705/com.example.pver.constraintdemo W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCMediaManager$MediaHandler.handleMessage(JCMediaManager.java:83)
03-24 11:22:03.953 29552-29705/com.example.pver.constraintdemo W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:105)
03-24 11:22:03.953 29552-29705/com.example.pver.constraintdemo W/System.err:     at android.os.Looper.loop(Looper.java:156)
03-24 11:22:03.953 29552-29705/com.example.pver.constraintdemo W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
03-24 11:22:03.953 29552-29705/com.example.pver.constraintdemo W/System.err: Caused by: java.io.IOException: setDataSource failed.: status=0x80000000
03-24 11:22:03.953 29552-29705/com.example.pver.constraintdemo W/System.err:     at android.media.MediaPlayer.nativeSetDataSource(Native Method)
03-24 11:22:03.953 29552-29705/com.example.pver.constraintdemo W/System.err:     at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1086)
03-24 11:22:03.953 29552-29705/com.example.pver.constraintdemo W/System.err:     at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1075)
03-24 11:22:03.953 29552-29705/com.example.pver.constraintdemo W/System.err: 	... 5 more
```

看了下里面的代码, 
```
//只反射了这个方法
Method method = clazz.getDeclaredMethod("setDataSource", String.class, Map.class);
method.invoke(mediaPlayer, CURRENT_PLAYING_URL, MAP_HEADER_DATA);

public void setDataSource(String path, Map<String, String> headers){
...
}


//没有反射这个
public void setDataSource(@NonNull Context context, @NonNull Uri uri,
            @Nullable Map<String, String> headers){
...
}
```

不知道我的理解有没有问题
这个东西是有其他方法可以播放吗? 有的话麻烦告诉一下 ...

**Comment by lipangit** [comment]
setDataSource我觉的是不需要传Context这个参数所以没反射这个函数，但是你的这种情况就需要了，你觉得怎么改能兼容uri呢

**Comment by action-hong** [comment]
@lipangit 
直接传个Context进去? 或者直接用textureView所持有的`Context` ? , 
改成下面那样, 内容提供器的uri也没问题, 跑了一下实例代码也没啥问题

```
//这边为什么要用反射?这个方法不是public的吗?
//Class<MediaPlayer> clazz = MediaPlayer.class;
//Method method = clazz.getDeclaredMethod("setDataSource", String.class, Map.class);
//method.invoke(mediaPlayer, CURRENT_PLAYING_URL, MAP_HEADER_DATA);
//直接使用这个带Context参数的?
mediaPlayer.setDataSource(textureView.getContext(), Uri.parse(CURRENT_PLAYING_URL), MAP_HEADER_DATA);
```

看了下该方法已经对file, content, http各个scheme进行处理了
```
public void setDataSource(@NonNull Context context, @NonNull Uri uri,
            @Nullable Map<String, String> headers) throws IOException, IllegalArgumentException,
                    SecurityException, IllegalStateException {
        final ContentResolver resolver = context.getContentResolver();
        final String scheme = uri.getScheme();
        if (ContentResolver.SCHEME_FILE.equals(scheme)) {
            //处理本地路径的视频
            setDataSource(uri.getPath());
            return;
        } else if (ContentResolver.SCHEME_CONTENT.equals(scheme)
                && Settings.AUTHORITY.equals(uri.getAuthority())) {
            //处理内容提供器提供的uri
              .....
        } else {
            // Try requested Uri locally first, or fallback to media server
            if (attemptDataSource(resolver, uri)) {
                return;
            } else {
                //原代码所使用的方法
                setDataSource(uri.toString(), headers);
            }
        }
    }
```
不过这么搞的话总感觉怪怪的, 而且初始化得传一个context进去

**Comment by lipangit** [comment]
有道理，我觉的视频地址应该从string型换成uri

**Comment by action-hong** [comment]
```
//多加一个方法?
public void setUp(Uri url, int screen, Object... objects) {
    checkNotNull(url);
    setUp(url.toString(), screen, objects);
}
```

如果要把`url`这个`field`改成`Uri`的话,感觉还是要改蛮多地方的

**Comment by lipangit** [comment]
是想这样改，更规范一些，能适应更多情况

**Comment by action-hong** [comment]
恩恩 加油了 体力活呀

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/27815055-e1c390ae-60b3-11e7-996a-976eae96b153.png)

@action-hong 我想把设置dataSource的方法暴露出来，怎么做好一些

**Comment by action-hong** [comment]
直接暴露给客户端调用吗? @lipangit

**Comment by lipangit** [comment]
对，让用户根据自己的情况去seSource，最好能把函数当参数去传递

在库的外面设置一个函数
OutSetDataSource（MediaPlayer mediaPlayer）{
  mediaPlayer.setDatasources()
}
然后在库里new完MediaPlayer之后调用这个OutSetDataSource函数

**Comment by lipangit** [comment]
现在支持了，用新版自定义播放引擎
