### ISSUE TITLE
Explicit termination method 'release' not called (Surface not released)

### ISSUE THREAD

**Issue by storix** [lipangit/JiaoZiVideoPlayer#804]
Hi,

When Strict Mode is enabled the following exception is thrown:

```
04-16 13:05:38.669 19336-19345/? E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                               java.lang.Throwable: Explicit termination method 'release' not called
                                                   at dalvik.system.CloseGuard.open(CloseGuard.java:184)
                                                   at android.view.Surface.setNativeObjectLocked(Surface.java:397)
                                                   at android.view.Surface.<init>(Surface.java:128)
                                                   at fm.jiecao.jcvideoplayer_lib.JCMediaManager$MediaHandler.handleMessage(Unknown Source)
                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                   at android.os.Looper.loop(Looper.java:136)
                                                   at android.os.HandlerThread.run(HandlerThread.java:61)
```

This is because [at this line](https://github.com/lipangit/JieCaoVideoPlayer/blob/913b61afc4da08b90314f0be53c5303bf7a13f15/jcvideoplayer-lib/src/main/java/fm/jiecao/jcvideoplayer_lib/JCMediaManager.java#L94) you are creating the `Surface` but it is never released.

As [shown](https://android.googlesource.com/platform/development/+/698cfb95876b55066f7b34879d03b6a4909d002f/ndk/platforms/android-14/samples/native-media/src/com/example/nativemedia/NativeMedia.java#369) in the Android samples the correct way to set the surface is like this:

```Java
mediaPlayer.setSurface(s);
s.release(); 
```
I think, you can do this without PR. Thanks.

**Comment by lipangit** [comment]
OK I will test these code.

**Comment by lipangit** [comment]
how todo @storix

**Comment by lipangit** [comment]
fix in onComplete() function
